// ecolarAdmin/src/main/webapp/app/house-hold-administration/house-hold/house-hold-detail.component.ts
import { Component, OnInit } from '@angular/core';
import { ActivatedRoute } from '@angular/router';

import { IHouseHold } from 'app/shared/model/house-hold.model';

@Component({
    selector: 'eco-house-hold-detail',
    templateUrl: './house-hold-detail.component.html'
})
export class HouseHoldDetailComponent implements OnInit {
    houseHold: IHouseHold;

    constructor(private activatedRoute: ActivatedRoute) {}

    ngOnInit() {
        this.activatedRoute.data.subscribe(({ houseHold }) => {
            this.houseHold = houseHold;
        });
    }

    previousState() {
        window.history.back();
    }
}

<div class="row justify-content-center">
    <div class="col-8">
        <div *ngIf="houseHold">
            <h2><span jhiTranslate="ecolarAdminApp.houseHold.detail.title">House Hold</span> {{houseHold.id}}</h2>
            <hr>
            <eco-alert-error></eco-alert-error>
            <dl class="row-md jh-entity-details">
                <dt><span jhiTranslate="ecolarAdminApp.houseHold.name">Name</span></dt>
                <dd>
                    <span>{{houseHold.name}}</span>
                </dd>
                <dt><span jhiTranslate="ecolarAdminApp.houseHold.members">Members</span></dt>
                <dd>
                    <span *ngFor="let members of houseHold.members; let last = last">
                        {{members.login}}{{last ? '' : ', '}}
                    </span>
                </dd>
            </dl>

            <button type="submit"
                    (click)="previousState()"
                    class="btn btn-info">
                <fa-icon [icon]="'arrow-left'"></fa-icon>&nbsp;<span jhiTranslate="entity.action.back"> Back</span>
            </button>

            <button type="button"
                    [routerLink]="['/house-hold', houseHold.id, 'edit']"
                    class="btn btn-primary">
                <fa-icon [icon]="'pencil-alt'"></fa-icon>&nbsp;<span jhiTranslate="entity.action.edit"> Edit</span>
            </button>
        </div>
    </div>
</div>

// ecolarMobile/src/main/webapp/app/entities/house-hold/house-hold-detail.tsx
import React from 'react';
import { connect } from 'react-redux';
import { Link, RouteComponentProps } from 'react-router-dom';
import { Button, Row, Col } from 'reactstrap';
// tslint:disable-next-line:no-unused-variable
import { Translate, ICrudGetAction } from 'react-jhipster';
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome';

import { IRootState } from 'app/shared/reducers';
import { getEntity } from './house-hold.reducer';
import { IHouseHold } from 'app/shared/model/house-hold.model';
// tslint:disable-next-line:no-unused-variable
import { APP_DATE_FORMAT, APP_LOCAL_DATE_FORMAT } from 'app/config/constants';

export interface IHouseHoldDetailProps extends StateProps, DispatchProps, RouteComponentProps<{ id: string }> {}

export class HouseHoldDetail extends React.Component<IHouseHoldDetailProps> {
  componentDidMount() {
    this.props.getEntity(this.props.match.params.id);
  }

  render() {
    const { houseHoldEntity } = this.props;
    return (
      <Row>
        <Col md="8">
          <h2>
            <Translate contentKey="ecolarMobileApp.houseHold.detail.title">HouseHold</Translate> [<b>{houseHoldEntity.id}</b>]
          </h2>
          <dl className="jh-entity-details">
            <dt>
              <span id="name">
                <Translate contentKey="ecolarMobileApp.houseHold.name">Name</Translate>
              </span>
            </dt>
            <dd>{houseHoldEntity.name}</dd>
            <dt>
              <Translate contentKey="ecolarMobileApp.houseHold.accountCategories">Account Categories</Translate>
            </dt>
            <dd>{houseHoldEntity.accountCategories ? houseHoldEntity.accountCategories.id : ''}</dd>
            <dt>
              <Translate contentKey="ecolarMobileApp.houseHold.members">Members</Translate>
            </dt>
            <dd>
              {houseHoldEntity.members
                ? houseHoldEntity.members.map((val, i) => (
                    <span key={val.id}>
                      <a>{val.login}</a>
                      {i === houseHoldEntity.members.length - 1 ? '' : ', '}
                    </span>
                  ))
                : null}{' '}
            </dd>
          </dl>
          <Button tag={Link} to="/entity/house-hold" replace color="info">
            <FontAwesomeIcon icon="arrow-left" />{' '}
            <span className="d-none d-md-inline">
              <Translate contentKey="entity.action.back">Back</Translate>
            </span>
          </Button>&nbsp;
          <Button tag={Link} to={`/entity/house-hold/${houseHoldEntity.id}/edit`} replace color="primary">
            <FontAwesomeIcon icon="pencil-alt" />{' '}
            <span className="d-none d-md-inline">
              <Translate contentKey="entity.action.edit">Edit</Translate>
            </span>
          </Button>
        </Col>
      </Row>
    );
  }
}

const mapStateToProps = ({ houseHold }: IRootState) => ({
  houseHoldEntity: houseHold.entity
});

const mapDispatchToProps = { getEntity };

type StateProps = ReturnType<typeof mapStateToProps>;
type DispatchProps = typeof mapDispatchToProps;

export default connect(
  mapStateToProps,
  mapDispatchToProps
)(HouseHoldDetail);
