// ecolar-mobile/src/main/webapp/app/entities/house-hold/house-hold.vue
<template>
    <div>
        <h2 id="page-heading">
            <span v-text="$t('ecolarApp.houseHold.home.title')" id="house-hold-heading">House Holds</span>
            <router-link to="/entity/house-hold/new" tag="button" id="jh-create-entity" class="btn btn-primary float-right jh-create-entity create-house-hold">
                <font-awesome-icon icon="plus"></font-awesome-icon>
                <span  v-text="$t('ecolarApp.houseHold.home.createLabel')">
                    Create new HouseHold
                </span>
            </router-link>
        </h2>
        <!--<jhi-alert></jhi-alert>-->
        <br/>
        <div class="table-responsive" v-if="houseHolds">
            <table class="table table-striped">
                <thead>
                <tr>
                    <th><span v-text="$t('global.field.id')">ID</span></th>
                        <th><span v-text="$t('ecolarApp.houseHold.name')">Name</span></th>
                            <th><span v-text="$t('ecolarApp.houseHold.accountCategories')">Account Categories</span></th>
                            <th><span v-text="$t('ecolarApp.houseHold.members')">Members</span></th>
                    <th></th>
                </tr>
                </thead>
                <tbody>
                <tr v-for="houseHold in houseHolds">
                    <td><router-link :to="{name: 'HouseHoldView', params: {houseHoldId: houseHold.id}}">{{houseHold.id}}</router-link></td>
                            <td>{{houseHold.name}}</td>
                        <td>
                                        <div v-if="houseHold.accountCategories">
                                            <router-link :to="'../entity/account-categories/' + houseHold.accountCategories.id + '/view'" >{{houseHold.accountCategories.id}}</router-link>
                                        </div>
                        </td>
                        <td>
                                    <span v-for="members in houseHold.members">
                                        {{members.login}}{{last ? '' : ', '}}
                                    </span>
                        </td>
                    <td class="text-right">
                        <div class="btn-group flex-btn-group-container">
                            <router-link :to="{name: 'HouseHoldView', params: {houseHoldId: houseHold.id}}" tag="button" class="btn btn-info btn-sm">
                                <font-awesome-icon icon="eye"></font-awesome-icon>
                                <span class="d-none d-md-inline" v-text="$t('entity.action.view')">View</span>
                            </router-link>
                            <router-link :to="{name: 'HouseHoldEdit', params: {houseHoldId: houseHold.id}}"  tag="button" class="btn btn-primary btn-sm">
                                <font-awesome-icon icon="pencil-alt"></font-awesome-icon>
                                <span class="d-none d-md-inline" v-text="$t('entity.action.edit')">Edit</span>
                            </router-link>
                            <b-btn v-on:click="prepareRemove(houseHold)"
                                   class="btn btn-danger btn-sm"
                                   v-b-modal.removeEntity>
                                <font-awesome-icon icon="times"></font-awesome-icon>
                                <span class="d-none d-md-inline" v-text="$t('entity.action.delete')">Delete</span>
                            </b-btn>
                        </div>
                    </td>
                </tr>
                </tbody>
            </table>
        </div>
        <b-modal ref="removeEntity" id="removeEntity" >
            <span slot="modal-title"><span id="ecolarApp.houseHold.delete.question" v-text="$t('entity.delete.title')">Confirm delete operation</span></span>
            <div class="modal-body">
                <p id="eco-delete-houseHold-heading" v-bind:title="$t('ecolarApp.houseHold.delete.question')">Are you sure you want to delete this House Hold?</p>
            </div>
            <div slot="modal-footer">
                <button type="button" class="btn btn-secondary" v-text="$t('entity.action.cancel')" v-on:click="closeDialog()">Cancel</button>
                <button type="button" class="btn btn-primary" id="eco-confirm-delete-houseHold" v-text="$t('entity.action.delete')" v-on:click="removeHouseHold()">Delete</button>
            </div>
        </b-modal>
    </div>
</template>

<script lang="ts" src="./house-hold.component.ts">
</script>

// ecolarMobile/src/main/webapp/app/entities/house-hold/house-hold.tsx
import React from 'react';
import { connect } from 'react-redux';
import { Link, RouteComponentProps } from 'react-router-dom';
import { Button, Col, Row, Table } from 'reactstrap';
// tslint:disable-next-line:no-unused-variable
import { Translate, ICrudGetAllAction } from 'react-jhipster';
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome';

import { IRootState } from 'app/shared/reducers';
import { getEntities } from './house-hold.reducer';
import { IHouseHold } from 'app/shared/model/house-hold.model';
// tslint:disable-next-line:no-unused-variable
import { APP_DATE_FORMAT, APP_LOCAL_DATE_FORMAT } from 'app/config/constants';

export interface IHouseHoldProps extends StateProps, DispatchProps, RouteComponentProps<{ url: string }> {}

export class HouseHold extends React.Component<IHouseHoldProps> {
  componentDidMount() {
    this.props.getEntities();
  }

  render() {
    const { houseHoldList, match } = this.props;
    return (
      <div>
        <h2 id="house-hold-heading">
          <Translate contentKey="ecolarMobileApp.houseHold.home.title">House Holds</Translate>
          <Link to={`${match.url}/new`} className="btn btn-primary float-right jh-create-entity" id="jh-create-entity">
            <FontAwesomeIcon icon="plus" />&nbsp;
            <Translate contentKey="ecolarMobileApp.houseHold.home.createLabel">Create new House Hold</Translate>
          </Link>
        </h2>
        <div className="table-responsive">
          <Table responsive>
            <thead>
              <tr>
                <th>
                  <Translate contentKey="global.field.id">ID</Translate>
                </th>
                <th>
                  <Translate contentKey="ecolarMobileApp.houseHold.name">Name</Translate>
                </th>
                <th>
                  <Translate contentKey="ecolarMobileApp.houseHold.accountCategories">Account Categories</Translate>
                </th>
                <th>
                  <Translate contentKey="ecolarMobileApp.houseHold.members">Members</Translate>
                </th>
                <th />
              </tr>
            </thead>
            <tbody>
              {houseHoldList.map((houseHold, i) => (
                <tr key={`entity-${i}`}>
                  <td>
                    <Button tag={Link} to={`${match.url}/${houseHold.id}`} color="link" size="sm">
                      {houseHold.id}
                    </Button>
                  </td>
                  <td>{houseHold.name}</td>
                  <td>
                    {houseHold.accountCategories ? (
                      <Link to={`account-categories/${houseHold.accountCategories.id}`}>{houseHold.accountCategories.id}</Link>
                    ) : (
                      ''
                    )}
                  </td>
                  <td>
                    {houseHold.members
                      ? houseHold.members.map((val, j) => (
                          <span key={j}>
                            {val.login}
                            {j === houseHold.members.length - 1 ? '' : ', '}
                          </span>
                        ))
                      : null}
                  </td>
                  <td className="text-right">
                    <div className="btn-group flex-btn-group-container">
                      <Button tag={Link} to={`${match.url}/${houseHold.id}`} color="info" size="sm">
                        <FontAwesomeIcon icon="eye" />{' '}
                        <span className="d-none d-md-inline">
                          <Translate contentKey="entity.action.view">View</Translate>
                        </span>
                      </Button>
                      <Button tag={Link} to={`${match.url}/${houseHold.id}/edit`} color="primary" size="sm">
                        <FontAwesomeIcon icon="pencil-alt" />{' '}
                        <span className="d-none d-md-inline">
                          <Translate contentKey="entity.action.edit">Edit</Translate>
                        </span>
                      </Button>
                      <Button tag={Link} to={`${match.url}/${houseHold.id}/delete`} color="danger" size="sm">
                        <FontAwesomeIcon icon="trash" />{' '}
                        <span className="d-none d-md-inline">
                          <Translate contentKey="entity.action.delete">Delete</Translate>
                        </span>
                      </Button>
                    </div>
                  </td>
                </tr>
              ))}
            </tbody>
          </Table>
        </div>
      </div>
    );
  }
}

const mapStateToProps = ({ houseHold }: IRootState) => ({
  houseHoldList: houseHold.entities
});

const mapDispatchToProps = {
  getEntities
};

type StateProps = ReturnType<typeof mapStateToProps>;
type DispatchProps = typeof mapDispatchToProps;

export default connect(
  mapStateToProps,
  mapDispatchToProps
)(HouseHold);
