// ecolarMobile/src/main/webapp/app/entities/accounts-document/accounts-document.tsx
import React from 'react';
import { connect } from 'react-redux';
import { Link, RouteComponentProps } from 'react-router-dom';
import { Button, Col, Row, Table } from 'reactstrap';
// tslint:disable-next-line:no-unused-variable
import { Translate, ICrudGetAllAction } from 'react-jhipster';
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome';

import { IRootState } from 'app/shared/reducers';
import { getEntities } from './accounts-document.reducer';
import { IAccountsDocument } from 'app/shared/model/accounts-document.model';
// tslint:disable-next-line:no-unused-variable
import { APP_DATE_FORMAT, APP_LOCAL_DATE_FORMAT } from 'app/config/constants';

export interface IAccountsDocumentProps extends StateProps, DispatchProps, RouteComponentProps<{ url: string }> {}

export class AccountsDocument extends React.Component<IAccountsDocumentProps> {
  componentDidMount() {
    this.props.getEntities();
  }

  render() {
    const { accountsDocumentList, match } = this.props;
    return (
      <div>
        <h2 id="accounts-document-heading">
          <Translate contentKey="ecolarMobileApp.accountsDocument.home.title">Accounts Documents</Translate>
          <Link to={`${match.url}/new`} className="btn btn-primary float-right jh-create-entity" id="jh-create-entity">
            <FontAwesomeIcon icon="plus" />&nbsp;
            <Translate contentKey="ecolarMobileApp.accountsDocument.home.createLabel">Create new Accounts Document</Translate>
          </Link>
        </h2>
        <div className="table-responsive">
          <Table responsive>
            <thead>
              <tr>
                <th>
                  <Translate contentKey="global.field.id">ID</Translate>
                </th>
                <th />
              </tr>
            </thead>
            <tbody>
              {accountsDocumentList.map((accountsDocument, i) => (
                <tr key={`entity-${i}`}>
                  <td>
                    <Button tag={Link} to={`${match.url}/${accountsDocument.id}`} color="link" size="sm">
                      {accountsDocument.id}
                    </Button>
                  </td>
                  <td className="text-right">
                    <div className="btn-group flex-btn-group-container">
                      <Button tag={Link} to={`${match.url}/${accountsDocument.id}`} color="info" size="sm">
                        <FontAwesomeIcon icon="eye" />{' '}
                        <span className="d-none d-md-inline">
                          <Translate contentKey="entity.action.view">View</Translate>
                        </span>
                      </Button>
                      <Button tag={Link} to={`${match.url}/${accountsDocument.id}/edit`} color="primary" size="sm">
                        <FontAwesomeIcon icon="pencil-alt" />{' '}
                        <span className="d-none d-md-inline">
                          <Translate contentKey="entity.action.edit">Edit</Translate>
                        </span>
                      </Button>
                      <Button tag={Link} to={`${match.url}/${accountsDocument.id}/delete`} color="danger" size="sm">
                        <FontAwesomeIcon icon="trash" />{' '}
                        <span className="d-none d-md-inline">
                          <Translate contentKey="entity.action.delete">Delete</Translate>
                        </span>
                      </Button>
                    </div>
                  </td>
                </tr>
              ))}
            </tbody>
          </Table>
        </div>
      </div>
    );
  }
}

const mapStateToProps = ({ accountsDocument }: IRootState) => ({
  accountsDocumentList: accountsDocument.entities
});

const mapDispatchToProps = {
  getEntities
};

type StateProps = ReturnType<typeof mapStateToProps>;
type DispatchProps = typeof mapDispatchToProps;

export default connect(
  mapStateToProps,
  mapDispatchToProps
)(AccountsDocument);

// ecolarAdmin/src/main/webapp/app/entities/accounts-document/accounts-document.component.ts
import { Component, OnInit, OnDestroy } from '@angular/core';
import { HttpErrorResponse, HttpResponse } from '@angular/common/http';
import { Subscription } from 'rxjs';
import { JhiEventManager, JhiAlertService } from 'ng-jhipster';

import { IAccountsDocument } from 'app/shared/model/accounts-document.model';
import { Principal } from 'app/core';
import { AccountsDocumentService } from './accounts-document.service';

@Component({
    selector: 'eco-accounts-document',
    templateUrl: './accounts-document.component.html'
})
export class AccountsDocumentComponent implements OnInit, OnDestroy {
    accountsDocuments: IAccountsDocument[];
    currentAccount: any;
    eventSubscriber: Subscription;

    constructor(
        private accountsDocumentService: AccountsDocumentService,
        private jhiAlertService: JhiAlertService,
        private eventManager: JhiEventManager,
        private principal: Principal
    ) {}

    loadAll() {
        this.accountsDocumentService.query().subscribe(
            (res: HttpResponse<IAccountsDocument[]>) => {
                this.accountsDocuments = res.body;
            },
            (res: HttpErrorResponse) => this.onError(res.message)
        );
    }

    ngOnInit() {
        this.loadAll();
        this.principal.identity().then(account => {
            this.currentAccount = account;
        });
        this.registerChangeInAccountsDocuments();
    }

    ngOnDestroy() {
        this.eventManager.destroy(this.eventSubscriber);
    }

    trackId(index: number, item: IAccountsDocument) {
        return item.id;
    }

    registerChangeInAccountsDocuments() {
        this.eventSubscriber = this.eventManager.subscribe('accountsDocumentListModification', response => this.loadAll());
    }

    private onError(errorMessage: string) {
        this.jhiAlertService.error(errorMessage, null, null);
    }
}

<div>
    <h2 id="page-heading">
        <span jhiTranslate="ecolarAdminApp.accountsDocument.home.title">Accounts Documents</span>
        <button id="jh-create-entity" class="btn btn-primary float-right jh-create-entity create-accounts-document" [routerLink]="['/accounts-document/new']">
            <fa-icon [icon]="'plus'"></fa-icon>
            <span  jhiTranslate="ecolarAdminApp.accountsDocument.home.createLabel">
            Create new Accounts Document
            </span>
        </button>
    </h2>
    <eco-alert></eco-alert>
    <br/>
    <div class="table-responsive" *ngIf="accountsDocuments">
        <table class="table table-striped">
            <thead>
            <tr>
            <th><span jhiTranslate="global.field.id">ID</span></th>
            <th></th>
            </tr>
            </thead>
            <tbody>
            <tr *ngFor="let accountsDocument of accountsDocuments ;trackBy: trackId">
                <td><a [routerLink]="['/accounts-document', accountsDocument.id, 'view' ]">{{accountsDocument.id}}</a></td>
                <td class="text-right">
                    <div class="btn-group flex-btn-group-container">
                        <button type="submit"
                                [routerLink]="['/accounts-document', accountsDocument.id, 'view' ]"
                                class="btn btn-info btn-sm">
                            <fa-icon [icon]="'eye'"></fa-icon>
                            <span class="d-none d-md-inline" jhiTranslate="entity.action.view">View</span>
                        </button>
                        <button type="submit"
                                [routerLink]="['/accounts-document', accountsDocument.id, 'edit']"
                                class="btn btn-primary btn-sm">
                            <fa-icon [icon]="'pencil-alt'"></fa-icon>
                            <span class="d-none d-md-inline" jhiTranslate="entity.action.edit">Edit</span>
                        </button>
                        <button type="submit"
                                [routerLink]="['/', { outlets: { popup: 'accounts-document/'+ accountsDocument.id + '/delete'} }]"
                                replaceUrl="true"
                                queryParamsHandling="merge"
                                class="btn btn-danger btn-sm">
                            <fa-icon [icon]="'times'"></fa-icon>
                            <span class="d-none d-md-inline" jhiTranslate="entity.action.delete">Delete</span>
                        </button>
                    </div>
                </td>
            </tr>
            </tbody>
        </table>
    </div>
</div>
