// ecolarAdmin/src/main/webapp/app/house-holds/house-hold/house-hold-update.component.ts
import { Component, OnInit } from '@angular/core';
import { ActivatedRoute } from '@angular/router';
import { HttpResponse, HttpErrorResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { JhiAlertService } from 'ng-jhipster';

import { IHouseHold } from 'app/shared/model/house-hold.model';
import { HouseHoldService } from '../house-hold.service';
import { IAccountCategories } from 'app/shared/model/account-categories.model';
import { IUser, UserService } from 'app/core';

@Component({
    selector: 'eco-house-hold-update',
    templateUrl: './house-hold-update.component.html'
})
export class HouseHoldUpdateComponent implements OnInit {
    houseHold: IHouseHold;
    isSaving: boolean;

    accountcategories: IAccountCategories[];

    users: IUser[];

    constructor(
        private jhiAlertService: JhiAlertService,
        private houseHoldService: HouseHoldService,
        private userService: UserService,
        private activatedRoute: ActivatedRoute
    ) {}

    ngOnInit() {
        this.isSaving = false;
        this.activatedRoute.data.subscribe(({ houseHold }) => {
            this.houseHold = houseHold;
        });
        this.userService.query().subscribe(
            (res: HttpResponse<IUser[]>) => {
                this.users = res.body;
            },
            (res: HttpErrorResponse) => this.onError(res.message)
        );
    }

    previousState() {
        window.history.back();
    }

    save() {
        this.isSaving = true;
        if (this.houseHold.id !== undefined) {
            this.subscribeToSaveResponse(this.houseHoldService.update(this.houseHold));
        } else {
            this.subscribeToSaveResponse(this.houseHoldService.create(this.houseHold));
        }
    }

    private subscribeToSaveResponse(result: Observable<HttpResponse<IHouseHold>>) {
        result.subscribe((res: HttpResponse<IHouseHold>) => this.onSaveSuccess(), (res: HttpErrorResponse) => this.onSaveError());
    }

    private onSaveSuccess() {
        this.isSaving = false;
        this.previousState();
    }

    private onSaveError() {
        this.isSaving = false;
    }

    private onError(errorMessage: string) {
        this.jhiAlertService.error(errorMessage, null, null);
    }

    trackAccountCategoriesById(index: number, item: IAccountCategories) {
        return item.id;
    }

    trackUserById(index: number, item: IUser) {
        return item.id;
    }

    getSelected(selectedVals: Array<any>, option: any) {
        if (selectedVals) {
            for (let i = 0; i < selectedVals.length; i++) {
                if (option.id === selectedVals[i].id) {
                    return selectedVals[i];
                }
            }
        }
        return option;
    }
}

<div class="row justify-content-center">
    <div class="col-8">
        <form name="editForm" role="form" novalidate (ngSubmit)="save()" #editForm="ngForm">
            <h2 id="eco-house-hold-heading" jhiTranslate="ecolarAdminApp.houseHold.home.createOrEditLabel">Create or edit a House Hold</h2>
            <div>
                <eco-alert-error></eco-alert-error>
                <div class="form-group" [hidden]="!houseHold.id">
                    <label for="id" jhiTranslate="global.field.id">ID</label>
                    <input type="text" class="form-control" id="id" name="id"
                        [(ngModel)]="houseHold.id" readonly />
                </div>
                <div class="form-group">
                    <label class="form-control-label" jhiTranslate="ecolarAdminApp.houseHold.name" for="field_name">Name</label>
                    <input type="text" class="form-control" name="name" id="field_name"
                        [(ngModel)]="houseHold.name" />
                </div>

                <div class="form-group">
                    <label jhiTranslate="ecolarAdminApp.houseHold.members" for="field_members">Members</label>
                    <select class="form-control" id="field_members" multiple name="members" [(ngModel)]="houseHold.members">
                        <option [ngValue]="getSelected(houseHold.members, userOption)" *ngFor="let userOption of users; trackBy: trackUserById">{{userOption.login}}</option>
                    </select>
                </div>
            </div>
            <div>
                <button type="button" id="cancel-save" class="btn btn-secondary"  (click)="previousState()">
                    <fa-icon [icon]="'ban'"></fa-icon>&nbsp;<span jhiTranslate="entity.action.cancel">Cancel</span>
                </button>
                <button type="submit" id="save-entity" [disabled]="editForm.form.invalid || isSaving" class="btn btn-primary">
                    <fa-icon [icon]="'save'"></fa-icon>&nbsp;<span jhiTranslate="entity.action.save">Save</span>
                </button>
            </div>
        </form>
    </div>
</div>

// ecolar-mobile/src/main/webapp/app/entities/house-hold/house-hold-update.vue
<template>
    <div class="row justify-content-center">
        <div class="col-8">
            <form name="editForm" role="form" novalidate v-on:submit.prevent="save()" >
                <h2 id="ecolarApp.houseHold.home.createOrEditLabel" v-text="$t('ecolarApp.houseHold.home.createOrEditLabel')">Create or edit a HouseHold</h2>
                <div>
                    <!--<jhi-alert-error></jhi-alert-error>-->
                    <div class="form-group" v-if="houseHold.id">
                        <label for="id" v-text="$t('global.field.id')">ID</label>
                        <input type="text" class="form-control" id="id" name="id"
                               v-model="houseHold.id" readonly />
                    </div>

                    <div class="form-group">
                        <label class="form-control-label" v-text="$t('ecolarApp.houseHold.name')" for="house-hold-name">Name</label>
                        <input type="text" class="form-control" name="name" id="house-hold-name"
                            :class="{'valid': !$v.houseHold.name.$invalid, 'invalid': $v.houseHold.name.$invalid }" v-model="$v.houseHold.name.$model" />
                    </div>

                        <div class="form-group">
                            <label class="form-control-label" v-text="$t('ecolarApp.houseHold.accountCategories')" for="house-hold-accountCategories">Account Categories</label>
                                <select class="form-control" id="house-hold-accountCategories" name="accountCategories" v-model="houseHold.accountCategories">
                                    <option value="null"></option>
                                    <option v-bind:value="houseHold.accountCategories && accountCategoriesOption.id === houseHold.accountCategories.id ? houseHold.accountCategories : accountCategoriesOption" v-for="accountCategoriesOption in accountCategories">{{accountCategoriesOption.id}}</option>
                                </select>
                        </div>
                        <div class="form-group">
                            <label v-text="$t('ecolarApp.houseHold.members')" for="house-hold-members">Members</label>
                            <select class="form-control" id="house-hold-members" multiple name="members" v-model="houseHold.members">
                                <option v-bind:value="getSelected(houseHold.members, userOption)" v-for="userOption in users">{{userOption.login}}</option>
                            </select>
                        </div>

                </div>
                <div>
                    <button type="button" id="cancel-save" class="btn btn-secondary" v-on:click="previousState()">
                        <font-awesome-icon icon="ban"></font-awesome-icon>&nbsp;<span v-text="$t('entity.action.cancel')">Cancel</span>
                    </button>
                    <button type="submit" id="save-entity" :disabled="$v.houseHold.$invalid || isSaving" class="btn btn-primary">
                        <font-awesome-icon icon="save"></font-awesome-icon>&nbsp;<span v-text="$t('entity.action.save')">Save</span>
                    </button>
                </div>
            </form>
        </div>
    </div>
</template>
<script lang="ts" src="./house-hold-update.component.ts">
</script>
