// ecolarAdmin/src/main/webapp/app/entities/house-hold/house-hold.component.ts
import { Component, OnInit, OnDestroy } from '@angular/core';
import { HttpErrorResponse, HttpResponse } from '@angular/common/http';
import { Subscription } from 'rxjs';
import { JhiEventManager, JhiAlertService } from 'ng-jhipster';

import { IHouseHold } from 'app/shared/model/house-hold.model';
import { Principal } from 'app/core';
import { HouseHoldService } from './house-hold.service';

@Component({
    selector: 'eco-house-hold',
    templateUrl: './house-hold.component.html'
})
export class HouseHoldComponent implements OnInit, OnDestroy {
    houseHolds: IHouseHold[];
    currentAccount: any;
    eventSubscriber: Subscription;

    constructor(
        private houseHoldService: HouseHoldService,
        private jhiAlertService: JhiAlertService,
        private eventManager: JhiEventManager,
        private principal: Principal
    ) {}

    loadAll() {
        this.houseHoldService.query().subscribe(
            (res: HttpResponse<IHouseHold[]>) => {
                this.houseHolds = res.body;
            },
            (res: HttpErrorResponse) => this.onError(res.message)
        );
    }

    ngOnInit() {
        this.loadAll();
        this.principal.identity().then(account => {
            this.currentAccount = account;
        });
        this.registerChangeInHouseHolds();
    }

    ngOnDestroy() {
        this.eventManager.destroy(this.eventSubscriber);
    }

    trackId(index: number, item: IHouseHold) {
        return item.id;
    }

    registerChangeInHouseHolds() {
        this.eventSubscriber = this.eventManager.subscribe('houseHoldListModification', response => this.loadAll());
    }

    private onError(errorMessage: string) {
        this.jhiAlertService.error(errorMessage, null, null);
    }
}

<div>
    <h2 id="page-heading">
        <span jhiTranslate="ecolarAdminApp.houseHold.home.title">House Holds</span>
        <button id="jh-create-entity" class="btn btn-primary float-right jh-create-entity create-house-hold" [routerLink]="['/house-hold/new']">
            <fa-icon [icon]="'plus'"></fa-icon>
            <span  jhiTranslate="ecolarAdminApp.houseHold.home.createLabel">
            Create new House Hold
            </span>
        </button>
    </h2>
    <eco-alert></eco-alert>
    <br/>
    <div class="table-responsive" *ngIf="houseHolds">
        <table class="table table-striped">
            <thead>
            <tr>
            <th><span jhiTranslate="global.field.id">ID</span></th>
            <th><span jhiTranslate="ecolarAdminApp.houseHold.name">Name</span></th>
            <th><span jhiTranslate="ecolarAdminApp.houseHold.accountsDocument">Accounts Document</span></th>
            <th><span jhiTranslate="ecolarAdminApp.houseHold.members">Members</span></th>
            <th></th>
            </tr>
            </thead>
            <tbody>
            <tr *ngFor="let houseHold of houseHolds ;trackBy: trackId">
                <td><a [routerLink]="['/house-hold', houseHold.id, 'view' ]">{{houseHold.id}}</a></td>
                <td>{{houseHold.name}}</td>
                <td>
                    <div *ngIf="houseHold.accountsDocument">
                        <a [routerLink]="['../accounts-document', houseHold.accountsDocument?.id, 'view' ]" >{{houseHold.accountsDocument?.id}}</a>
                    </div>
                </td>
                <td>
                    <span *ngFor="let members of houseHold.members; let last = last">
                            {{members.login}}{{last ? '' : ', '}}
                        </span>
                </td>
                <td class="text-right">
                    <div class="btn-group flex-btn-group-container">
                        <button type="submit"
                                [routerLink]="['/house-hold', houseHold.id, 'view' ]"
                                class="btn btn-info btn-sm">
                            <fa-icon [icon]="'eye'"></fa-icon>
                            <span class="d-none d-md-inline" jhiTranslate="entity.action.view">View</span>
                        </button>
                        <button type="submit"
                                [routerLink]="['/house-hold', houseHold.id, 'edit']"
                                class="btn btn-primary btn-sm">
                            <fa-icon [icon]="'pencil-alt'"></fa-icon>
                            <span class="d-none d-md-inline" jhiTranslate="entity.action.edit">Edit</span>
                        </button>
                        <button type="submit"
                                [routerLink]="['/', { outlets: { popup: 'house-hold/'+ houseHold.id + '/delete'} }]"
                                replaceUrl="true"
                                queryParamsHandling="merge"
                                class="btn btn-danger btn-sm">
                            <fa-icon [icon]="'times'"></fa-icon>
                            <span class="d-none d-md-inline" jhiTranslate="entity.action.delete">Delete</span>
                        </button>
                    </div>
                </td>
            </tr>
            </tbody>
        </table>
    </div>
</div>

// ecolar-mobile/src/main/webapp/app/entities/house-hold/house-hold.vue
<template>
    <div>
        <h2 id="page-heading">
            <span v-text="$t('ecolarApp.houseHold.home.title')" id="house-hold-heading">House Holds</span>
            <router-link to="/entity/house-hold/new" tag="button" id="jh-create-entity" class="btn btn-primary float-right jh-create-entity create-house-hold">
                <font-awesome-icon icon="plus"></font-awesome-icon>
                <span  v-text="$t('ecolarApp.houseHold.home.createLabel')">
                    Create new HouseHold
                </span>
            </router-link>
        </h2>
        <!--<jhi-alert></jhi-alert>-->
        <br/>
        <div class="table-responsive" v-if="houseHolds">
            <table class="table table-striped">
                <thead>
                <tr>
                    <th><span v-text="$t('global.field.id')">ID</span></th>
                        <th><span v-text="$t('ecolarApp.houseHold.name')">Name</span></th>
                            <th><span v-text="$t('ecolarApp.houseHold.accountCategories')">Account Categories</span></th>
                            <th><span v-text="$t('ecolarApp.houseHold.members')">Members</span></th>
                    <th></th>
                </tr>
                </thead>
                <tbody>
                <tr v-for="houseHold in houseHolds">
                    <td><router-link :to="{name: 'HouseHoldView', params: {houseHoldId: houseHold.id}}">{{houseHold.id}}</router-link></td>
                            <td>{{houseHold.name}}</td>
                        <td>
                                        <div v-if="houseHold.accountCategories">
                                            <router-link :to="'../entity/account-categories/' + houseHold.accountCategories.id + '/view'" >{{houseHold.accountCategories.id}}</router-link>
                                        </div>
                        </td>
                        <td>
                                    <span v-for="members in houseHold.members">
                                        {{members.login}}{{last ? '' : ', '}}
                                    </span>
                        </td>
                    <td class="text-right">
                        <div class="btn-group flex-btn-group-container">
                            <router-link :to="{name: 'HouseHoldView', params: {houseHoldId: houseHold.id}}" tag="button" class="btn btn-info btn-sm">
                                <font-awesome-icon icon="eye"></font-awesome-icon>
                                <span class="d-none d-md-inline" v-text="$t('entity.action.view')">View</span>
                            </router-link>
                            <router-link :to="{name: 'HouseHoldEdit', params: {houseHoldId: houseHold.id}}"  tag="button" class="btn btn-primary btn-sm">
                                <font-awesome-icon icon="pencil-alt"></font-awesome-icon>
                                <span class="d-none d-md-inline" v-text="$t('entity.action.edit')">Edit</span>
                            </router-link>
                            <b-btn v-on:click="prepareRemove(houseHold)"
                                   class="btn btn-danger btn-sm"
                                   v-b-modal.removeEntity>
                                <font-awesome-icon icon="times"></font-awesome-icon>
                                <span class="d-none d-md-inline" v-text="$t('entity.action.delete')">Delete</span>
                            </b-btn>
                        </div>
                    </td>
                </tr>
                </tbody>
            </table>
        </div>
        <b-modal ref="removeEntity" id="removeEntity" >
            <span slot="modal-title"><span id="ecolarApp.houseHold.delete.question" v-text="$t('entity.delete.title')">Confirm delete operation</span></span>
            <div class="modal-body">
                <p id="eco-delete-houseHold-heading" v-bind:title="$t('ecolarApp.houseHold.delete.question')">Are you sure you want to delete this House Hold?</p>
            </div>
            <div slot="modal-footer">
                <button type="button" class="btn btn-secondary" v-text="$t('entity.action.cancel')" v-on:click="closeDialog()">Cancel</button>
                <button type="button" class="btn btn-primary" id="eco-confirm-delete-houseHold" v-text="$t('entity.action.delete')" v-on:click="removeHouseHold()">Delete</button>
            </div>
        </b-modal>
    </div>
</template>

<script lang="ts" src="./house-hold.component.ts">
</script>
