// ecolar-mobile/src/main/webapp/app/entities/user-preferences/user-preferences-update.vue
<template>
    <div class="row justify-content-center">
        <div class="col-8">
            <form name="editForm" role="form" novalidate v-on:submit.prevent="save()" >
                <h2 id="ecolarApp.userPreferences.home.createOrEditLabel" v-text="$t('ecolarApp.userPreferences.home.createOrEditLabel')">Create or edit a UserPreferences</h2>
                <div>
                    <!--<jhi-alert-error></jhi-alert-error>-->
                    <div class="form-group" v-if="userPreferences.id">
                        <label for="id" v-text="$t('global.field.id')">ID</label>
                        <input type="text" class="form-control" id="id" name="id"
                               v-model="userPreferences.id" readonly />
                    </div>


                        <div class="form-group">
                            <label class="form-control-label" v-bind:value="$t('ecolarApp.userPreferences.user')" for="user-preferences-user">User</label>
                                <select class="form-control" id="user-preferences-user" name="user" v-model="userPreferences.user" >
                                    <option value="null"></option>
                                    <option v-bind:value="userPreferences.user && userOption.id === userPreferences.user.id ? userPreferences.user : userOption" v-for="userOption in users">{{userOption.login}}</option>
                                </select>
                        </div>

                </div>
                <div>
                    <button type="button" id="cancel-save" class="btn btn-secondary" v-on:click="previousState()">
                        <font-awesome-icon icon="ban"></font-awesome-icon>&nbsp;<span v-text="$t('entity.action.cancel')">Cancel</span>
                    </button>
                    <button type="submit" id="save-entity" :disabled="$v.userPreferences.$invalid || isSaving" class="btn btn-primary">
                        <font-awesome-icon icon="save"></font-awesome-icon>&nbsp;<span v-text="$t('entity.action.save')">Save</span>
                    </button>
                </div>
            </form>
        </div>
    </div>
</template>
<script lang="ts" src="./user-preferences-update.component.ts">
</script>

// ecolarAdmin/src/main/webapp/app/entities/user-preferences/user-preferences-update.component.ts
import { Component, OnInit } from '@angular/core';
import { ActivatedRoute } from '@angular/router';
import { HttpResponse, HttpErrorResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { JhiAlertService } from 'ng-jhipster';

import { IUserPreferences } from 'app/shared/model/user-preferences.model';
import { UserPreferencesService } from './user-preferences.service';
import { IUser, UserService } from 'app/core';

@Component({
    selector: 'eco-user-preferences-update',
    templateUrl: './user-preferences-update.component.html'
})
export class UserPreferencesUpdateComponent implements OnInit {
    userPreferences: IUserPreferences;
    isSaving: boolean;

    users: IUser[];

    constructor(
        private jhiAlertService: JhiAlertService,
        private userPreferencesService: UserPreferencesService,
        private userService: UserService,
        private activatedRoute: ActivatedRoute
    ) {}

    ngOnInit() {
        this.isSaving = false;
        this.activatedRoute.data.subscribe(({ userPreferences }) => {
            this.userPreferences = userPreferences;
        });
        this.userService.query().subscribe(
            (res: HttpResponse<IUser[]>) => {
                this.users = res.body;
            },
            (res: HttpErrorResponse) => this.onError(res.message)
        );
    }

    previousState() {
        window.history.back();
    }

    save() {
        this.isSaving = true;
        if (this.userPreferences.id !== undefined) {
            this.subscribeToSaveResponse(this.userPreferencesService.update(this.userPreferences));
        } else {
            this.subscribeToSaveResponse(this.userPreferencesService.create(this.userPreferences));
        }
    }

    private subscribeToSaveResponse(result: Observable<HttpResponse<IUserPreferences>>) {
        result.subscribe((res: HttpResponse<IUserPreferences>) => this.onSaveSuccess(), (res: HttpErrorResponse) => this.onSaveError());
    }

    private onSaveSuccess() {
        this.isSaving = false;
        this.previousState();
    }

    private onSaveError() {
        this.isSaving = false;
    }

    private onError(errorMessage: string) {
        this.jhiAlertService.error(errorMessage, null, null);
    }

    trackUserById(index: number, item: IUser) {
        return item.id;
    }
}

<div class="row justify-content-center">
    <div class="col-8">
        <form name="editForm" role="form" novalidate (ngSubmit)="save()" #editForm="ngForm">
            <h2 id="eco-user-preferences-heading" jhiTranslate="ecolarAdminApp.userPreferences.home.createOrEditLabel">Create or edit a User Preferences</h2>
            <div>
                <eco-alert-error></eco-alert-error>
                <div class="form-group" [hidden]="!userPreferences.id">
                    <label for="id" jhiTranslate="global.field.id">ID</label>
                    <input type="text" class="form-control" id="id" name="id"
                        [(ngModel)]="userPreferences.id" readonly />
                </div>

                <div class="form-group">
                    <label class="form-control-label" jhiTranslate="ecolarAdminApp.userPreferences.user" for="field_user">User</label>
                    <select class="form-control" id="field_user" name="user" [(ngModel)]="userPreferences.user" >
                        <option [ngValue]="null"></option>
                        <option [ngValue]="userOption.id === userPreferences.user?.id ? userPreferences.user : userOption" *ngFor="let userOption of users; trackBy: trackUserById">{{userOption.login}}</option>
                    </select>
                </div>
            </div>
            <div>
                <button type="button" id="cancel-save" class="btn btn-secondary"  (click)="previousState()">
                    <fa-icon [icon]="'ban'"></fa-icon>&nbsp;<span jhiTranslate="entity.action.cancel">Cancel</span>
                </button>
                <button type="submit" id="save-entity" [disabled]="editForm.form.invalid || isSaving" class="btn btn-primary">
                    <fa-icon [icon]="'save'"></fa-icon>&nbsp;<span jhiTranslate="entity.action.save">Save</span>
                </button>
            </div>
        </form>
    </div>
</div>
