// ecolarMobile/src/main/webapp/app/entities/user-preferences/user-preferences-detail.tsx
import React from 'react';
import { connect } from 'react-redux';
import { Link, RouteComponentProps } from 'react-router-dom';
import { Button, Row, Col } from 'reactstrap';
// tslint:disable-next-line:no-unused-variable
import { Translate, ICrudGetAction } from 'react-jhipster';
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome';

import { IRootState } from 'app/shared/reducers';
import { getEntity } from './user-preferences.reducer';
import { IUserPreferences } from 'app/shared/model/user-preferences.model';
// tslint:disable-next-line:no-unused-variable
import { APP_DATE_FORMAT, APP_LOCAL_DATE_FORMAT } from 'app/config/constants';

export interface IUserPreferencesDetailProps extends StateProps, DispatchProps, RouteComponentProps<{ id: string }> {}

export class UserPreferencesDetail extends React.Component<IUserPreferencesDetailProps> {
  componentDidMount() {
    this.props.getEntity(this.props.match.params.id);
  }

  render() {
    const { userPreferencesEntity } = this.props;
    return (
      <Row>
        <Col md="8">
          <h2>
            <Translate contentKey="ecolarMobileApp.userPreferences.detail.title">UserPreferences</Translate> [<b>
              {userPreferencesEntity.id}
            </b>]
          </h2>
          <dl className="jh-entity-details">
            <dt>
              <Translate contentKey="ecolarMobileApp.userPreferences.user">User</Translate>
            </dt>
            <dd>{userPreferencesEntity.user ? userPreferencesEntity.user.login : ''}</dd>
          </dl>
          <Button tag={Link} to="/entity/user-preferences" replace color="info">
            <FontAwesomeIcon icon="arrow-left" />{' '}
            <span className="d-none d-md-inline">
              <Translate contentKey="entity.action.back">Back</Translate>
            </span>
          </Button>&nbsp;
          <Button tag={Link} to={`/entity/user-preferences/${userPreferencesEntity.id}/edit`} replace color="primary">
            <FontAwesomeIcon icon="pencil-alt" />{' '}
            <span className="d-none d-md-inline">
              <Translate contentKey="entity.action.edit">Edit</Translate>
            </span>
          </Button>
        </Col>
      </Row>
    );
  }
}

const mapStateToProps = ({ userPreferences }: IRootState) => ({
  userPreferencesEntity: userPreferences.entity
});

const mapDispatchToProps = { getEntity };

type StateProps = ReturnType<typeof mapStateToProps>;
type DispatchProps = typeof mapDispatchToProps;

export default connect(
  mapStateToProps,
  mapDispatchToProps
)(UserPreferencesDetail);

// ecolarAdmin/src/main/webapp/app/entities/user-preferences/user-preferences-detail.component.ts
import { Component, OnInit } from '@angular/core';
import { ActivatedRoute } from '@angular/router';

import { IUserPreferences } from 'app/shared/model/user-preferences.model';

@Component({
    selector: 'eco-user-preferences-detail',
    templateUrl: './user-preferences-detail.component.html'
})
export class UserPreferencesDetailComponent implements OnInit {
    userPreferences: IUserPreferences;

    constructor(private activatedRoute: ActivatedRoute) {}

    ngOnInit() {
        this.activatedRoute.data.subscribe(({ userPreferences }) => {
            this.userPreferences = userPreferences;
        });
    }

    previousState() {
        window.history.back();
    }
}

<div class="row justify-content-center">
    <div class="col-8">
        <div *ngIf="userPreferences">
            <h2><span jhiTranslate="ecolarAdminApp.userPreferences.detail.title">User Preferences</span> {{userPreferences.id}}</h2>
            <hr>
            <eco-alert-error></eco-alert-error>
            <dl class="row-md jh-entity-details">
                <dt><span jhiTranslate="ecolarAdminApp.userPreferences.user">User</span></dt>
                <dd>
                    {{userPreferences.user?.login}}
                </dd>
            </dl>

            <button type="submit"
                    (click)="previousState()"
                    class="btn btn-info">
                <fa-icon [icon]="'arrow-left'"></fa-icon>&nbsp;<span jhiTranslate="entity.action.back"> Back</span>
            </button>

            <button type="button"
                    [routerLink]="['/user-preferences', userPreferences.id, 'edit']"
                    class="btn btn-primary">
                <fa-icon [icon]="'pencil-alt'"></fa-icon>&nbsp;<span jhiTranslate="entity.action.edit"> Edit</span>
            </button>
        </div>
    </div>
</div>
