// ecolar-mobile/src/main/webapp/app/entities/user-preferences/user-preferences.vue
<template>
    <div>
        <h2 id="page-heading">
            <span v-text="$t('ecolarApp.userPreferences.home.title')" id="user-preferences-heading">User Preferences</span>
            <router-link to="/entity/user-preferences/new" tag="button" id="jh-create-entity" class="btn btn-primary float-right jh-create-entity create-user-preferences">
                <font-awesome-icon icon="plus"></font-awesome-icon>
                <span  v-text="$t('ecolarApp.userPreferences.home.createLabel')">
                    Create new UserPreferences
                </span>
            </router-link>
        </h2>
        <!--<jhi-alert></jhi-alert>-->
        <br/>
        <div class="table-responsive" v-if="userPreferences">
            <table class="table table-striped">
                <thead>
                <tr>
                    <th><span v-text="$t('global.field.id')">ID</span></th>
                            <th><span v-text="$t('ecolarApp.userPreferences.user')">User</span></th>
                    <th></th>
                </tr>
                </thead>
                <tbody>
                <tr v-for="userPreferences in userPreferences">
                    <td><router-link :to="{name: 'UserPreferencesView', params: {userPreferencesId: userPreferences.id}}">{{userPreferences.id}}</router-link></td>
                        <td>
                                        {{userPreferences.user.login}}
                        </td>
                    <td class="text-right">
                        <div class="btn-group flex-btn-group-container">
                            <router-link :to="{name: 'UserPreferencesView', params: {userPreferencesId: userPreferences.id}}" tag="button" class="btn btn-info btn-sm">
                                <font-awesome-icon icon="eye"></font-awesome-icon>
                                <span class="d-none d-md-inline" v-text="$t('entity.action.view')">View</span>
                            </router-link>
                            <router-link :to="{name: 'UserPreferencesEdit', params: {userPreferencesId: userPreferences.id}}"  tag="button" class="btn btn-primary btn-sm">
                                <font-awesome-icon icon="pencil-alt"></font-awesome-icon>
                                <span class="d-none d-md-inline" v-text="$t('entity.action.edit')">Edit</span>
                            </router-link>
                            <b-btn v-on:click="prepareRemove(userPreferences)"
                                   class="btn btn-danger btn-sm"
                                   v-b-modal.removeEntity>
                                <font-awesome-icon icon="times"></font-awesome-icon>
                                <span class="d-none d-md-inline" v-text="$t('entity.action.delete')">Delete</span>
                            </b-btn>
                        </div>
                    </td>
                </tr>
                </tbody>
            </table>
        </div>
        <b-modal ref="removeEntity" id="removeEntity" >
            <span slot="modal-title"><span id="ecolarApp.userPreferences.delete.question" v-text="$t('entity.delete.title')">Confirm delete operation</span></span>
            <div class="modal-body">
                <p id="eco-delete-userPreferences-heading" v-bind:title="$t('ecolarApp.userPreferences.delete.question')">Are you sure you want to delete this User Preferences?</p>
            </div>
            <div slot="modal-footer">
                <button type="button" class="btn btn-secondary" v-text="$t('entity.action.cancel')" v-on:click="closeDialog()">Cancel</button>
                <button type="button" class="btn btn-primary" id="eco-confirm-delete-userPreferences" v-text="$t('entity.action.delete')" v-on:click="removeUserPreferences()">Delete</button>
            </div>
        </b-modal>
    </div>
</template>

<script lang="ts" src="./user-preferences.component.ts">
</script>

// ecolarAdmin/src/main/webapp/app/house-hold-administration/user-preferences/user-preferences.component.ts
import { Component, OnInit, OnDestroy } from '@angular/core';
import { HttpErrorResponse, HttpResponse } from '@angular/common/http';
import { Subscription } from 'rxjs';
import { JhiEventManager, JhiAlertService } from 'ng-jhipster';

import { IUserPreferences } from 'app/shared/model/user-preferences.model';
import { Principal } from 'app/core';
import { UserPreferencesService } from './user-preferences.service';

@Component({
    selector: 'eco-user-preferences',
    templateUrl: './user-preferences.component.html'
})
export class UserPreferencesComponent implements OnInit, OnDestroy {
    userPreferences: IUserPreferences[];
    currentAccount: any;
    eventSubscriber: Subscription;

    constructor(
        private userPreferencesService: UserPreferencesService,
        private jhiAlertService: JhiAlertService,
        private eventManager: JhiEventManager,
        private principal: Principal
    ) {}

    loadAll() {
        this.userPreferencesService.query().subscribe(
            (res: HttpResponse<IUserPreferences[]>) => {
                this.userPreferences = res.body;
            },
            (res: HttpErrorResponse) => this.onError(res.message)
        );
    }

    ngOnInit() {
        this.loadAll();
        this.principal.identity().then(account => {
            this.currentAccount = account;
        });
        this.registerChangeInUserPreferences();
    }

    ngOnDestroy() {
        this.eventManager.destroy(this.eventSubscriber);
    }

    trackId(index: number, item: IUserPreferences) {
        return item.id;
    }

    registerChangeInUserPreferences() {
        this.eventSubscriber = this.eventManager.subscribe('userPreferencesListModification', response => this.loadAll());
    }

    private onError(errorMessage: string) {
        this.jhiAlertService.error(errorMessage, null, null);
    }
}

<div>
    <h2 id="page-heading">
        <span jhiTranslate="ecolarAdminApp.userPreferences.home.title">User Preferences</span>
        <button id="jh-create-entity" class="btn btn-primary float-right jh-create-entity create-user-preferences" [routerLink]="['/user-preferences/new']">
            <fa-icon [icon]="'plus'"></fa-icon>
            <span  jhiTranslate="ecolarAdminApp.userPreferences.home.createLabel">
            Create new User Preferences
            </span>
        </button>
    </h2>
    <eco-alert></eco-alert>
    <br/>
    <div class="table-responsive" *ngIf="userPreferences">
        <table class="table table-striped">
            <thead>
            <tr>
            <th><span jhiTranslate="global.field.id">ID</span></th>
            <th><span jhiTranslate="ecolarAdminApp.userPreferences.user">User</span></th>
            <th></th>
            </tr>
            </thead>
            <tbody>
            <tr *ngFor="let userPreferences of userPreferences ;trackBy: trackId">
                <td><a [routerLink]="['/user-preferences', userPreferences.id, 'view' ]">{{userPreferences.id}}</a></td>
                <td>
                    {{userPreferences.user?.login}}
                </td>
                <td class="text-right">
                    <div class="btn-group flex-btn-group-container">
                        <button type="submit"
                                [routerLink]="['/user-preferences', userPreferences.id, 'view' ]"
                                class="btn btn-info btn-sm">
                            <fa-icon [icon]="'eye'"></fa-icon>
                            <span class="d-none d-md-inline" jhiTranslate="entity.action.view">View</span>
                        </button>
                        <button type="submit"
                                [routerLink]="['/user-preferences', userPreferences.id, 'edit']"
                                class="btn btn-primary btn-sm">
                            <fa-icon [icon]="'pencil-alt'"></fa-icon>
                            <span class="d-none d-md-inline" jhiTranslate="entity.action.edit">Edit</span>
                        </button>
                        <button type="submit"
                                [routerLink]="['/', { outlets: { popup: 'user-preferences/'+ userPreferences.id + '/delete'} }]"
                                replaceUrl="true"
                                queryParamsHandling="merge"
                                class="btn btn-danger btn-sm">
                            <fa-icon [icon]="'times'"></fa-icon>
                            <span class="d-none d-md-inline" jhiTranslate="entity.action.delete">Delete</span>
                        </button>
                    </div>
                </td>
            </tr>
            </tbody>
        </table>
    </div>
</div>
