// ecolar-mobile/src/main/webapp/app/entities/movement-line/movement-line.vue
<template>
    <div>
        <h2 id="page-heading">
            <span v-text="$t('ecolarApp.movementLine.home.title')" id="movement-line-heading">Movement Lines</span>
            <router-link to="/entity/movement-line/new" tag="button" id="jh-create-entity" class="btn btn-primary float-right jh-create-entity create-movement-line">
                <font-awesome-icon icon="plus"></font-awesome-icon>
                <span  v-text="$t('ecolarApp.movementLine.home.createLabel')">
                    Create new MovementLine
                </span>
            </router-link>
        </h2>
        <!--<jhi-alert></jhi-alert>-->
        <br/>
        <div class="table-responsive" v-if="movementLines">
            <table class="table table-striped">
                <thead>
                <tr>
                    <th><span v-text="$t('global.field.id')">ID</span></th>
                        <th><span v-text="$t('ecolarApp.movementLine.amount')">Amount</span></th>
                        <th><span v-text="$t('ecolarApp.movementLine.eventType')">Event Type</span></th>
                            <th><span v-text="$t('ecolarApp.movementLine.account')">Account</span></th>
                    <th></th>
                </tr>
                </thead>
                <tbody>
                <tr v-for="movementLine in movementLines">
                    <td><router-link :to="{name: 'MovementLineView', params: {movementLineId: movementLine.id}}">{{movementLine.id}}</router-link></td>
                            <td>{{movementLine.amount}}</td>
                            <td v-text="$t('ecolarApp.LineType.' + movementLine.eventType)">{{movementLine.eventType}}</td>
                        <td>
                                        <div v-if="movementLine.account">
                                            <router-link :to="'../entity/e-account/' + movementLine.account.id + '/view'" >{{movementLine.account.accountName}}</router-link>
                                        </div>
                        </td>
                    <td class="text-right">
                        <div class="btn-group flex-btn-group-container">
                            <router-link :to="{name: 'MovementLineView', params: {movementLineId: movementLine.id}}" tag="button" class="btn btn-info btn-sm">
                                <font-awesome-icon icon="eye"></font-awesome-icon>
                                <span class="d-none d-md-inline" v-text="$t('entity.action.view')">View</span>
                            </router-link>
                            <router-link :to="{name: 'MovementLineEdit', params: {movementLineId: movementLine.id}}"  tag="button" class="btn btn-primary btn-sm">
                                <font-awesome-icon icon="pencil-alt"></font-awesome-icon>
                                <span class="d-none d-md-inline" v-text="$t('entity.action.edit')">Edit</span>
                            </router-link>
                            <b-btn v-on:click="prepareRemove(movementLine)"
                                   class="btn btn-danger btn-sm"
                                   v-b-modal.removeEntity>
                                <font-awesome-icon icon="times"></font-awesome-icon>
                                <span class="d-none d-md-inline" v-text="$t('entity.action.delete')">Delete</span>
                            </b-btn>
                        </div>
                    </td>
                </tr>
                </tbody>
            </table>
        </div>
        <b-modal ref="removeEntity" id="removeEntity" >
            <span slot="modal-title"><span id="ecolarApp.movementLine.delete.question" v-text="$t('entity.delete.title')">Confirm delete operation</span></span>
            <div class="modal-body">
                <p id="eco-delete-movementLine-heading" v-bind:title="$t('ecolarApp.movementLine.delete.question')">Are you sure you want to delete this Movement Line?</p>
            </div>
            <div slot="modal-footer">
                <button type="button" class="btn btn-secondary" v-text="$t('entity.action.cancel')" v-on:click="closeDialog()">Cancel</button>
                <button type="button" class="btn btn-primary" id="eco-confirm-delete-movementLine" v-text="$t('entity.action.delete')" v-on:click="removeMovementLine()">Delete</button>
            </div>
        </b-modal>
    </div>
</template>

<script lang="ts" src="./movement-line.component.ts">
</script>

// ecolarMobile/src/main/webapp/app/entities/movement-line/movement-line.tsx
import React from 'react';
import { connect } from 'react-redux';
import { Link, RouteComponentProps } from 'react-router-dom';
import { Button, Col, Row, Table } from 'reactstrap';
// tslint:disable-next-line:no-unused-variable
import { Translate, ICrudGetAllAction } from 'react-jhipster';
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome';

import { IRootState } from 'app/shared/reducers';
import { getEntities } from './movement-line.reducer';
import { IMovementLine } from 'app/shared/model/movement-line.model';
// tslint:disable-next-line:no-unused-variable
import { APP_DATE_FORMAT, APP_LOCAL_DATE_FORMAT } from 'app/config/constants';

export interface IMovementLineProps extends StateProps, DispatchProps, RouteComponentProps<{ url: string }> {}

export class MovementLine extends React.Component<IMovementLineProps> {
  componentDidMount() {
    this.props.getEntities();
  }

  render() {
    const { movementLineList, match } = this.props;
    return (
      <div>
        <h2 id="movement-line-heading">
          <Translate contentKey="ecolarMobileApp.movementLine.home.title">Movement Lines</Translate>
          <Link to={`${match.url}/new`} className="btn btn-primary float-right jh-create-entity" id="jh-create-entity">
            <FontAwesomeIcon icon="plus" />&nbsp;
            <Translate contentKey="ecolarMobileApp.movementLine.home.createLabel">Create new Movement Line</Translate>
          </Link>
        </h2>
        <div className="table-responsive">
          <Table responsive>
            <thead>
              <tr>
                <th>
                  <Translate contentKey="global.field.id">ID</Translate>
                </th>
                <th>
                  <Translate contentKey="ecolarMobileApp.movementLine.amount">Amount</Translate>
                </th>
                <th>
                  <Translate contentKey="ecolarMobileApp.movementLine.eventType">Event Type</Translate>
                </th>
                <th>
                  <Translate contentKey="ecolarMobileApp.movementLine.account">Account</Translate>
                </th>
                <th />
              </tr>
            </thead>
            <tbody>
              {movementLineList.map((movementLine, i) => (
                <tr key={`entity-${i}`}>
                  <td>
                    <Button tag={Link} to={`${match.url}/${movementLine.id}`} color="link" size="sm">
                      {movementLine.id}
                    </Button>
                  </td>
                  <td>{movementLine.amount}</td>
                  <td>
                    <Translate contentKey={`ecolarMobileApp.LineType.${movementLine.eventType}`} />
                  </td>
                  <td>
                    {movementLine.account ? (
                      <Link to={`e-account/${movementLine.account.id}`}>{movementLine.account.accountName}</Link>
                    ) : (
                      ''
                    )}
                  </td>
                  <td className="text-right">
                    <div className="btn-group flex-btn-group-container">
                      <Button tag={Link} to={`${match.url}/${movementLine.id}`} color="info" size="sm">
                        <FontAwesomeIcon icon="eye" />{' '}
                        <span className="d-none d-md-inline">
                          <Translate contentKey="entity.action.view">View</Translate>
                        </span>
                      </Button>
                      <Button tag={Link} to={`${match.url}/${movementLine.id}/edit`} color="primary" size="sm">
                        <FontAwesomeIcon icon="pencil-alt" />{' '}
                        <span className="d-none d-md-inline">
                          <Translate contentKey="entity.action.edit">Edit</Translate>
                        </span>
                      </Button>
                      <Button tag={Link} to={`${match.url}/${movementLine.id}/delete`} color="danger" size="sm">
                        <FontAwesomeIcon icon="trash" />{' '}
                        <span className="d-none d-md-inline">
                          <Translate contentKey="entity.action.delete">Delete</Translate>
                        </span>
                      </Button>
                    </div>
                  </td>
                </tr>
              ))}
            </tbody>
          </Table>
        </div>
      </div>
    );
  }
}

const mapStateToProps = ({ movementLine }: IRootState) => ({
  movementLineList: movementLine.entities
});

const mapDispatchToProps = {
  getEntities
};

type StateProps = ReturnType<typeof mapStateToProps>;
type DispatchProps = typeof mapDispatchToProps;

export default connect(
  mapStateToProps,
  mapDispatchToProps
)(MovementLine);
