// ecolarAdmin/src/main/webapp/app/entities/movement-line/movement-line-detail.component.ts
import { Component, OnInit } from '@angular/core';
import { ActivatedRoute } from '@angular/router';

import { IMovementLine } from 'app/shared/model/movement-line.model';

@Component({
    selector: 'eco-movement-line-detail',
    templateUrl: './movement-line-detail.component.html'
})
export class MovementLineDetailComponent implements OnInit {
    movementLine: IMovementLine;

    constructor(private activatedRoute: ActivatedRoute) {}

    ngOnInit() {
        this.activatedRoute.data.subscribe(({ movementLine }) => {
            this.movementLine = movementLine;
        });
    }

    previousState() {
        window.history.back();
    }
}

<div class="row justify-content-center">
    <div class="col-8">
        <div *ngIf="movementLine">
            <h2><span jhiTranslate="ecolarAdminApp.movementLine.detail.title">Movement Line</span> {{movementLine.id}}</h2>
            <hr>
            <eco-alert-error></eco-alert-error>
            <dl class="row-md jh-entity-details">
                <dt><span jhiTranslate="ecolarAdminApp.movementLine.amount">Amount</span></dt>
                <dd>
                    <span>{{movementLine.amount}}</span>
                </dd>
                <dt><span jhiTranslate="ecolarAdminApp.movementLine.eventType">Event Type</span></dt>
                <dd>
                    <span jhiTranslate="{{'ecolarAdminApp.LineType.' + movementLine.eventType}}">{{movementLine.eventType}}</span>
                </dd>
                <dt><span jhiTranslate="ecolarAdminApp.movementLine.account">Account</span></dt>
                <dd>
                    <div *ngIf="movementLine.account">
                        <a [routerLink]="['/e-account', movementLine.account?.id, 'view']">{{movementLine.account?.accountName}}</a>
                    </div>
                </dd>
            </dl>

            <button type="submit"
                    (click)="previousState()"
                    class="btn btn-info">
                <fa-icon [icon]="'arrow-left'"></fa-icon>&nbsp;<span jhiTranslate="entity.action.back"> Back</span>
            </button>

            <button type="button"
                    [routerLink]="['/movement-line', movementLine.id, 'edit']"
                    class="btn btn-primary">
                <fa-icon [icon]="'pencil-alt'"></fa-icon>&nbsp;<span jhiTranslate="entity.action.edit"> Edit</span>
            </button>
        </div>
    </div>
</div>

// ecolarMobile/src/main/webapp/app/entities/movement-line/movement-line-detail.tsx
import React from 'react';
import { connect } from 'react-redux';
import { Link, RouteComponentProps } from 'react-router-dom';
import { Button, Row, Col } from 'reactstrap';
// tslint:disable-next-line:no-unused-variable
import { Translate, ICrudGetAction } from 'react-jhipster';
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome';

import { IRootState } from 'app/shared/reducers';
import { getEntity } from './movement-line.reducer';
import { IMovementLine } from 'app/shared/model/movement-line.model';
// tslint:disable-next-line:no-unused-variable
import { APP_DATE_FORMAT, APP_LOCAL_DATE_FORMAT } from 'app/config/constants';

export interface IMovementLineDetailProps extends StateProps, DispatchProps, RouteComponentProps<{ id: string }> {}

export class MovementLineDetail extends React.Component<IMovementLineDetailProps> {
  componentDidMount() {
    this.props.getEntity(this.props.match.params.id);
  }

  render() {
    const { movementLineEntity } = this.props;
    return (
      <Row>
        <Col md="8">
          <h2>
            <Translate contentKey="ecolarMobileApp.movementLine.detail.title">MovementLine</Translate> [<b>{movementLineEntity.id}</b>]
          </h2>
          <dl className="jh-entity-details">
            <dt>
              <span id="amount">
                <Translate contentKey="ecolarMobileApp.movementLine.amount">Amount</Translate>
              </span>
            </dt>
            <dd>{movementLineEntity.amount}</dd>
            <dt>
              <span id="eventType">
                <Translate contentKey="ecolarMobileApp.movementLine.eventType">Event Type</Translate>
              </span>
            </dt>
            <dd>{movementLineEntity.eventType}</dd>
            <dt>
              <Translate contentKey="ecolarMobileApp.movementLine.account">Account</Translate>
            </dt>
            <dd>{movementLineEntity.account ? movementLineEntity.account.accountName : ''}</dd>
          </dl>
          <Button tag={Link} to="/entity/movement-line" replace color="info">
            <FontAwesomeIcon icon="arrow-left" />{' '}
            <span className="d-none d-md-inline">
              <Translate contentKey="entity.action.back">Back</Translate>
            </span>
          </Button>&nbsp;
          <Button tag={Link} to={`/entity/movement-line/${movementLineEntity.id}/edit`} replace color="primary">
            <FontAwesomeIcon icon="pencil-alt" />{' '}
            <span className="d-none d-md-inline">
              <Translate contentKey="entity.action.edit">Edit</Translate>
            </span>
          </Button>
        </Col>
      </Row>
    );
  }
}

const mapStateToProps = ({ movementLine }: IRootState) => ({
  movementLineEntity: movementLine.entity
});

const mapDispatchToProps = { getEntity };

type StateProps = ReturnType<typeof mapStateToProps>;
type DispatchProps = typeof mapDispatchToProps;

export default connect(
  mapStateToProps,
  mapDispatchToProps
)(MovementLineDetail);
