// ecolarMobile/src/main/webapp/app/entities/movement/movement.tsx
import React from 'react';
import { connect } from 'react-redux';
import { Link, RouteComponentProps } from 'react-router-dom';
import { Button, Col, Row, Table } from 'reactstrap';
// tslint:disable-next-line:no-unused-variable
import { Translate, ICrudGetAllAction, TextFormat } from 'react-jhipster';
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome';

import { IRootState } from 'app/shared/reducers';
import { getEntities } from './movement.reducer';
import { IMovement } from 'app/shared/model/movement.model';
// tslint:disable-next-line:no-unused-variable
import { APP_DATE_FORMAT, APP_LOCAL_DATE_FORMAT } from 'app/config/constants';

export interface IMovementProps extends StateProps, DispatchProps, RouteComponentProps<{ url: string }> {}

export class Movement extends React.Component<IMovementProps> {
  componentDidMount() {
    this.props.getEntities();
  }

  render() {
    const { movementList, match } = this.props;
    return (
      <div>
        <h2 id="movement-heading">
          <Translate contentKey="ecolarMobileApp.movement.home.title">Movements</Translate>
          <Link to={`${match.url}/new`} className="btn btn-primary float-right jh-create-entity" id="jh-create-entity">
            <FontAwesomeIcon icon="plus" />&nbsp;
            <Translate contentKey="ecolarMobileApp.movement.home.createLabel">Create new Movement</Translate>
          </Link>
        </h2>
        <div className="table-responsive">
          <Table responsive>
            <thead>
              <tr>
                <th>
                  <Translate contentKey="global.field.id">ID</Translate>
                </th>
                <th>
                  <Translate contentKey="ecolarMobileApp.movement.eventTime">Event Time</Translate>
                </th>
                <th>
                  <Translate contentKey="ecolarMobileApp.movement.registrationTime">Registration Time</Translate>
                </th>
                <th>
                  <Translate contentKey="ecolarMobileApp.movement.amount">Amount</Translate>
                </th>
                <th>
                  <Translate contentKey="ecolarMobileApp.movement.location">Location</Translate>
                </th>
                <th>
                  <Translate contentKey="ecolarMobileApp.movement.eventLines">Event Lines</Translate>
                </th>
                <th />
              </tr>
            </thead>
            <tbody>
              {movementList.map((movement, i) => (
                <tr key={`entity-${i}`}>
                  <td>
                    <Button tag={Link} to={`${match.url}/${movement.id}`} color="link" size="sm">
                      {movement.id}
                    </Button>
                  </td>
                  <td>
                    <TextFormat type="date" value={movement.eventTime} format={APP_DATE_FORMAT} />
                  </td>
                  <td>
                    <TextFormat type="date" value={movement.registrationTime} format={APP_DATE_FORMAT} />
                  </td>
                  <td>{movement.amount}</td>
                  <td>{movement.location}</td>
                  <td>
                    {movement.eventLines
                      ? movement.eventLines.map((val, j) => (
                          <span key={j}>
                            <Link to={`movement-line/${val.id}`}>{val.id}</Link>
                            {j === movement.eventLines.length - 1 ? '' : ', '}
                          </span>
                        ))
                      : null}
                  </td>
                  <td className="text-right">
                    <div className="btn-group flex-btn-group-container">
                      <Button tag={Link} to={`${match.url}/${movement.id}`} color="info" size="sm">
                        <FontAwesomeIcon icon="eye" />{' '}
                        <span className="d-none d-md-inline">
                          <Translate contentKey="entity.action.view">View</Translate>
                        </span>
                      </Button>
                      <Button tag={Link} to={`${match.url}/${movement.id}/edit`} color="primary" size="sm">
                        <FontAwesomeIcon icon="pencil-alt" />{' '}
                        <span className="d-none d-md-inline">
                          <Translate contentKey="entity.action.edit">Edit</Translate>
                        </span>
                      </Button>
                      <Button tag={Link} to={`${match.url}/${movement.id}/delete`} color="danger" size="sm">
                        <FontAwesomeIcon icon="trash" />{' '}
                        <span className="d-none d-md-inline">
                          <Translate contentKey="entity.action.delete">Delete</Translate>
                        </span>
                      </Button>
                    </div>
                  </td>
                </tr>
              ))}
            </tbody>
          </Table>
        </div>
      </div>
    );
  }
}

const mapStateToProps = ({ movement }: IRootState) => ({
  movementList: movement.entities
});

const mapDispatchToProps = {
  getEntities
};

type StateProps = ReturnType<typeof mapStateToProps>;
type DispatchProps = typeof mapDispatchToProps;

export default connect(
  mapStateToProps,
  mapDispatchToProps
)(Movement);

// ecolar-mobile/src/main/webapp/app/entities/movement/movement.vue
<template>
    <div>
        <h2 id="page-heading">
            <span v-text="$t('ecolarApp.movement.home.title')" id="movement-heading">Movements</span>
            <router-link to="/entity/movement/new" tag="button" id="jh-create-entity" class="btn btn-primary float-right jh-create-entity create-movement">
                <font-awesome-icon icon="plus"></font-awesome-icon>
                <span  v-text="$t('ecolarApp.movement.home.createLabel')">
                    Create new Movement
                </span>
            </router-link>
        </h2>
        <!--<jhi-alert></jhi-alert>-->
        <br/>
        <div class="table-responsive" v-if="movements">
            <table class="table table-striped">
                <thead>
                <tr>
                    <th><span v-text="$t('global.field.id')">ID</span></th>
                        <th><span v-text="$t('ecolarApp.movement.eventTime')">Event Time</span></th>
                        <th><span v-text="$t('ecolarApp.movement.registrationTime')">Registration Time</span></th>
                        <th><span v-text="$t('ecolarApp.movement.amount')">Amount</span></th>
                        <th><span v-text="$t('ecolarApp.movement.location')">Location</span></th>
                            <th><span v-text="$t('ecolarApp.movement.eventLines')">Event Lines</span></th>
                    <th></th>
                </tr>
                </thead>
                <tbody>
                <tr v-for="movement in movements">
                    <td><router-link :to="{name: 'MovementView', params: {movementId: movement.id}}">{{movement.id}}</router-link></td>
                            <td>{{movement.eventTime | formatDate}}</td>
                            <td>{{movement.registrationTime | formatDate}}</td>
                            <td>{{movement.amount}}</td>
                            <td>{{movement.location}}</td>
                        <td>
                                    <span v-for="eventLines in movement.eventLines">
                                        <router-link class="form-control-static" :to="'../movement-line/' + eventLines.id}} + '/View'">{{eventLines.id}}</router-link>{{last ? '' : ', '}}
                                    </span>
                        </td>
                    <td class="text-right">
                        <div class="btn-group flex-btn-group-container">
                            <router-link :to="{name: 'MovementView', params: {movementId: movement.id}}" tag="button" class="btn btn-info btn-sm">
                                <font-awesome-icon icon="eye"></font-awesome-icon>
                                <span class="d-none d-md-inline" v-text="$t('entity.action.view')">View</span>
                            </router-link>
                            <router-link :to="{name: 'MovementEdit', params: {movementId: movement.id}}"  tag="button" class="btn btn-primary btn-sm">
                                <font-awesome-icon icon="pencil-alt"></font-awesome-icon>
                                <span class="d-none d-md-inline" v-text="$t('entity.action.edit')">Edit</span>
                            </router-link>
                            <b-btn v-on:click="prepareRemove(movement)"
                                   class="btn btn-danger btn-sm"
                                   v-b-modal.removeEntity>
                                <font-awesome-icon icon="times"></font-awesome-icon>
                                <span class="d-none d-md-inline" v-text="$t('entity.action.delete')">Delete</span>
                            </b-btn>
                        </div>
                    </td>
                </tr>
                </tbody>
            </table>
        </div>
        <b-modal ref="removeEntity" id="removeEntity" >
            <span slot="modal-title"><span id="ecolarApp.movement.delete.question" v-text="$t('entity.delete.title')">Confirm delete operation</span></span>
            <div class="modal-body">
                <p id="eco-delete-movement-heading" v-bind:title="$t('ecolarApp.movement.delete.question')">Are you sure you want to delete this Movement?</p>
            </div>
            <div slot="modal-footer">
                <button type="button" class="btn btn-secondary" v-text="$t('entity.action.cancel')" v-on:click="closeDialog()">Cancel</button>
                <button type="button" class="btn btn-primary" id="eco-confirm-delete-movement" v-text="$t('entity.action.delete')" v-on:click="removeMovement()">Delete</button>
            </div>
        </b-modal>
    </div>
</template>

<script lang="ts" src="./movement.component.ts">
</script>
