// ecolarAdmin/src/main/webapp/app/entities/movement/movement.component.ts
import { Component, OnInit, OnDestroy } from '@angular/core';
import { HttpErrorResponse, HttpResponse } from '@angular/common/http';
import { Subscription } from 'rxjs';
import { JhiEventManager, JhiAlertService } from 'ng-jhipster';

import { IMovement } from 'app/shared/model/movement.model';
import { Principal } from 'app/core';
import { MovementService } from './movement.service';

@Component({
    selector: 'eco-movement',
    templateUrl: './movement.component.html'
})
export class MovementComponent implements OnInit, OnDestroy {
    movements: IMovement[];
    currentAccount: any;
    eventSubscriber: Subscription;

    constructor(
        private movementService: MovementService,
        private jhiAlertService: JhiAlertService,
        private eventManager: JhiEventManager,
        private principal: Principal
    ) {}

    loadAll() {
        this.movementService.query().subscribe(
            (res: HttpResponse<IMovement[]>) => {
                this.movements = res.body;
            },
            (res: HttpErrorResponse) => this.onError(res.message)
        );
    }

    ngOnInit() {
        this.loadAll();
        this.principal.identity().then(account => {
            this.currentAccount = account;
        });
        this.registerChangeInMovements();
    }

    ngOnDestroy() {
        this.eventManager.destroy(this.eventSubscriber);
    }

    trackId(index: number, item: IMovement) {
        return item.id;
    }

    registerChangeInMovements() {
        this.eventSubscriber = this.eventManager.subscribe('movementListModification', response => this.loadAll());
    }

    private onError(errorMessage: string) {
        this.jhiAlertService.error(errorMessage, null, null);
    }
}

<div>
    <h2 id="page-heading">
        <span jhiTranslate="ecolarAdminApp.movement.home.title">Movements</span>
        <button id="jh-create-entity" class="btn btn-primary float-right jh-create-entity create-movement" [routerLink]="['/movement/new']">
            <fa-icon [icon]="'plus'"></fa-icon>
            <span  jhiTranslate="ecolarAdminApp.movement.home.createLabel">
            Create new Movement
            </span>
        </button>
    </h2>
    <eco-alert></eco-alert>
    <br/>
    <div class="table-responsive" *ngIf="movements">
        <table class="table table-striped">
            <thead>
            <tr>
            <th><span jhiTranslate="global.field.id">ID</span></th>
            <th><span jhiTranslate="ecolarAdminApp.movement.eventTime">Event Time</span></th>
            <th><span jhiTranslate="ecolarAdminApp.movement.registrationTime">Registration Time</span></th>
            <th><span jhiTranslate="ecolarAdminApp.movement.amount">Amount</span></th>
            <th><span jhiTranslate="ecolarAdminApp.movement.location">Location</span></th>
            <th><span jhiTranslate="ecolarAdminApp.movement.eventLines">Event Lines</span></th>
            <th></th>
            </tr>
            </thead>
            <tbody>
            <tr *ngFor="let movement of movements ;trackBy: trackId">
                <td><a [routerLink]="['/movement', movement.id, 'view' ]">{{movement.id}}</a></td>
                <td>{{movement.eventTime | date:'medium'}}</td>
                <td>{{movement.registrationTime | date:'medium'}}</td>
                <td>{{movement.amount}}</td>
                <td>{{movement.location}}</td>
                <td>
                    <span *ngFor="let eventLines of movement.eventLines; let last = last">
                            <a class="form-control-static" [routerLink]="['../movement-line', eventLines?.id, 'view' ]">{{eventLines.id}}</a>{{last ? '' : ', '}}
                        </span>
                </td>
                <td class="text-right">
                    <div class="btn-group flex-btn-group-container">
                        <button type="submit"
                                [routerLink]="['/movement', movement.id, 'view' ]"
                                class="btn btn-info btn-sm">
                            <fa-icon [icon]="'eye'"></fa-icon>
                            <span class="d-none d-md-inline" jhiTranslate="entity.action.view">View</span>
                        </button>
                        <button type="submit"
                                [routerLink]="['/movement', movement.id, 'edit']"
                                class="btn btn-primary btn-sm">
                            <fa-icon [icon]="'pencil-alt'"></fa-icon>
                            <span class="d-none d-md-inline" jhiTranslate="entity.action.edit">Edit</span>
                        </button>
                        <button type="submit"
                                [routerLink]="['/', { outlets: { popup: 'movement/'+ movement.id + '/delete'} }]"
                                replaceUrl="true"
                                queryParamsHandling="merge"
                                class="btn btn-danger btn-sm">
                            <fa-icon [icon]="'times'"></fa-icon>
                            <span class="d-none d-md-inline" jhiTranslate="entity.action.delete">Delete</span>
                        </button>
                    </div>
                </td>
            </tr>
            </tbody>
        </table>
    </div>
</div>

// ecolar-mobile/src/main/webapp/app/entities/movement/movement.vue
<template>
    <div>
        <h2 id="page-heading">
            <span v-text="$t('ecolarApp.movement.home.title')" id="movement-heading">Movements</span>
            <router-link to="/entity/movement/new" tag="button" id="jh-create-entity" class="btn btn-primary float-right jh-create-entity create-movement">
                <font-awesome-icon icon="plus"></font-awesome-icon>
                <span  v-text="$t('ecolarApp.movement.home.createLabel')">
                    Create new Movement
                </span>
            </router-link>
        </h2>
        <!--<jhi-alert></jhi-alert>-->
        <br/>
        <div class="table-responsive" v-if="movements">
            <table class="table table-striped">
                <thead>
                <tr>
                    <th><span v-text="$t('global.field.id')">ID</span></th>
                        <th><span v-text="$t('ecolarApp.movement.eventTime')">Event Time</span></th>
                        <th><span v-text="$t('ecolarApp.movement.registrationTime')">Registration Time</span></th>
                        <th><span v-text="$t('ecolarApp.movement.amount')">Amount</span></th>
                        <th><span v-text="$t('ecolarApp.movement.location')">Location</span></th>
                            <th><span v-text="$t('ecolarApp.movement.eventLines')">Event Lines</span></th>
                    <th></th>
                </tr>
                </thead>
                <tbody>
                <tr v-for="movement in movements">
                    <td><router-link :to="{name: 'MovementView', params: {movementId: movement.id}}">{{movement.id}}</router-link></td>
                            <td>{{movement.eventTime | formatDate}}</td>
                            <td>{{movement.registrationTime | formatDate}}</td>
                            <td>{{movement.amount}}</td>
                            <td>{{movement.location}}</td>
                        <td>
                                    <span v-for="eventLines in movement.eventLines">
                                        <router-link class="form-control-static" :to="'../movement-line/' + eventLines.id}} + '/View'">{{eventLines.id}}</router-link>{{last ? '' : ', '}}
                                    </span>
                        </td>
                    <td class="text-right">
                        <div class="btn-group flex-btn-group-container">
                            <router-link :to="{name: 'MovementView', params: {movementId: movement.id}}" tag="button" class="btn btn-info btn-sm">
                                <font-awesome-icon icon="eye"></font-awesome-icon>
                                <span class="d-none d-md-inline" v-text="$t('entity.action.view')">View</span>
                            </router-link>
                            <router-link :to="{name: 'MovementEdit', params: {movementId: movement.id}}"  tag="button" class="btn btn-primary btn-sm">
                                <font-awesome-icon icon="pencil-alt"></font-awesome-icon>
                                <span class="d-none d-md-inline" v-text="$t('entity.action.edit')">Edit</span>
                            </router-link>
                            <b-btn v-on:click="prepareRemove(movement)"
                                   class="btn btn-danger btn-sm"
                                   v-b-modal.removeEntity>
                                <font-awesome-icon icon="times"></font-awesome-icon>
                                <span class="d-none d-md-inline" v-text="$t('entity.action.delete')">Delete</span>
                            </b-btn>
                        </div>
                    </td>
                </tr>
                </tbody>
            </table>
        </div>
        <b-modal ref="removeEntity" id="removeEntity" >
            <span slot="modal-title"><span id="ecolarApp.movement.delete.question" v-text="$t('entity.delete.title')">Confirm delete operation</span></span>
            <div class="modal-body">
                <p id="eco-delete-movement-heading" v-bind:title="$t('ecolarApp.movement.delete.question')">Are you sure you want to delete this Movement?</p>
            </div>
            <div slot="modal-footer">
                <button type="button" class="btn btn-secondary" v-text="$t('entity.action.cancel')" v-on:click="closeDialog()">Cancel</button>
                <button type="button" class="btn btn-primary" id="eco-confirm-delete-movement" v-text="$t('entity.action.delete')" v-on:click="removeMovement()">Delete</button>
            </div>
        </b-modal>
    </div>
</template>

<script lang="ts" src="./movement.component.ts">
</script>
