// ecolar-mobile/src/main/webapp/app/entities/category/category-update.vue
<template>
    <div class="row justify-content-center">
        <div class="col-8">
            <form name="editForm" role="form" novalidate v-on:submit.prevent="save()" >
                <h2 id="ecolarApp.category.home.createOrEditLabel" v-text="$t('ecolarApp.category.home.createOrEditLabel')">Create or edit a Category</h2>
                <div v-if="category">
                    <!--<jhi-alert-error></jhi-alert-error>-->
                    <div class="form-group" v-if="category.id">
                        <label for="id" v-text="$t('global.field.id')">ID</label>
                        <input type="text" class="form-control" id="id" name="id"
                               v-model="category.id" readonly />
                    </div>

                    <div class="form-group">
                        <label class="form-control-label" v-text="$t('ecolarApp.category.name')" for="category-name">Name</label>
                        <input type="text" class="form-control" name="name" id="category-name"
                            :class="{'valid': !$v.category.name.$invalid, 'invalid': $v.category.name.$invalid }" v-model="$v.category.name.$model" />
                    </div>
                    <div class="form-group">
                        <label class="form-control-label" v-text="$t('ecolarApp.category.description')" for="category-description">Description</label>
                        <input type="text" class="form-control" name="description" id="category-description"
                            :class="{'valid': !$v.category.description.$invalid, 'invalid': $v.category.description.$invalid }" v-model="$v.category.description.$model" />
                    </div>
                    <div class="form-group">
                        <label class="form-control-label" v-text="$t('ecolarApp.category.path')" for="category-path">Path</label>
                        <input type="text" class="form-control" name="path" id="category-path"
                            :class="{'valid': !$v.category.path.$invalid, 'invalid': $v.category.path.$invalid }" v-model="$v.category.path.$model" />
                    </div>
                    <div class="form-group">
                        <label class="form-control-label" v-text="$t('ecolarApp.category.parentId')" for="category-parentId">Parent Id</label>
                        <input type="text" class="form-control" name="parentId" id="category-parentId"
                            :class="{'valid': !$v.category.parentId.$invalid, 'invalid': $v.category.parentId.$invalid }" v-model="$v.category.parentId.$model" />
                    </div>
                    <div class="form-group">
                        <label class="form-control-label" v-text="$t('ecolarApp.category.accountType')" for="category-accountType">Account Type</label>
                        <select class="form-control" name="accountType" :class="{'valid': !$v.category.accountType.$invalid, 'invalid': $v.category.accountType.$invalid }" v-model="$v.category.accountType.$model" id="category-accountType" >
                            <option value="ASSETS" v-bind:label="$t('ecolarApp.AccountType.ASSETS')">ASSETS</option>
                            <option value="LIABILITIES" v-bind:label="$t('ecolarApp.AccountType.LIABILITIES')">LIABILITIES</option>
                            <option value="REVENUE" v-bind:label="$t('ecolarApp.AccountType.REVENUE')">REVENUE</option>
                            <option value="EXPENSE" v-bind:label="$t('ecolarApp.AccountType.EXPENSE')">EXPENSE</option>
                        </select>
                    </div>

                        <div class="form-group">
                            <label class="form-control-label" v-bind:value="$t('ecolarApp.category.parent')" for="category-parent">Parent</label>
                                <select class="form-control" id="category-parent" name="parent" v-model="category.parent" >
                                    <option value="null"></option>
                                    <option v-bind:value="category.parent && categoryOption.id === category.parent.id ? category.parent : categoryOption" v-for="categoryOption in categories">{{categoryOption.name}}</option>
                                </select>
                        </div>
                        <div class="form-group">
                            <label class="form-control-label" v-bind:value="$t('ecolarApp.category.document')" for="category-document">Document</label>
                                <select class="form-control" id="category-document" name="document" v-model="category.document" >
                                    <option value="null"></option>
                                    <option v-bind:value="category.document && accountCategoriesOption.id === category.document.id ? category.document : accountCategoriesOption" v-for="accountCategoriesOption in accountCategories">{{accountCategoriesOption.id}}</option>
                                </select>
                        </div>

                </div>
                <div>
                    <button type="button" id="cancel-save" class="btn btn-secondary" v-on:click="previousState()">
                        <font-awesome-icon icon="ban"></font-awesome-icon>&nbsp;<span v-text="$t('entity.action.cancel')">Cancel</span>
                    </button>
                    <button type="submit" id="save-entity" :disabled="$v.category.$invalid || isSaving" class="btn btn-primary">
                        <font-awesome-icon icon="save"></font-awesome-icon>&nbsp;<span v-text="$t('entity.action.save')">Save</span>
                    </button>
                </div>
            </form>
        </div>
    </div>
</template>
<script lang="ts" src="./category-update.component.ts">
</script>

// ecolar-admin/src/main/webapp/app/entities/category/category-update.component.ts
import { Component, OnInit } from '@angular/core';
import { ActivatedRoute } from '@angular/router';
import { HttpResponse, HttpErrorResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { JhiAlertService } from 'ng-jhipster';

import { ICategory } from 'app/shared/model/category.model';
import { CategoryService } from './category.service';
import { IAccountCategories } from 'app/shared/model/account-categories.model';
import { AccountCategoriesService } from 'app/entities/account-categories';

@Component({
    selector: 'eco-category-update',
    templateUrl: './category-update.component.html'
})
export class CategoryUpdateComponent implements OnInit {
    category: ICategory;
    isSaving: boolean;

    categories: ICategory[];

    accountcategories: IAccountCategories[];

    constructor(
        private jhiAlertService: JhiAlertService,
        private categoryService: CategoryService,
        private accountCategoriesService: AccountCategoriesService,
        private activatedRoute: ActivatedRoute
    ) {}

    ngOnInit() {
        this.isSaving = false;
        this.activatedRoute.data.subscribe(({ category }) => {
            this.category = category;
        });
        this.categoryService.query().subscribe(
            (res: HttpResponse<ICategory[]>) => {
                this.categories = res.body;
            },
            (res: HttpErrorResponse) => this.onError(res.message)
        );
        this.accountCategoriesService.query().subscribe(
            (res: HttpResponse<IAccountCategories[]>) => {
                this.accountcategories = res.body;
            },
            (res: HttpErrorResponse) => this.onError(res.message)
        );
    }

    previousState() {
        window.history.back();
    }

    save() {
        this.isSaving = true;
        if (this.category.id !== undefined) {
            this.subscribeToSaveResponse(this.categoryService.update(this.category));
        } else {
            this.subscribeToSaveResponse(this.categoryService.create(this.category));
        }
    }

    private subscribeToSaveResponse(result: Observable<HttpResponse<ICategory>>) {
        result.subscribe((res: HttpResponse<ICategory>) => this.onSaveSuccess(), (res: HttpErrorResponse) => this.onSaveError());
    }

    private onSaveSuccess() {
        this.isSaving = false;
        this.previousState();
    }

    private onSaveError() {
        this.isSaving = false;
    }

    private onError(errorMessage: string) {
        this.jhiAlertService.error(errorMessage, null, null);
    }

    trackCategoryById(index: number, item: ICategory) {
        return item.id;
    }

    trackAccountCategoriesById(index: number, item: IAccountCategories) {
        return item.id;
    }
}

<div class="row justify-content-center">
    <div class="col-8">
        <form name="editForm" role="form" novalidate (ngSubmit)="save()" #editForm="ngForm">
            <h2 id="eco-category-heading" jhiTranslate="ecolarApp.category.home.createOrEditLabel">Create or edit a Category</h2>
            <div>
                <eco-alert-error></eco-alert-error>
                <div class="form-group" [hidden]="!category.id">
                    <label for="id" jhiTranslate="global.field.id">ID</label>
                    <input type="text" class="form-control" id="id" name="id"
                        [(ngModel)]="category.id" readonly />
                </div>
                <div class="form-group">
                    <label class="form-control-label" jhiTranslate="ecolarApp.category.name" for="field_name">Name</label>
                    <input type="text" class="form-control" name="name" id="field_name"
                        [(ngModel)]="category.name" />
                </div>
                <div class="form-group">
                    <label class="form-control-label" jhiTranslate="ecolarApp.category.description" for="field_description">Description</label>
                    <input type="text" class="form-control" name="description" id="field_description"
                        [(ngModel)]="category.description" />
                </div>
                <div class="form-group">
                    <label class="form-control-label" jhiTranslate="ecolarApp.category.path" for="field_path">Path</label>
                    <input type="text" class="form-control" name="path" id="field_path"
                        [(ngModel)]="category.path" />
                </div>
                <div class="form-group">
                    <label class="form-control-label" jhiTranslate="ecolarApp.category.parentId" for="field_parentId">Parent Id</label>
                    <input type="text" class="form-control" name="parentId" id="field_parentId"
                        [(ngModel)]="category.parentId" />
                </div>
                <div class="form-group">
                    <label class="form-control-label" jhiTranslate="ecolarApp.category.accountType" for="field_accountType">Account Type</label>
                    <select class="form-control" name="accountType" [(ngModel)]="category.accountType" id="field_accountType" >
                        <option value="ASSETS">{{'ecolarApp.AccountType.ASSETS' | translate}}</option>
                        <option value="LIABILITIES">{{'ecolarApp.AccountType.LIABILITIES' | translate}}</option>
                        <option value="REVENUE">{{'ecolarApp.AccountType.REVENUE' | translate}}</option>
                        <option value="EXPENSE">{{'ecolarApp.AccountType.EXPENSE' | translate}}</option>
                    </select>
                </div>

                <div class="form-group">
                    <label class="form-control-label" jhiTranslate="ecolarApp.category.parent" for="field_parent">Parent</label>
                    <select class="form-control" id="field_parent" name="parent" [(ngModel)]="category.parent" >
                        <option [ngValue]="null"></option>
                        <option [ngValue]="categoryOption.id === category.parent?.id ? category.parent : categoryOption" *ngFor="let categoryOption of categories; trackBy: trackCategoryById">{{categoryOption.name}}</option>
                    </select>
                </div>
                <div class="form-group">
                    <label class="form-control-label" jhiTranslate="ecolarApp.category.document" for="field_document">Document</label>
                    <select class="form-control" id="field_document" name="document" [(ngModel)]="category.document" >
                        <option [ngValue]="null"></option>
                        <option [ngValue]="accountCategoriesOption.id === category.document?.id ? category.document : accountCategoriesOption" *ngFor="let accountCategoriesOption of accountcategories; trackBy: trackAccountCategoriesById">{{accountCategoriesOption.id}}</option>
                    </select>
                </div>
            </div>
            <div>
                <button type="button" id="cancel-save" class="btn btn-secondary"  (click)="previousState()">
                    <fa-icon [icon]="'ban'"></fa-icon>&nbsp;<span jhiTranslate="entity.action.cancel">Cancel</span>
                </button>
                <button type="submit" id="save-entity" [disabled]="editForm.form.invalid || isSaving" class="btn btn-primary">
                    <fa-icon [icon]="'save'"></fa-icon>&nbsp;<span jhiTranslate="entity.action.save">Save</span>
                </button>
            </div>
        </form>
    </div>
</div>
