// ecolarAdmin/src/main/webapp/app/entities/accounts-document/accounts-document-detail.component.ts
import { Component, OnInit } from '@angular/core';
import { ActivatedRoute } from '@angular/router';

import { IAccountsDocument } from 'app/shared/model/accounts-document.model';

@Component({
    selector: 'eco-accounts-document-detail',
    templateUrl: './accounts-document-detail.component.html'
})
export class AccountsDocumentDetailComponent implements OnInit {
    accountsDocument: IAccountsDocument;

    constructor(private activatedRoute: ActivatedRoute) {}

    ngOnInit() {
        this.activatedRoute.data.subscribe(({ accountsDocument }) => {
            this.accountsDocument = accountsDocument;
        });
    }

    previousState() {
        window.history.back();
    }
}

<div class="row justify-content-center">
    <div class="col-8">
        <div *ngIf="accountsDocument">
            <h2><span jhiTranslate="ecolarAdminApp.accountsDocument.detail.title">Accounts Document</span> {{accountsDocument.id}}</h2>
            <hr>
            <eco-alert-error></eco-alert-error>
            <dl class="row-md jh-entity-details">
            </dl>

            <button type="submit"
                    (click)="previousState()"
                    class="btn btn-info">
                <fa-icon [icon]="'arrow-left'"></fa-icon>&nbsp;<span jhiTranslate="entity.action.back"> Back</span>
            </button>

            <button type="button"
                    [routerLink]="['/accounts-document', accountsDocument.id, 'edit']"
                    class="btn btn-primary">
                <fa-icon [icon]="'pencil-alt'"></fa-icon>&nbsp;<span jhiTranslate="entity.action.edit"> Edit</span>
            </button>
        </div>
    </div>
</div>

// ecolarMobile/src/main/webapp/app/entities/accounts-document/accounts-document-detail.tsx
import React from 'react';
import { connect } from 'react-redux';
import { Link, RouteComponentProps } from 'react-router-dom';
import { Button, Row, Col } from 'reactstrap';
// tslint:disable-next-line:no-unused-variable
import { Translate, ICrudGetAction } from 'react-jhipster';
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome';

import { IRootState } from 'app/shared/reducers';
import { getEntity } from './accounts-document.reducer';
import { IAccountsDocument } from 'app/shared/model/accounts-document.model';
// tslint:disable-next-line:no-unused-variable
import { APP_DATE_FORMAT, APP_LOCAL_DATE_FORMAT } from 'app/config/constants';

export interface IAccountsDocumentDetailProps extends StateProps, DispatchProps, RouteComponentProps<{ id: string }> {}

export class AccountsDocumentDetail extends React.Component<IAccountsDocumentDetailProps> {
  componentDidMount() {
    this.props.getEntity(this.props.match.params.id);
  }

  render() {
    const { accountsDocumentEntity } = this.props;
    return (
      <Row>
        <Col md="8">
          <h2>
            <Translate contentKey="ecolarMobileApp.accountsDocument.detail.title">AccountsDocument</Translate> [<b>
              {accountsDocumentEntity.id}
            </b>]
          </h2>
          <dl className="jh-entity-details" />
          <Button tag={Link} to="/entity/accounts-document" replace color="info">
            <FontAwesomeIcon icon="arrow-left" />{' '}
            <span className="d-none d-md-inline">
              <Translate contentKey="entity.action.back">Back</Translate>
            </span>
          </Button>&nbsp;
          <Button tag={Link} to={`/entity/accounts-document/${accountsDocumentEntity.id}/edit`} replace color="primary">
            <FontAwesomeIcon icon="pencil-alt" />{' '}
            <span className="d-none d-md-inline">
              <Translate contentKey="entity.action.edit">Edit</Translate>
            </span>
          </Button>
        </Col>
      </Row>
    );
  }
}

const mapStateToProps = ({ accountsDocument }: IRootState) => ({
  accountsDocumentEntity: accountsDocument.entity
});

const mapDispatchToProps = { getEntity };

type StateProps = ReturnType<typeof mapStateToProps>;
type DispatchProps = typeof mapDispatchToProps;

export default connect(
  mapStateToProps,
  mapDispatchToProps
)(AccountsDocumentDetail);
