// ecolarAdmin/src/main/webapp/app/entities/category/category-update.component.ts
import { Component, OnInit } from '@angular/core';
import { ActivatedRoute } from '@angular/router';
import { HttpResponse, HttpErrorResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { JhiAlertService } from 'ng-jhipster';

import { ICategory } from 'app/shared/model/category.model';
import { CategoryService } from './category.service';
import { IAccountsDocument } from 'app/shared/model/accounts-document.model';
import { AccountsDocumentService } from 'app/entities/accounts-document';

@Component({
    selector: 'eco-category-update',
    templateUrl: './category-update.component.html'
})
export class CategoryUpdateComponent implements OnInit {
    category: ICategory;
    isSaving: boolean;

    categories: ICategory[];

    accountsdocuments: IAccountsDocument[];

    constructor(
        private jhiAlertService: JhiAlertService,
        private categoryService: CategoryService,
        private accountsDocumentService: AccountsDocumentService,
        private activatedRoute: ActivatedRoute
    ) {}

    ngOnInit() {
        this.isSaving = false;
        this.activatedRoute.data.subscribe(({ category }) => {
            this.category = category;
        });
        this.categoryService.query().subscribe(
            (res: HttpResponse<ICategory[]>) => {
                this.categories = res.body;
            },
            (res: HttpErrorResponse) => this.onError(res.message)
        );
        this.accountsDocumentService.query().subscribe(
            (res: HttpResponse<IAccountsDocument[]>) => {
                this.accountsdocuments = res.body;
            },
            (res: HttpErrorResponse) => this.onError(res.message)
        );
    }

    previousState() {
        window.history.back();
    }

    save() {
        this.isSaving = true;
        if (this.category.id !== undefined) {
            this.subscribeToSaveResponse(this.categoryService.update(this.category));
        } else {
            this.subscribeToSaveResponse(this.categoryService.create(this.category));
        }
    }

    private subscribeToSaveResponse(result: Observable<HttpResponse<ICategory>>) {
        result.subscribe((res: HttpResponse<ICategory>) => this.onSaveSuccess(), (res: HttpErrorResponse) => this.onSaveError());
    }

    private onSaveSuccess() {
        this.isSaving = false;
        this.previousState();
    }

    private onSaveError() {
        this.isSaving = false;
    }

    private onError(errorMessage: string) {
        this.jhiAlertService.error(errorMessage, null, null);
    }

    trackCategoryById(index: number, item: ICategory) {
        return item.id;
    }

    trackAccountsDocumentById(index: number, item: IAccountsDocument) {
        return item.id;
    }
}

<div class="row justify-content-center">
    <div class="col-8">
        <form name="editForm" role="form" novalidate (ngSubmit)="save()" #editForm="ngForm">
            <h2 id="eco-category-heading" jhiTranslate="ecolarAdminApp.category.home.createOrEditLabel">Create or edit a Category</h2>
            <div>
                <eco-alert-error></eco-alert-error>
                <div class="form-group" [hidden]="!category.id">
                    <label for="id" jhiTranslate="global.field.id">ID</label>
                    <input type="text" class="form-control" id="id" name="id"
                        [(ngModel)]="category.id" readonly />
                </div>
                <div class="form-group">
                    <label class="form-control-label" jhiTranslate="ecolarAdminApp.category.name" for="field_name">Name</label>
                    <input type="text" class="form-control" name="name" id="field_name"
                        [(ngModel)]="category.name" />
                </div>
                <div class="form-group">
                    <label class="form-control-label" jhiTranslate="ecolarAdminApp.category.description" for="field_description">Description</label>
                    <input type="text" class="form-control" name="description" id="field_description"
                        [(ngModel)]="category.description" />
                </div>
                <div class="form-group">
                    <label class="form-control-label" jhiTranslate="ecolarAdminApp.category.path" for="field_path">Path</label>
                    <input type="text" class="form-control" name="path" id="field_path"
                        [(ngModel)]="category.path" />
                </div>
                <div class="form-group">
                    <label class="form-control-label" jhiTranslate="ecolarAdminApp.category.parentId" for="field_parentId">Parent Id</label>
                    <input type="text" class="form-control" name="parentId" id="field_parentId"
                        [(ngModel)]="category.parentId" />
                </div>
                <div class="form-group">
                    <label class="form-control-label" jhiTranslate="ecolarAdminApp.category.accountType" for="field_accountType">Account Type</label>
                    <select class="form-control" name="accountType" [(ngModel)]="category.accountType" id="field_accountType" >
                        <option value="ASSETS">{{'ecolarAdminApp.AccountType.ASSETS' | translate}}</option>
                        <option value="LIABILITIES">{{'ecolarAdminApp.AccountType.LIABILITIES' | translate}}</option>
                        <option value="REVENUE">{{'ecolarAdminApp.AccountType.REVENUE' | translate}}</option>
                        <option value="EXPENSE">{{'ecolarAdminApp.AccountType.EXPENSE' | translate}}</option>
                    </select>
                </div>

                <div class="form-group">
                    <label class="form-control-label" jhiTranslate="ecolarAdminApp.category.parent" for="field_parent">Parent</label>
                    <select class="form-control" id="field_parent" name="parent" [(ngModel)]="category.parent" >
                        <option [ngValue]="null"></option>
                        <option [ngValue]="categoryOption.id === category.parent?.id ? category.parent : categoryOption" *ngFor="let categoryOption of categories; trackBy: trackCategoryById">{{categoryOption.name}}</option>
                    </select>
                </div>
                <div class="form-group">
                    <label class="form-control-label" jhiTranslate="ecolarAdminApp.category.document" for="field_document">Document</label>
                    <select class="form-control" id="field_document" name="document" [(ngModel)]="category.document" >
                        <option [ngValue]="null"></option>
                        <option [ngValue]="accountsDocumentOption.id === category.document?.id ? category.document : accountsDocumentOption" *ngFor="let accountsDocumentOption of accountsdocuments; trackBy: trackAccountsDocumentById">{{accountsDocumentOption.id}}</option>
                    </select>
                </div>
            </div>
            <div>
                <button type="button" id="cancel-save" class="btn btn-secondary"  (click)="previousState()">
                    <fa-icon [icon]="'ban'"></fa-icon>&nbsp;<span jhiTranslate="entity.action.cancel">Cancel</span>
                </button>
                <button type="submit" id="save-entity" [disabled]="editForm.form.invalid || isSaving" class="btn btn-primary">
                    <fa-icon [icon]="'save'"></fa-icon>&nbsp;<span jhiTranslate="entity.action.save">Save</span>
                </button>
            </div>
        </form>
    </div>
</div>

// ecolarMobile/src/main/webapp/app/entities/category/category-update.tsx
import React from 'react';
import { connect } from 'react-redux';
import { Link, RouteComponentProps } from 'react-router-dom';
import { Button, Row, Col, Label } from 'reactstrap';
import { AvForm, AvGroup, AvInput, AvField } from 'availity-reactstrap-validation';
// tslint:disable-next-line:no-unused-variable
import { Translate, translate, ICrudGetAction, ICrudGetAllAction, ICrudPutAction } from 'react-jhipster';
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome';
import { IRootState } from 'app/shared/reducers';

import { getEntities as getCategories } from 'app/entities/category/category.reducer';
import { IAccountsDocument } from 'app/shared/model/accounts-document.model';
import { getEntities as getAccountsDocuments } from 'app/entities/accounts-document/accounts-document.reducer';
import { getEntity, updateEntity, createEntity, reset } from './category.reducer';
import { ICategory } from 'app/shared/model/category.model';
// tslint:disable-next-line:no-unused-variable
import { convertDateTimeFromServer } from 'app/shared/util/date-utils';
import { mapIdList } from 'app/shared/util/entity-utils';

export interface ICategoryUpdateProps extends StateProps, DispatchProps, RouteComponentProps<{ id: string }> {}

export interface ICategoryUpdateState {
  isNew: boolean;
  parentId: string;
  categoriesId: string;
  documentId: string;
}

export class CategoryUpdate extends React.Component<ICategoryUpdateProps, ICategoryUpdateState> {
  constructor(props) {
    super(props);
    this.state = {
      parentId: '0',
      categoriesId: '0',
      documentId: '0',
      isNew: !this.props.match.params || !this.props.match.params.id
    };
  }

  componentDidMount() {
    if (this.state.isNew) {
      this.props.reset();
    } else {
      this.props.getEntity(this.props.match.params.id);
    }

    this.props.getCategories();
    this.props.getAccountsDocuments();
  }

  saveEntity = (event, errors, values) => {
    if (errors.length === 0) {
      const { categoryEntity } = this.props;
      const entity = {
        ...categoryEntity,
        ...values
      };

      if (this.state.isNew) {
        this.props.createEntity(entity);
      } else {
        this.props.updateEntity(entity);
      }
      this.handleClose();
    }
  };

  handleClose = () => {
    this.props.history.push('/entity/category');
  };

  render() {
    const { categoryEntity, categories, accountsDocuments, loading, updating } = this.props;
    const { isNew } = this.state;

    return (
      <div>
        <Row className="justify-content-center">
          <Col md="8">
            <h2 id="ecolarMobileApp.category.home.createOrEditLabel">
              <Translate contentKey="ecolarMobileApp.category.home.createOrEditLabel">Create or edit a Category</Translate>
            </h2>
          </Col>
        </Row>
        <Row className="justify-content-center">
          <Col md="8">
            {loading ? (
              <p>Loading...</p>
            ) : (
              <AvForm model={isNew ? {} : categoryEntity} onSubmit={this.saveEntity}>
                {!isNew ? (
                  <AvGroup>
                    <Label for="id">
                      <Translate contentKey="global.field.id">ID</Translate>
                    </Label>
                    <AvInput id="category-id" type="text" className="form-control" name="id" required readOnly />
                  </AvGroup>
                ) : null}
                <AvGroup>
                  <Label id="nameLabel" for="name">
                    <Translate contentKey="ecolarMobileApp.category.name">Name</Translate>
                  </Label>
                  <AvField id="category-name" type="text" name="name" />
                </AvGroup>
                <AvGroup>
                  <Label id="descriptionLabel" for="description">
                    <Translate contentKey="ecolarMobileApp.category.description">Description</Translate>
                  </Label>
                  <AvField id="category-description" type="text" name="description" />
                </AvGroup>
                <AvGroup>
                  <Label id="pathLabel" for="path">
                    <Translate contentKey="ecolarMobileApp.category.path">Path</Translate>
                  </Label>
                  <AvField id="category-path" type="text" name="path" />
                </AvGroup>
                <AvGroup>
                  <Label id="parentIdLabel" for="parentId">
                    <Translate contentKey="ecolarMobileApp.category.parentId">Parent Id</Translate>
                  </Label>
                  <AvField id="category-parentId" type="text" name="parentId" />
                </AvGroup>
                <AvGroup>
                  <Label id="accountTypeLabel">
                    <Translate contentKey="ecolarMobileApp.category.accountType">Account Type</Translate>
                  </Label>
                  <AvInput
                    id="category-accountType"
                    type="select"
                    className="form-control"
                    name="accountType"
                    value={(!isNew && categoryEntity.accountType) || 'ASSETS'}
                  >
                    <option value="ASSETS">
                      <Translate contentKey="ecolarMobileApp.AccountType.ASSETS" />
                    </option>
                    <option value="LIABILITIES">
                      <Translate contentKey="ecolarMobileApp.AccountType.LIABILITIES" />
                    </option>
                    <option value="REVENUE">
                      <Translate contentKey="ecolarMobileApp.AccountType.REVENUE" />
                    </option>
                    <option value="EXPENSE">
                      <Translate contentKey="ecolarMobileApp.AccountType.EXPENSE" />
                    </option>
                  </AvInput>
                </AvGroup>
                <AvGroup>
                  <Label for="parent.name">
                    <Translate contentKey="ecolarMobileApp.category.parent">Parent</Translate>
                  </Label>
                  <AvInput id="category-parent" type="select" className="form-control" name="parent.id">
                    <option value="" key="0" />
                    {categories
                      ? categories.map(otherEntity => (
                          <option value={otherEntity.id} key={otherEntity.id}>
                            {otherEntity.name}
                          </option>
                        ))
                      : null}
                  </AvInput>
                </AvGroup>
                <AvGroup>
                  <Label for="document.id">
                    <Translate contentKey="ecolarMobileApp.category.document">Document</Translate>
                  </Label>
                  <AvInput id="category-document" type="select" className="form-control" name="document.id">
                    <option value="" key="0" />
                    {accountsDocuments
                      ? accountsDocuments.map(otherEntity => (
                          <option value={otherEntity.id} key={otherEntity.id}>
                            {otherEntity.id}
                          </option>
                        ))
                      : null}
                  </AvInput>
                </AvGroup>
                <Button tag={Link} id="cancel-save" to="/entity/category" replace color="info">
                  <FontAwesomeIcon icon="arrow-left" />&nbsp;
                  <span className="d-none d-md-inline">
                    <Translate contentKey="entity.action.back">Back</Translate>
                  </span>
                </Button>
                &nbsp;
                <Button color="primary" id="save-entity" type="submit" disabled={updating}>
                  <FontAwesomeIcon icon="save" />&nbsp;
                  <Translate contentKey="entity.action.save">Save</Translate>
                </Button>
              </AvForm>
            )}
          </Col>
        </Row>
      </div>
    );
  }
}

const mapStateToProps = (storeState: IRootState) => ({
  categories: storeState.category.entities,
  accountsDocuments: storeState.accountsDocument.entities,
  categoryEntity: storeState.category.entity,
  loading: storeState.category.loading,
  updating: storeState.category.updating
});

const mapDispatchToProps = {
  getCategories,
  getAccountsDocuments,
  getEntity,
  updateEntity,
  createEntity,
  reset
};

type StateProps = ReturnType<typeof mapStateToProps>;
type DispatchProps = typeof mapDispatchToProps;

export default connect(
  mapStateToProps,
  mapDispatchToProps
)(CategoryUpdate);
