// ecolar-mobile/src/main/webapp/app/entities/movement/movement-update.vue
<template>
    <div class="row justify-content-center">
        <div class="col-8">
            <form name="editForm" role="form" novalidate v-on:submit.prevent="save()" >
                <h2 id="ecolarApp.movement.home.createOrEditLabel" v-text="$t('ecolarApp.movement.home.createOrEditLabel')">Create or edit a Movement</h2>
                <div>
                    <!--<jhi-alert-error></jhi-alert-error>-->
                    <div class="form-group" v-if="movement.id">
                        <label for="id" v-text="$t('global.field.id')">ID</label>
                        <input type="text" class="form-control" id="id" name="id"
                               v-model="movement.id" readonly />
                    </div>

                    <div class="form-group">
                        <label class="form-control-label" v-text="$t('ecolarApp.movement.eventTime')" for="movement-eventTime">Event Time</label>
                        <div class="d-flex">
                            <input id="movement-eventTime" type="datetime-local" class="form-control" name="eventTime" :class="{'valid': !$v.movement.eventTime.$invalid, 'invalid': $v.movement.eventTime.$invalid }" v-model="$v.movement.eventTime.$model" />
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="form-control-label" v-text="$t('ecolarApp.movement.registrationTime')" for="movement-registrationTime">Registration Time</label>
                        <div class="d-flex">
                            <input id="movement-registrationTime" type="datetime-local" class="form-control" name="registrationTime" :class="{'valid': !$v.movement.registrationTime.$invalid, 'invalid': $v.movement.registrationTime.$invalid }" v-model="$v.movement.registrationTime.$model" />
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="form-control-label" v-text="$t('ecolarApp.movement.amount')" for="movement-amount">Amount</label>
                        <input type="number" class="form-control" name="amount" id="movement-amount"
                            :class="{'valid': !$v.movement.amount.$invalid, 'invalid': $v.movement.amount.$invalid }" v-model="$v.movement.amount.$model" />
                    </div>
                    <div class="form-group">
                        <label class="form-control-label" v-text="$t('ecolarApp.movement.location')" for="movement-location">Location</label>
                        <input type="text" class="form-control" name="location" id="movement-location"
                            :class="{'valid': !$v.movement.location.$invalid, 'invalid': $v.movement.location.$invalid }" v-model="$v.movement.location.$model" />
                    </div>

                        <div class="form-group">
                            <label v-text="$t('ecolarApp.movement.eventLines')" for="movement-eventLines">Event Lines</label>
                            <select class="form-control" id="movement-eventLines" multiple name="eventLines" v-model="movement.eventLines">
                                <option v-bind:value="getSelected(movement.eventLines, movementLineOption)" v-for="movementLineOption in movementLines">{{movementLineOption.id}}</option>
                            </select>
                        </div>

                </div>
                <div>
                    <button type="button" id="cancel-save" class="btn btn-secondary" v-on:click="previousState()">
                        <font-awesome-icon icon="ban"></font-awesome-icon>&nbsp;<span v-text="$t('entity.action.cancel')">Cancel</span>
                    </button>
                    <button type="submit" id="save-entity" :disabled="$v.movement.$invalid || isSaving" class="btn btn-primary">
                        <font-awesome-icon icon="save"></font-awesome-icon>&nbsp;<span v-text="$t('entity.action.save')">Save</span>
                    </button>
                </div>
            </form>
        </div>
    </div>
</template>
<script lang="ts" src="./movement-update.component.ts">
</script>

// ecolarMobile/src/main/webapp/app/entities/movement/movement-update.tsx
import React from 'react';
import { connect } from 'react-redux';
import { Link, RouteComponentProps } from 'react-router-dom';
import { Button, Row, Col, Label } from 'reactstrap';
import { AvForm, AvGroup, AvInput, AvField } from 'availity-reactstrap-validation';
// tslint:disable-next-line:no-unused-variable
import { Translate, translate, ICrudGetAction, ICrudGetAllAction, ICrudPutAction } from 'react-jhipster';
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome';
import { IRootState } from 'app/shared/reducers';

import { IMovementLine } from 'app/shared/model/movement-line.model';
import { getEntities as getMovementLines } from 'app/entities/movement-line/movement-line.reducer';
import { getEntity, updateEntity, createEntity, reset } from './movement.reducer';
import { IMovement } from 'app/shared/model/movement.model';
// tslint:disable-next-line:no-unused-variable
import { convertDateTimeFromServer } from 'app/shared/util/date-utils';
import { mapIdList } from 'app/shared/util/entity-utils';

export interface IMovementUpdateProps extends StateProps, DispatchProps, RouteComponentProps<{ id: string }> {}

export interface IMovementUpdateState {
  isNew: boolean;
  idseventLines: any[];
}

export class MovementUpdate extends React.Component<IMovementUpdateProps, IMovementUpdateState> {
  constructor(props) {
    super(props);
    this.state = {
      idseventLines: [],
      isNew: !this.props.match.params || !this.props.match.params.id
    };
  }

  componentDidMount() {
    if (this.state.isNew) {
      this.props.reset();
    } else {
      this.props.getEntity(this.props.match.params.id);
    }

    this.props.getMovementLines();
  }

  saveEntity = (event, errors, values) => {
    values.eventTime = new Date(values.eventTime);
    values.registrationTime = new Date(values.registrationTime);

    if (errors.length === 0) {
      const { movementEntity } = this.props;
      const entity = {
        ...movementEntity,
        ...values,
        eventLines: mapIdList(values.eventLines)
      };

      if (this.state.isNew) {
        this.props.createEntity(entity);
      } else {
        this.props.updateEntity(entity);
      }
      this.handleClose();
    }
  };

  handleClose = () => {
    this.props.history.push('/entity/movement');
  };

  render() {
    const { movementEntity, movementLines, loading, updating } = this.props;
    const { isNew } = this.state;

    return (
      <div>
        <Row className="justify-content-center">
          <Col md="8">
            <h2 id="ecolarMobileApp.movement.home.createOrEditLabel">
              <Translate contentKey="ecolarMobileApp.movement.home.createOrEditLabel">Create or edit a Movement</Translate>
            </h2>
          </Col>
        </Row>
        <Row className="justify-content-center">
          <Col md="8">
            {loading ? (
              <p>Loading...</p>
            ) : (
              <AvForm model={isNew ? {} : movementEntity} onSubmit={this.saveEntity}>
                {!isNew ? (
                  <AvGroup>
                    <Label for="id">
                      <Translate contentKey="global.field.id">ID</Translate>
                    </Label>
                    <AvInput id="movement-id" type="text" className="form-control" name="id" required readOnly />
                  </AvGroup>
                ) : null}
                <AvGroup>
                  <Label id="eventTimeLabel" for="eventTime">
                    <Translate contentKey="ecolarMobileApp.movement.eventTime">Event Time</Translate>
                  </Label>
                  <AvInput
                    id="movement-eventTime"
                    type="datetime-local"
                    className="form-control"
                    name="eventTime"
                    value={isNew ? null : convertDateTimeFromServer(this.props.movementEntity.eventTime)}
                  />
                </AvGroup>
                <AvGroup>
                  <Label id="registrationTimeLabel" for="registrationTime">
                    <Translate contentKey="ecolarMobileApp.movement.registrationTime">Registration Time</Translate>
                  </Label>
                  <AvInput
                    id="movement-registrationTime"
                    type="datetime-local"
                    className="form-control"
                    name="registrationTime"
                    value={isNew ? null : convertDateTimeFromServer(this.props.movementEntity.registrationTime)}
                  />
                </AvGroup>
                <AvGroup>
                  <Label id="amountLabel" for="amount">
                    <Translate contentKey="ecolarMobileApp.movement.amount">Amount</Translate>
                  </Label>
                  <AvField id="movement-amount" type="text" name="amount" />
                </AvGroup>
                <AvGroup>
                  <Label id="locationLabel" for="location">
                    <Translate contentKey="ecolarMobileApp.movement.location">Location</Translate>
                  </Label>
                  <AvField id="movement-location" type="text" name="location" />
                </AvGroup>
                <AvGroup>
                  <Label for="movementLines">
                    <Translate contentKey="ecolarMobileApp.movement.eventLines">Event Lines</Translate>
                  </Label>
                  <AvInput
                    id="movement-eventLines"
                    type="select"
                    multiple
                    className="form-control"
                    name="eventLines"
                    value={movementEntity.eventLines && movementEntity.eventLines.map(e => e.id)}
                  >
                    <option value="" key="0" />
                    {movementLines
                      ? movementLines.map(otherEntity => (
                          <option value={otherEntity.id} key={otherEntity.id}>
                            {otherEntity.id}
                          </option>
                        ))
                      : null}
                  </AvInput>
                </AvGroup>
                <Button tag={Link} id="cancel-save" to="/entity/movement" replace color="info">
                  <FontAwesomeIcon icon="arrow-left" />&nbsp;
                  <span className="d-none d-md-inline">
                    <Translate contentKey="entity.action.back">Back</Translate>
                  </span>
                </Button>
                &nbsp;
                <Button color="primary" id="save-entity" type="submit" disabled={updating}>
                  <FontAwesomeIcon icon="save" />&nbsp;
                  <Translate contentKey="entity.action.save">Save</Translate>
                </Button>
              </AvForm>
            )}
          </Col>
        </Row>
      </div>
    );
  }
}

const mapStateToProps = (storeState: IRootState) => ({
  movementLines: storeState.movementLine.entities,
  movementEntity: storeState.movement.entity,
  loading: storeState.movement.loading,
  updating: storeState.movement.updating
});

const mapDispatchToProps = {
  getMovementLines,
  getEntity,
  updateEntity,
  createEntity,
  reset
};

type StateProps = ReturnType<typeof mapStateToProps>;
type DispatchProps = typeof mapDispatchToProps;

export default connect(
  mapStateToProps,
  mapDispatchToProps
)(MovementUpdate);
