// ecolarMobile/src/main/webapp/app/entities/category/category.tsx
import React from 'react';
import { connect } from 'react-redux';
import { Link, RouteComponentProps } from 'react-router-dom';
import { Button, Col, Row, Table } from 'reactstrap';
// tslint:disable-next-line:no-unused-variable
import { Translate, ICrudGetAllAction } from 'react-jhipster';
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome';

import { IRootState } from 'app/shared/reducers';
import { getEntities } from './category.reducer';
import { ICategory } from 'app/shared/model/category.model';
// tslint:disable-next-line:no-unused-variable
import { APP_DATE_FORMAT, APP_LOCAL_DATE_FORMAT } from 'app/config/constants';

export interface ICategoryProps extends StateProps, DispatchProps, RouteComponentProps<{ url: string }> {}

export class Category extends React.Component<ICategoryProps> {
  componentDidMount() {
    this.props.getEntities();
  }

  render() {
    const { categoryList, match } = this.props;
    return (
      <div>
        <h2 id="category-heading">
          <Translate contentKey="ecolarMobileApp.category.home.title">Categories</Translate>
          <Link to={`${match.url}/new`} className="btn btn-primary float-right jh-create-entity" id="jh-create-entity">
            <FontAwesomeIcon icon="plus" />&nbsp;
            <Translate contentKey="ecolarMobileApp.category.home.createLabel">Create new Category</Translate>
          </Link>
        </h2>
        <div className="table-responsive">
          <Table responsive>
            <thead>
              <tr>
                <th>
                  <Translate contentKey="global.field.id">ID</Translate>
                </th>
                <th>
                  <Translate contentKey="ecolarMobileApp.category.name">Name</Translate>
                </th>
                <th>
                  <Translate contentKey="ecolarMobileApp.category.description">Description</Translate>
                </th>
                <th>
                  <Translate contentKey="ecolarMobileApp.category.path">Path</Translate>
                </th>
                <th>
                  <Translate contentKey="ecolarMobileApp.category.parentId">Parent Id</Translate>
                </th>
                <th>
                  <Translate contentKey="ecolarMobileApp.category.accountType">Account Type</Translate>
                </th>
                <th>
                  <Translate contentKey="ecolarMobileApp.category.parent">Parent</Translate>
                </th>
                <th>
                  <Translate contentKey="ecolarMobileApp.category.document">Document</Translate>
                </th>
                <th />
              </tr>
            </thead>
            <tbody>
              {categoryList.map((category, i) => (
                <tr key={`entity-${i}`}>
                  <td>
                    <Button tag={Link} to={`${match.url}/${category.id}`} color="link" size="sm">
                      {category.id}
                    </Button>
                  </td>
                  <td>{category.name}</td>
                  <td>{category.description}</td>
                  <td>{category.path}</td>
                  <td>{category.parentId}</td>
                  <td>
                    <Translate contentKey={`ecolarMobileApp.AccountType.${category.accountType}`} />
                  </td>
                  <td>{category.parent ? <Link to={`category/${category.parent.id}`}>{category.parent.name}</Link> : ''}</td>
                  <td>{category.document ? <Link to={`account-categories/${category.document.id}`}>{category.document.id}</Link> : ''}</td>
                  <td className="text-right">
                    <div className="btn-group flex-btn-group-container">
                      <Button tag={Link} to={`${match.url}/${category.id}`} color="info" size="sm">
                        <FontAwesomeIcon icon="eye" />{' '}
                        <span className="d-none d-md-inline">
                          <Translate contentKey="entity.action.view">View</Translate>
                        </span>
                      </Button>
                      <Button tag={Link} to={`${match.url}/${category.id}/edit`} color="primary" size="sm">
                        <FontAwesomeIcon icon="pencil-alt" />{' '}
                        <span className="d-none d-md-inline">
                          <Translate contentKey="entity.action.edit">Edit</Translate>
                        </span>
                      </Button>
                      <Button tag={Link} to={`${match.url}/${category.id}/delete`} color="danger" size="sm">
                        <FontAwesomeIcon icon="trash" />{' '}
                        <span className="d-none d-md-inline">
                          <Translate contentKey="entity.action.delete">Delete</Translate>
                        </span>
                      </Button>
                    </div>
                  </td>
                </tr>
              ))}
            </tbody>
          </Table>
        </div>
      </div>
    );
  }
}

const mapStateToProps = ({ category }: IRootState) => ({
  categoryList: category.entities
});

const mapDispatchToProps = {
  getEntities
};

type StateProps = ReturnType<typeof mapStateToProps>;
type DispatchProps = typeof mapDispatchToProps;

export default connect(
  mapStateToProps,
  mapDispatchToProps
)(Category);

// ecolar-mobile/src/main/webapp/app/entities/category/category.vue
<template>
    <div>
        <h2 id="page-heading">
            <span v-text="$t('ecolarApp.category.home.title')" id="category-heading">Categories</span>
            <router-link to="/entity/category/new" tag="button" id="jh-create-entity" class="btn btn-primary float-right jh-create-entity create-category">
                <font-awesome-icon icon="plus"></font-awesome-icon>
                <span  v-text="$t('ecolarApp.category.home.createLabel')">
                    Create new Category
                </span>
            </router-link>
        </h2>
        <!--<jhi-alert></jhi-alert>-->
        <br/>
        <div class="table-responsive" v-if="categories">
            <table class="table table-striped">
                <thead>
                <tr>
                    <th><span v-text="$t('global.field.id')">ID</span></th>
                        <th><span v-text="$t('ecolarApp.category.name')">Name</span></th>
                        <th><span v-text="$t('ecolarApp.category.description')">Description</span></th>
                        <th><span v-text="$t('ecolarApp.category.path')">Path</span></th>
                        <th><span v-text="$t('ecolarApp.category.parentId')">Parent Id</span></th>
                        <th><span v-text="$t('ecolarApp.category.accountType')">Account Type</span></th>
                            <th><span v-text="$t('ecolarApp.category.parent')">Parent</span></th>
                            <th><span v-text="$t('ecolarApp.category.document')">Document</span></th>
                    <th></th>
                </tr>
                </thead>
                <tbody>
                <tr v-for="category in categories">
                    <td><router-link :to="{name: 'CategoryView', params: {categoryId: category.id}}">{{category.id}}</router-link></td>
                            <td>{{category.name}}</td>
                            <td>{{category.description}}</td>
                            <td>{{category.path}}</td>
                            <td>{{category.parentId}}</td>
                            <td v-text="$t('ecolarApp.AccountType.' + category.accountType)">{{category.accountType}}</td>
                        <td>
                                        <div v-if="category.parent">
                                            <router-link :to="'../category/' + category.parent.id + '/View'" >{{category.parent.name}}</router-link>
                                        </div>
                        </td>
                        <td>
                                        <div v-if="category.document">
                                            <router-link :to="'../account-categories/' + category.document.id + '/View'" >{{category.document.id}}</router-link>
                                        </div>
                        </td>
                    <td class="text-right">
                        <div class="btn-group flex-btn-group-container">
                            <router-link :to="{name: 'CategoryView', params: {categoryId: category.id}}" tag="button" class="btn btn-info btn-sm">
                                <font-awesome-icon icon="eye"></font-awesome-icon>
                                <span class="d-none d-md-inline" v-text="$t('entity.action.view')">View</span>
                            </router-link>
                            <router-link :to="{name: 'CategoryEdit', params: {categoryId: category.id}}"  tag="button" class="btn btn-primary btn-sm">
                                <font-awesome-icon icon="pencil-alt"></font-awesome-icon>
                                <span class="d-none d-md-inline" v-text="$t('entity.action.edit')">Edit</span>
                            </router-link>
                            <b-btn v-on:click="prepareRemove(category)"
                                   class="btn btn-danger btn-sm"
                                   v-b-modal.removeEntity>
                                <font-awesome-icon icon="times"></font-awesome-icon>
                                <span class="d-none d-md-inline" v-text="$t('entity.action.delete')">Delete</span>
                            </b-btn>
                        </div>
                    </td>
                </tr>
                </tbody>
            </table>
        </div>
        <b-modal ref="removeEntity" id="removeEntity" >
            <span slot="modal-title"><span id="ecolarApp.category.delete.question" v-text="$t('entity.delete.title')">Confirm delete operation</span></span>
            <div class="modal-body">
                <p id="eco-delete-category-heading" v-bind:title="$t('ecolarApp.category.delete.question')">Are you sure you want to delete this Category?</p>
            </div>
            <div slot="modal-footer">
                <button type="button" class="btn btn-secondary" v-text="$t('entity.action.cancel')" v-on:click="closeDialog()">Cancel</button>
                <button type="button" class="btn btn-primary" id="eco-confirm-delete-category" v-text="$t('entity.action.delete')" v-on:click="removeCategory()">Delete</button>
            </div>
        </b-modal>
    </div>
</template>

<script lang="ts" src="./category.component.ts">
</script>
