// ecolar-mobile/src/main/webapp/app/entities/e-account/e-account.vue
<template>
    <div>
        <h2 id="page-heading">
            <span v-text="$t('ecolarApp.eAccount.home.title')" id="e-account-heading">E Accounts</span>
            <router-link to="/entity/e-account/new" tag="button" id="jh-create-entity" class="btn btn-primary float-right jh-create-entity create-e-account">
                <font-awesome-icon icon="plus"></font-awesome-icon>
                <span  v-text="$t('ecolarApp.eAccount.home.createLabel')">
                    Create new EAccount
                </span>
            </router-link>
        </h2>
        <!--<jhi-alert></jhi-alert>-->
        <br/>
        <div class="table-responsive" v-if="eAccounts">
            <table class="table table-striped">
                <thead>
                <tr>
                    <th><span v-text="$t('global.field.id')">ID</span></th>
                        <th><span v-text="$t('ecolarApp.eAccount.accountCode')">Account Code</span></th>
                        <th><span v-text="$t('ecolarApp.eAccount.accountName')">Account Name</span></th>
                        <th><span v-text="$t('ecolarApp.eAccount.type')">Type</span></th>
                            <th><span v-text="$t('ecolarApp.eAccount.category')">Category</span></th>
                    <th></th>
                </tr>
                </thead>
                <tbody>
                <tr v-for="eAccount in eAccounts">
                    <td><router-link :to="{name: 'EAccountView', params: {eAccountId: eAccount.id}}">{{eAccount.id}}</router-link></td>
                            <td>{{eAccount.accountCode}}</td>
                            <td>{{eAccount.accountName}}</td>
                            <td v-text="$t('ecolarApp.AccountType.' + eAccount.type)">{{eAccount.type}}</td>
                        <td>
                                        <div v-if="eAccount.category">
                                            <router-link :to="'../entity/category/' + eAccount.category.id + '/view'" >{{eAccount.category.name}}</router-link>
                                        </div>
                        </td>
                    <td class="text-right">
                        <div class="btn-group flex-btn-group-container">
                            <router-link :to="{name: 'EAccountView', params: {eAccountId: eAccount.id}}" tag="button" class="btn btn-info btn-sm">
                                <font-awesome-icon icon="eye"></font-awesome-icon>
                                <span class="d-none d-md-inline" v-text="$t('entity.action.view')">View</span>
                            </router-link>
                            <router-link :to="{name: 'EAccountEdit', params: {eAccountId: eAccount.id}}"  tag="button" class="btn btn-primary btn-sm">
                                <font-awesome-icon icon="pencil-alt"></font-awesome-icon>
                                <span class="d-none d-md-inline" v-text="$t('entity.action.edit')">Edit</span>
                            </router-link>
                            <b-btn v-on:click="prepareRemove(eAccount)"
                                   class="btn btn-danger btn-sm"
                                   v-b-modal.removeEntity>
                                <font-awesome-icon icon="times"></font-awesome-icon>
                                <span class="d-none d-md-inline" v-text="$t('entity.action.delete')">Delete</span>
                            </b-btn>
                        </div>
                    </td>
                </tr>
                </tbody>
            </table>
        </div>
        <b-modal ref="removeEntity" id="removeEntity" >
            <span slot="modal-title"><span id="ecolarApp.eAccount.delete.question" v-text="$t('entity.delete.title')">Confirm delete operation</span></span>
            <div class="modal-body">
                <p id="eco-delete-eAccount-heading" v-bind:title="$t('ecolarApp.eAccount.delete.question')">Are you sure you want to delete this E Account?</p>
            </div>
            <div slot="modal-footer">
                <button type="button" class="btn btn-secondary" v-text="$t('entity.action.cancel')" v-on:click="closeDialog()">Cancel</button>
                <button type="button" class="btn btn-primary" id="eco-confirm-delete-eAccount" v-text="$t('entity.action.delete')" v-on:click="removeEAccount()">Delete</button>
            </div>
        </b-modal>
    </div>
</template>

<script lang="ts" src="./e-account.component.ts">
</script>

// ecolarMobile/src/main/webapp/app/entities/e-account/e-account.tsx
import React from 'react';
import { connect } from 'react-redux';
import { Link, RouteComponentProps } from 'react-router-dom';
import { Button, Col, Row, Table } from 'reactstrap';
// tslint:disable-next-line:no-unused-variable
import { Translate, ICrudGetAllAction } from 'react-jhipster';
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome';

import { IRootState } from 'app/shared/reducers';
import { getEntities } from './e-account.reducer';
import { IEAccount } from 'app/shared/model/e-account.model';
// tslint:disable-next-line:no-unused-variable
import { APP_DATE_FORMAT, APP_LOCAL_DATE_FORMAT } from 'app/config/constants';

export interface IEAccountProps extends StateProps, DispatchProps, RouteComponentProps<{ url: string }> {}

export class EAccount extends React.Component<IEAccountProps> {
  componentDidMount() {
    this.props.getEntities();
  }

  render() {
    const { eAccountList, match } = this.props;
    return (
      <div>
        <h2 id="e-account-heading">
          <Translate contentKey="ecolarMobileApp.eAccount.home.title">E Accounts</Translate>
          <Link to={`${match.url}/new`} className="btn btn-primary float-right jh-create-entity" id="jh-create-entity">
            <FontAwesomeIcon icon="plus" />&nbsp;
            <Translate contentKey="ecolarMobileApp.eAccount.home.createLabel">Create new E Account</Translate>
          </Link>
        </h2>
        <div className="table-responsive">
          <Table responsive>
            <thead>
              <tr>
                <th>
                  <Translate contentKey="global.field.id">ID</Translate>
                </th>
                <th>
                  <Translate contentKey="ecolarMobileApp.eAccount.accountCode">Account Code</Translate>
                </th>
                <th>
                  <Translate contentKey="ecolarMobileApp.eAccount.accountName">Account Name</Translate>
                </th>
                <th>
                  <Translate contentKey="ecolarMobileApp.eAccount.type">Type</Translate>
                </th>
                <th>
                  <Translate contentKey="ecolarMobileApp.eAccount.category">Category</Translate>
                </th>
                <th />
              </tr>
            </thead>
            <tbody>
              {eAccountList.map((eAccount, i) => (
                <tr key={`entity-${i}`}>
                  <td>
                    <Button tag={Link} to={`${match.url}/${eAccount.id}`} color="link" size="sm">
                      {eAccount.id}
                    </Button>
                  </td>
                  <td>{eAccount.accountCode}</td>
                  <td>{eAccount.accountName}</td>
                  <td>
                    <Translate contentKey={`ecolarMobileApp.AccountType.${eAccount.type}`} />
                  </td>
                  <td>{eAccount.category ? <Link to={`category/${eAccount.category.id}`}>{eAccount.category.name}</Link> : ''}</td>
                  <td className="text-right">
                    <div className="btn-group flex-btn-group-container">
                      <Button tag={Link} to={`${match.url}/${eAccount.id}`} color="info" size="sm">
                        <FontAwesomeIcon icon="eye" />{' '}
                        <span className="d-none d-md-inline">
                          <Translate contentKey="entity.action.view">View</Translate>
                        </span>
                      </Button>
                      <Button tag={Link} to={`${match.url}/${eAccount.id}/edit`} color="primary" size="sm">
                        <FontAwesomeIcon icon="pencil-alt" />{' '}
                        <span className="d-none d-md-inline">
                          <Translate contentKey="entity.action.edit">Edit</Translate>
                        </span>
                      </Button>
                      <Button tag={Link} to={`${match.url}/${eAccount.id}/delete`} color="danger" size="sm">
                        <FontAwesomeIcon icon="trash" />{' '}
                        <span className="d-none d-md-inline">
                          <Translate contentKey="entity.action.delete">Delete</Translate>
                        </span>
                      </Button>
                    </div>
                  </td>
                </tr>
              ))}
            </tbody>
          </Table>
        </div>
      </div>
    );
  }
}

const mapStateToProps = ({ eAccount }: IRootState) => ({
  eAccountList: eAccount.entities
});

const mapDispatchToProps = {
  getEntities
};

type StateProps = ReturnType<typeof mapStateToProps>;
type DispatchProps = typeof mapDispatchToProps;

export default connect(
  mapStateToProps,
  mapDispatchToProps
)(EAccount);
