// ecolar-admin/src/main/webapp/app/admin/metrics/metrics.component.ts
import { Component, OnInit } from '@angular/core';
import { NgbModal } from '@ng-bootstrap/ng-bootstrap';

import { EcoMetricsMonitoringModalComponent } from './metrics-modal.component';
import { EcoMetricsService } from './metrics.service';

@Component({
    selector: 'eco-metrics',
    templateUrl: './metrics.component.html'
})
export class EcoMetricsMonitoringComponent implements OnInit {
    metrics: any = {};
    cachesStats: any = {};
    servicesStats: any = {};
    updatingMetrics = true;
    JCACHE_KEY: string;

    constructor(private modalService: NgbModal, private metricsService: EcoMetricsService) {
        this.JCACHE_KEY = 'jcache.statistics';
    }

    ngOnInit() {
        this.refresh();
    }

    refresh() {
        this.updatingMetrics = true;
        this.metricsService.getMetrics().subscribe(metrics => {
            this.metrics = metrics;
            this.updatingMetrics = false;
            this.servicesStats = {};
            this.cachesStats = {};
            Object.keys(metrics.timers).forEach(key => {
                const value = metrics.timers[key];
                if (key.includes('web.rest') || key.includes('service')) {
                    this.servicesStats[key] = value;
                }
            });
            Object.keys(metrics.gauges).forEach(key => {
                if (key.includes('jcache.statistics')) {
                    const value = metrics.gauges[key].value;
                    // remove gets or puts
                    const index = key.lastIndexOf('.');
                    const newKey = key.substr(0, index);

                    // Keep the name of the domain
                    this.cachesStats[newKey] = {
                        name: this.JCACHE_KEY.length,
                        value
                    };
                }
            });
        });
    }

    refreshThreadDumpData() {
        this.metricsService.threadDump().subscribe(data => {
            const modalRef = this.modalService.open(EcoMetricsMonitoringModalComponent, { size: 'lg' });
            modalRef.componentInstance.threadDump = data.threads;
            modalRef.result.then(
                result => {
                    // Left blank intentionally, nothing to do here
                },
                reason => {
                    // Left blank intentionally, nothing to do here
                }
            );
        });
    }

    filterNaN(input) {
        if (isNaN(input)) {
            return 0;
        }
        return input;
    }
}

// ecolar-mobile/src/main/webapp/app/admin/metrics/metrics.component.ts
import numeral from 'numeral';
import EcoMetricsModal from './metrics-modal.vue';
import MetricsService from './metrics.service';
import { Component, Vue, Inject } from 'vue-property-decorator';

@Component({
    components: {
        'metrics-modal': EcoMetricsModal
    }
})
export default class EcoMetrics extends Vue {
    public metrics: any;
    public cachesStats: any;
    public servicesStats: any;
    public updatingMetrics: boolean;
    public JCACHE_KEY: string;
    public threads: any;
    @Inject('metricsService') private metricsService: () => MetricsService;

    constructor() {
        super();
        this.metrics = {};
        this.cachesStats = {};
        this.servicesStats = {};
        this.updatingMetrics = true;
        this.JCACHE_KEY = 'jcache.statistics';
        this.threads = null;
    }

    public mounted(): void {
        this.refresh();
    }

    public refresh(): void {
        this.updatingMetrics = true;
        this.metricsService()
            .getMetrics()
            .then(res => {
                this.metrics = res.data;
                this.updatingMetrics = false;
                this.servicesStats = {};
                this.cachesStats = {};
                Object.keys(this.metrics.timers).forEach(key => {
                    const value = this.metrics.timers[key];
                    if (key.includes('web.rest') || key.includes('service')) {
                        this.servicesStats[key] = value;
                    }
                });
                Object.keys(this.metrics.gauges).forEach(key => {
                    if (key.includes('jcache.statistics')) {
                        const value = this.metrics.gauges[key].value;
                        // remove gets or puts
                        const index = key.lastIndexOf('.');
                        const newKey = key.substr(0, index);

                        // Keep the name of the domain
                        this.cachesStats[newKey] = {
                            name: this.JCACHE_KEY.length,
                            value
                        };
                    }
                });
            });
    }

    public refreshThreadDumpData(): void {
        if ((<any>this.$refs.metricsModal).show) {
            (<any>this.$refs.metricsModal).show();
        }
        this.metricsService()
            .retrieveThreadDump()
            .then(res => {
                this.threads = res.data.threads;
            });
    }

    filterNaN(input: any): any {
        if (isNaN(input)) {
            return 0;
        }
        return input;
    }

    formatNumber1(value: any): any {
        return numeral(value).format('0,0');
    }

    formatNumber2(value: any): any {
        return numeral(value).format('0,00');
    }
}
