// ecolarAdmin/src/main/webapp/app/admin/health/health.component.ts
import { Component, OnInit } from '@angular/core';
import { NgbModal } from '@ng-bootstrap/ng-bootstrap';

import { EcoHealthService } from './health.service';
import { EcoHealthModalComponent } from './health-modal.component';

@Component({
    selector: 'eco-health',
    templateUrl: './health.component.html'
})
export class EcoHealthCheckComponent implements OnInit {
    healthData: any;
    updatingHealth: boolean;

    constructor(private modalService: NgbModal, private healthService: EcoHealthService) {}

    ngOnInit() {
        this.refresh();
    }

    baseName(name: string) {
        return this.healthService.getBaseName(name);
    }

    getBadgeClass(statusState) {
        if (statusState === 'UP') {
            return 'badge-success';
        } else {
            return 'badge-danger';
        }
    }

    refresh() {
        this.updatingHealth = true;

        this.healthService.checkHealth().subscribe(
            health => {
                this.healthData = this.healthService.transformHealthData(health);
                this.updatingHealth = false;
            },
            error => {
                if (error.status === 503) {
                    this.healthData = this.healthService.transformHealthData(error.error);
                    this.updatingHealth = false;
                }
            }
        );
    }

    showHealth(health: any) {
        const modalRef = this.modalService.open(EcoHealthModalComponent);
        modalRef.componentInstance.currentHealth = health;
        modalRef.result.then(
            result => {
                // Left blank intentionally, nothing to do here
            },
            reason => {
                // Left blank intentionally, nothing to do here
            }
        );
    }

    subSystemName(name: string) {
        return this.healthService.getSubSystemName(name);
    }
}

// ecolar-mobile/src/main/webapp/app/components/admin/health/Health.component.ts
import HealthService from './health.service';
import EcoHealthModal from './health-modal.vue';
import { Component, Inject, Vue } from 'vue-property-decorator';

@Component({
  components: {
    'health-modal': EcoHealthModal
  }
})
export default class EcoHealth extends Vue {
  public healthData: any;
  public currentHealth: any;
  public updatingHealth: boolean;
  @Inject('healthService') private healthService: () => HealthService;

  constructor() {
    super();
    this.healthData = null;
    this.currentHealth = null;
    this.updatingHealth = false;
  }

  public mounted(): void {
    this.refresh();
  }

  public baseName(name: any): any {
    return this.healthService().getBaseName(name);
  }

  public getBadgeClass(statusState: any): String {
    if (statusState === 'UP') {
      return 'badge-success';
    } else {
      return 'badge-danger';
    }
  }

  public refresh(): void {
    this.updatingHealth = true;
    this.healthService()
      .checkHealth()
      .then(res => {
        this.healthData = this.healthService().transformHealthData(res.data);
        this.updatingHealth = false;
      })
      .catch(error => {
        if (error.status === 503) {
          this.healthData = this.healthService().transformHealthData(error.error);
        }
        this.updatingHealth = false;
      });
  }

  public showHealth(health: any): void {
    this.currentHealth = health;
    (<any>this.$refs.healthModal).show();
  }

  public subSystemName(name: String): String {
    return this.healthService().getSubSystemName(name);
  }
}
