// ecolar-admin/src/main/webapp/app/admin/health/health-modal.component.ts
import { Component } from '@angular/core';
import { NgbActiveModal } from '@ng-bootstrap/ng-bootstrap';

import { EcoHealthService } from './health.service';

@Component({
    selector: 'eco-health-modal',
    templateUrl: './health-modal.component.html'
})
export class EcoHealthModalComponent {
    currentHealth: any;

    constructor(private healthService: EcoHealthService, public activeModal: NgbActiveModal) {}

    baseName(name) {
        return this.healthService.getBaseName(name);
    }

    subSystemName(name) {
        return this.healthService.getSubSystemName(name);
    }

    readableValue(value: number) {
        if (this.currentHealth.name === 'diskSpace') {
            // Should display storage space in an human readable unit
            const val = value / 1073741824;
            if (val > 1) {
                // Value
                return val.toFixed(2) + ' GB';
            } else {
                return (value / 1048576).toFixed(2) + ' MB';
            }
        }

        if (typeof value === 'object') {
            return JSON.stringify(value);
        } else {
            return value.toString();
        }
    }
}

// ecolar-mobile/src/main/webapp/app/components/admin/health/HealthModal.vue
<template>
    <div class="modal-body pad">
        <div v-if="currentHealth && currentHealth.details">
            <h5 v-text="$t('health.details.properties')">Properties</h5>
            <div class="table-responsive">
                <table class="table table-striped">
                    <thead>
                    <tr>
                        <th class="text-left" v-text="$t('health.details.name')">Name</th>
                        <th class="text-left" v-text="$t('health.details.value')">Value</th>
                    </tr>
                    </thead>
                    <tbody>
                    <tr v-for="(item, index) in currentHealth.details.details">
                        <td class="text-left">{{index}}</td>
                        <td class="text-left">{{readableValue(item)}}</td>
                    </tr>
                    </tbody>
                </table>
            </div>
        </div>
        <div v-if="currentHealth && currentHealth.error">
            <h4 v-text="$t('health.details.error')">Error</h4>
            <pre>{{currentHealth.error}}</pre>
        </div>
    </div>
</template>

<script>
    import HealthService from './HealthService.vue';

    const EcoHealthModal = {
        name: 'EcoHealthModal',
        mixins: [HealthService],
        props: ['currentHealth'],
        methods: {
            baseName(name) {
                return this.getBaseName(name);
            },
            subSystemName(name) {
                return this.getSubSystemName(name);
            },
            readableValue(value) {
                if (this.currentHealth.name === 'diskSpace') {
                    // Should display storage space in an human readable unit
                    const val = value / 1073741824;
                    if (val > 1) { // Value
                        return val.toFixed(2) + ' GB';
                    } else {
                        return (value / 1048576).toFixed(2) + ' MB';
                    }
                }

                if (typeof value === 'object') {
                    return JSON.stringify(value);
                } else {
                    return value.toString();
                }
            }
        }
    };

    export default EcoHealthModal;
</script>

<style scoped>

</style>
