// ecolar-mobile/src/main/webapp/app/entities/user-preferences/user-preferences.vue
<template>
    <div>
        <h2 id="page-heading">
            <span v-text="$t('ecolarApp.userPreferences.home.title')" id="user-preferences-heading">User Preferences</span>
            <router-link to="/entity/user-preferences/new" tag="button" id="jh-create-entity" class="btn btn-primary float-right jh-create-entity create-user-preferences">
                <font-awesome-icon icon="plus"></font-awesome-icon>
                <span  v-text="$t('ecolarApp.userPreferences.home.createLabel')">
                    Create new UserPreferences
                </span>
            </router-link>
        </h2>
        <!--<jhi-alert></jhi-alert>-->
        <br/>
        <div class="table-responsive" v-if="userPreferences">
            <table class="table table-striped">
                <thead>
                <tr>
                    <th><span v-text="$t('global.field.id')">ID</span></th>
                            <th><span v-text="$t('ecolarApp.userPreferences.user')">User</span></th>
                    <th></th>
                </tr>
                </thead>
                <tbody>
                <tr v-for="userPreferences in userPreferences">
                    <td><router-link :to="{name: 'UserPreferencesView', params: {userPreferencesId: userPreferences.id}}">{{userPreferences.id}}</router-link></td>
                        <td>
                                        {{userPreferences.user.login}}
                        </td>
                    <td class="text-right">
                        <div class="btn-group flex-btn-group-container">
                            <router-link :to="{name: 'UserPreferencesView', params: {userPreferencesId: userPreferences.id}}" tag="button" class="btn btn-info btn-sm">
                                <font-awesome-icon icon="eye"></font-awesome-icon>
                                <span class="d-none d-md-inline" v-text="$t('entity.action.view')">View</span>
                            </router-link>
                            <router-link :to="{name: 'UserPreferencesEdit', params: {userPreferencesId: userPreferences.id}}"  tag="button" class="btn btn-primary btn-sm">
                                <font-awesome-icon icon="pencil-alt"></font-awesome-icon>
                                <span class="d-none d-md-inline" v-text="$t('entity.action.edit')">Edit</span>
                            </router-link>
                            <b-btn v-on:click="prepareRemove(userPreferences)"
                                   class="btn btn-danger btn-sm"
                                   v-b-modal.removeEntity>
                                <font-awesome-icon icon="times"></font-awesome-icon>
                                <span class="d-none d-md-inline" v-text="$t('entity.action.delete')">Delete</span>
                            </b-btn>
                        </div>
                    </td>
                </tr>
                </tbody>
            </table>
        </div>
        <b-modal ref="removeEntity" id="removeEntity" >
            <span slot="modal-title"><span id="ecolarApp.userPreferences.delete.question" v-text="$t('entity.delete.title')">Confirm delete operation</span></span>
            <div class="modal-body">
                <p id="eco-delete-userPreferences-heading" v-bind:title="$t('ecolarApp.userPreferences.delete.question')">Are you sure you want to delete this User Preferences?</p>
            </div>
            <div slot="modal-footer">
                <button type="button" class="btn btn-secondary" v-text="$t('entity.action.cancel')" v-on:click="closeDialog()">Cancel</button>
                <button type="button" class="btn btn-primary" id="eco-confirm-delete-userPreferences" v-text="$t('entity.action.delete')" v-on:click="removeUserPreferences()">Delete</button>
            </div>
        </b-modal>
    </div>
</template>

<script lang="ts" src="./user-preferences.component.ts">
</script>

// ecolarMobile/src/main/webapp/app/entities/user-preferences/user-preferences.tsx
import React from 'react';
import { connect } from 'react-redux';
import { Link, RouteComponentProps } from 'react-router-dom';
import { Button, Col, Row, Table } from 'reactstrap';
// tslint:disable-next-line:no-unused-variable
import { Translate, ICrudGetAllAction } from 'react-jhipster';
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome';

import { IRootState } from 'app/shared/reducers';
import { getEntities } from './user-preferences.reducer';
import { IUserPreferences } from 'app/shared/model/user-preferences.model';
// tslint:disable-next-line:no-unused-variable
import { APP_DATE_FORMAT, APP_LOCAL_DATE_FORMAT } from 'app/config/constants';

export interface IUserPreferencesProps extends StateProps, DispatchProps, RouteComponentProps<{ url: string }> {}

export class UserPreferences extends React.Component<IUserPreferencesProps> {
  componentDidMount() {
    this.props.getEntities();
  }

  render() {
    const { userPreferencesList, match } = this.props;
    return (
      <div>
        <h2 id="user-preferences-heading">
          <Translate contentKey="ecolarMobileApp.userPreferences.home.title">User Preferences</Translate>
          <Link to={`${match.url}/new`} className="btn btn-primary float-right jh-create-entity" id="jh-create-entity">
            <FontAwesomeIcon icon="plus" />&nbsp;
            <Translate contentKey="ecolarMobileApp.userPreferences.home.createLabel">Create new User Preferences</Translate>
          </Link>
        </h2>
        <div className="table-responsive">
          <Table responsive>
            <thead>
              <tr>
                <th>
                  <Translate contentKey="global.field.id">ID</Translate>
                </th>
                <th>
                  <Translate contentKey="ecolarMobileApp.userPreferences.user">User</Translate>
                </th>
                <th />
              </tr>
            </thead>
            <tbody>
              {userPreferencesList.map((userPreferences, i) => (
                <tr key={`entity-${i}`}>
                  <td>
                    <Button tag={Link} to={`${match.url}/${userPreferences.id}`} color="link" size="sm">
                      {userPreferences.id}
                    </Button>
                  </td>
                  <td>{userPreferences.user ? userPreferences.user.login : ''}</td>
                  <td className="text-right">
                    <div className="btn-group flex-btn-group-container">
                      <Button tag={Link} to={`${match.url}/${userPreferences.id}`} color="info" size="sm">
                        <FontAwesomeIcon icon="eye" />{' '}
                        <span className="d-none d-md-inline">
                          <Translate contentKey="entity.action.view">View</Translate>
                        </span>
                      </Button>
                      <Button tag={Link} to={`${match.url}/${userPreferences.id}/edit`} color="primary" size="sm">
                        <FontAwesomeIcon icon="pencil-alt" />{' '}
                        <span className="d-none d-md-inline">
                          <Translate contentKey="entity.action.edit">Edit</Translate>
                        </span>
                      </Button>
                      <Button tag={Link} to={`${match.url}/${userPreferences.id}/delete`} color="danger" size="sm">
                        <FontAwesomeIcon icon="trash" />{' '}
                        <span className="d-none d-md-inline">
                          <Translate contentKey="entity.action.delete">Delete</Translate>
                        </span>
                      </Button>
                    </div>
                  </td>
                </tr>
              ))}
            </tbody>
          </Table>
        </div>
      </div>
    );
  }
}

const mapStateToProps = ({ userPreferences }: IRootState) => ({
  userPreferencesList: userPreferences.entities
});

const mapDispatchToProps = {
  getEntities
};

type StateProps = ReturnType<typeof mapStateToProps>;
type DispatchProps = typeof mapDispatchToProps;

export default connect(
  mapStateToProps,
  mapDispatchToProps
)(UserPreferences);
