// ecolar-mobile/src/main/webapp/app/entities/movement/movement-update.vue
<template>
    <div class="row justify-content-center">
        <div class="col-8">
            <form name="editForm" role="form" novalidate v-on:submit.prevent="save()" >
                <h2 id="ecolarApp.movement.home.createOrEditLabel" v-text="$t('ecolarApp.movement.home.createOrEditLabel')">Create or edit a Movement</h2>
                <div>
                    <!--<jhi-alert-error></jhi-alert-error>-->
                    <div class="form-group" v-if="movement.id">
                        <label for="id" v-text="$t('global.field.id')">ID</label>
                        <input type="text" class="form-control" id="id" name="id"
                               v-model="movement.id" readonly />
                    </div>

                    <div class="form-group">
                        <label class="form-control-label" v-text="$t('ecolarApp.movement.eventTime')" for="movement-eventTime">Event Time</label>
                        <div class="d-flex">
                            <input id="movement-eventTime" type="datetime-local" class="form-control" name="eventTime" :class="{'valid': !$v.movement.eventTime.$invalid, 'invalid': $v.movement.eventTime.$invalid }" v-model="$v.movement.eventTime.$model" />
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="form-control-label" v-text="$t('ecolarApp.movement.registrationTime')" for="movement-registrationTime">Registration Time</label>
                        <div class="d-flex">
                            <input id="movement-registrationTime" type="datetime-local" class="form-control" name="registrationTime" :class="{'valid': !$v.movement.registrationTime.$invalid, 'invalid': $v.movement.registrationTime.$invalid }" v-model="$v.movement.registrationTime.$model" />
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="form-control-label" v-text="$t('ecolarApp.movement.amount')" for="movement-amount">Amount</label>
                        <input type="number" class="form-control" name="amount" id="movement-amount"
                            :class="{'valid': !$v.movement.amount.$invalid, 'invalid': $v.movement.amount.$invalid }" v-model="$v.movement.amount.$model" />
                    </div>
                    <div class="form-group">
                        <label class="form-control-label" v-text="$t('ecolarApp.movement.location')" for="movement-location">Location</label>
                        <input type="text" class="form-control" name="location" id="movement-location"
                            :class="{'valid': !$v.movement.location.$invalid, 'invalid': $v.movement.location.$invalid }" v-model="$v.movement.location.$model" />
                    </div>

                        <div class="form-group">
                            <label v-text="$t('ecolarApp.movement.eventLines')" for="movement-eventLines">Event Lines</label>
                            <select class="form-control" id="movement-eventLines" multiple name="eventLines" v-model="movement.eventLines">
                                <option v-bind:value="getSelected(movement.eventLines, movementLineOption)" v-for="movementLineOption in movementLines">{{movementLineOption.id}}</option>
                            </select>
                        </div>

                </div>
                <div>
                    <button type="button" id="cancel-save" class="btn btn-secondary" v-on:click="previousState()">
                        <font-awesome-icon icon="ban"></font-awesome-icon>&nbsp;<span v-text="$t('entity.action.cancel')">Cancel</span>
                    </button>
                    <button type="submit" id="save-entity" :disabled="$v.movement.$invalid || isSaving" class="btn btn-primary">
                        <font-awesome-icon icon="save"></font-awesome-icon>&nbsp;<span v-text="$t('entity.action.save')">Save</span>
                    </button>
                </div>
            </form>
        </div>
    </div>
</template>
<script lang="ts" src="./movement-update.component.ts">
</script>

// ecolarAdmin/src/main/webapp/app/entities/movement/movement-update.component.ts
import { Component, OnInit } from '@angular/core';
import { ActivatedRoute } from '@angular/router';
import { HttpResponse, HttpErrorResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import * as moment from 'moment';
import { DATE_TIME_FORMAT } from 'app/shared/constants/input.constants';
import { JhiAlertService } from 'ng-jhipster';

import { IMovement } from 'app/shared/model/movement.model';
import { MovementService } from './movement.service';
import { IMovementLine } from 'app/shared/model/movement-line.model';
import { MovementLineService } from 'app/entities/movement-line';

@Component({
    selector: 'eco-movement-update',
    templateUrl: './movement-update.component.html'
})
export class MovementUpdateComponent implements OnInit {
    movement: IMovement;
    isSaving: boolean;

    movementlines: IMovementLine[];
    eventTime: string;
    registrationTime: string;

    constructor(
        private jhiAlertService: JhiAlertService,
        private movementService: MovementService,
        private movementLineService: MovementLineService,
        private activatedRoute: ActivatedRoute
    ) {}

    ngOnInit() {
        this.isSaving = false;
        this.activatedRoute.data.subscribe(({ movement }) => {
            this.movement = movement;
            this.eventTime = this.movement.eventTime != null ? this.movement.eventTime.format(DATE_TIME_FORMAT) : null;
            this.registrationTime = this.movement.registrationTime != null ? this.movement.registrationTime.format(DATE_TIME_FORMAT) : null;
        });
        this.movementLineService.query().subscribe(
            (res: HttpResponse<IMovementLine[]>) => {
                this.movementlines = res.body;
            },
            (res: HttpErrorResponse) => this.onError(res.message)
        );
    }

    previousState() {
        window.history.back();
    }

    save() {
        this.isSaving = true;
        this.movement.eventTime = this.eventTime != null ? moment(this.eventTime, DATE_TIME_FORMAT) : null;
        this.movement.registrationTime = this.registrationTime != null ? moment(this.registrationTime, DATE_TIME_FORMAT) : null;
        if (this.movement.id !== undefined) {
            this.subscribeToSaveResponse(this.movementService.update(this.movement));
        } else {
            this.subscribeToSaveResponse(this.movementService.create(this.movement));
        }
    }

    private subscribeToSaveResponse(result: Observable<HttpResponse<IMovement>>) {
        result.subscribe((res: HttpResponse<IMovement>) => this.onSaveSuccess(), (res: HttpErrorResponse) => this.onSaveError());
    }

    private onSaveSuccess() {
        this.isSaving = false;
        this.previousState();
    }

    private onSaveError() {
        this.isSaving = false;
    }

    private onError(errorMessage: string) {
        this.jhiAlertService.error(errorMessage, null, null);
    }

    trackMovementLineById(index: number, item: IMovementLine) {
        return item.id;
    }

    getSelected(selectedVals: Array<any>, option: any) {
        if (selectedVals) {
            for (let i = 0; i < selectedVals.length; i++) {
                if (option.id === selectedVals[i].id) {
                    return selectedVals[i];
                }
            }
        }
        return option;
    }
}

<div class="row justify-content-center">
    <div class="col-8">
        <form name="editForm" role="form" novalidate (ngSubmit)="save()" #editForm="ngForm">
            <h2 id="eco-movement-heading" jhiTranslate="ecolarAdminApp.movement.home.createOrEditLabel">Create or edit a Movement</h2>
            <div>
                <eco-alert-error></eco-alert-error>
                <div class="form-group" [hidden]="!movement.id">
                    <label for="id" jhiTranslate="global.field.id">ID</label>
                    <input type="text" class="form-control" id="id" name="id"
                        [(ngModel)]="movement.id" readonly />
                </div>
                <div class="form-group">
                    <label class="form-control-label" jhiTranslate="ecolarAdminApp.movement.eventTime" for="field_eventTime">Event Time</label>
                    <div class="d-flex">
                        <input id="field_eventTime" type="datetime-local" class="form-control" name="eventTime" [(ngModel)]="eventTime"
                        />
                    </div>
                </div>
                <div class="form-group">
                    <label class="form-control-label" jhiTranslate="ecolarAdminApp.movement.registrationTime" for="field_registrationTime">Registration Time</label>
                    <div class="d-flex">
                        <input id="field_registrationTime" type="datetime-local" class="form-control" name="registrationTime" [(ngModel)]="registrationTime"
                        />
                    </div>
                </div>
                <div class="form-group">
                    <label class="form-control-label" jhiTranslate="ecolarAdminApp.movement.amount" for="field_amount">Amount</label>
                    <input type="number" class="form-control" name="amount" id="field_amount"
                        [(ngModel)]="movement.amount" />
                </div>
                <div class="form-group">
                    <label class="form-control-label" jhiTranslate="ecolarAdminApp.movement.location" for="field_location">Location</label>
                    <input type="text" class="form-control" name="location" id="field_location"
                        [(ngModel)]="movement.location" />
                </div>

                <div class="form-group">
                    <label jhiTranslate="ecolarAdminApp.movement.eventLines" for="field_eventLines">Event Lines</label>
                    <select class="form-control" id="field_eventLines" multiple name="eventLines" [(ngModel)]="movement.eventLines">
                        <option [ngValue]="getSelected(movement.eventLines, movementLineOption)" *ngFor="let movementLineOption of movementlines; trackBy: trackMovementLineById">{{movementLineOption.id}}</option>
                    </select>
                </div>
            </div>
            <div>
                <button type="button" id="cancel-save" class="btn btn-secondary"  (click)="previousState()">
                    <fa-icon [icon]="'ban'"></fa-icon>&nbsp;<span jhiTranslate="entity.action.cancel">Cancel</span>
                </button>
                <button type="submit" id="save-entity" [disabled]="editForm.form.invalid || isSaving" class="btn btn-primary">
                    <fa-icon [icon]="'save'"></fa-icon>&nbsp;<span jhiTranslate="entity.action.save">Save</span>
                </button>
            </div>
        </form>
    </div>
</div>
