// ecolarAdmin/src/main/webapp/app/entities/movement-line/movement-line.component.ts
import { Component, OnInit, OnDestroy } from '@angular/core';
import { HttpErrorResponse, HttpResponse } from '@angular/common/http';
import { Subscription } from 'rxjs';
import { JhiEventManager, JhiAlertService } from 'ng-jhipster';

import { IMovementLine } from 'app/shared/model/movement-line.model';
import { Principal } from 'app/core';
import { MovementLineService } from './movement-line.service';

@Component({
    selector: 'eco-movement-line',
    templateUrl: './movement-line.component.html'
})
export class MovementLineComponent implements OnInit, OnDestroy {
    movementLines: IMovementLine[];
    currentAccount: any;
    eventSubscriber: Subscription;

    constructor(
        private movementLineService: MovementLineService,
        private jhiAlertService: JhiAlertService,
        private eventManager: JhiEventManager,
        private principal: Principal
    ) {}

    loadAll() {
        this.movementLineService.query().subscribe(
            (res: HttpResponse<IMovementLine[]>) => {
                this.movementLines = res.body;
            },
            (res: HttpErrorResponse) => this.onError(res.message)
        );
    }

    ngOnInit() {
        this.loadAll();
        this.principal.identity().then(account => {
            this.currentAccount = account;
        });
        this.registerChangeInMovementLines();
    }

    ngOnDestroy() {
        this.eventManager.destroy(this.eventSubscriber);
    }

    trackId(index: number, item: IMovementLine) {
        return item.id;
    }

    registerChangeInMovementLines() {
        this.eventSubscriber = this.eventManager.subscribe('movementLineListModification', response => this.loadAll());
    }

    private onError(errorMessage: string) {
        this.jhiAlertService.error(errorMessage, null, null);
    }
}

<div>
    <h2 id="page-heading">
        <span jhiTranslate="ecolarAdminApp.movementLine.home.title">Movement Lines</span>
        <button id="jh-create-entity" class="btn btn-primary float-right jh-create-entity create-movement-line" [routerLink]="['/movement-line/new']">
            <fa-icon [icon]="'plus'"></fa-icon>
            <span  jhiTranslate="ecolarAdminApp.movementLine.home.createLabel">
            Create new Movement Line
            </span>
        </button>
    </h2>
    <eco-alert></eco-alert>
    <br/>
    <div class="table-responsive" *ngIf="movementLines">
        <table class="table table-striped">
            <thead>
            <tr>
            <th><span jhiTranslate="global.field.id">ID</span></th>
            <th><span jhiTranslate="ecolarAdminApp.movementLine.amount">Amount</span></th>
            <th><span jhiTranslate="ecolarAdminApp.movementLine.eventType">Event Type</span></th>
            <th><span jhiTranslate="ecolarAdminApp.movementLine.account">Account</span></th>
            <th></th>
            </tr>
            </thead>
            <tbody>
            <tr *ngFor="let movementLine of movementLines ;trackBy: trackId">
                <td><a [routerLink]="['/movement-line', movementLine.id, 'view' ]">{{movementLine.id}}</a></td>
                <td>{{movementLine.amount}}</td>
                <td jhiTranslate="{{'ecolarAdminApp.LineType.' + movementLine.eventType}}">{{movementLine.eventType}}</td>
                <td>
                    <div *ngIf="movementLine.account">
                        <a [routerLink]="['../e-account', movementLine.account?.id, 'view' ]" >{{movementLine.account?.accountName}}</a>
                    </div>
                </td>
                <td class="text-right">
                    <div class="btn-group flex-btn-group-container">
                        <button type="submit"
                                [routerLink]="['/movement-line', movementLine.id, 'view' ]"
                                class="btn btn-info btn-sm">
                            <fa-icon [icon]="'eye'"></fa-icon>
                            <span class="d-none d-md-inline" jhiTranslate="entity.action.view">View</span>
                        </button>
                        <button type="submit"
                                [routerLink]="['/movement-line', movementLine.id, 'edit']"
                                class="btn btn-primary btn-sm">
                            <fa-icon [icon]="'pencil-alt'"></fa-icon>
                            <span class="d-none d-md-inline" jhiTranslate="entity.action.edit">Edit</span>
                        </button>
                        <button type="submit"
                                [routerLink]="['/', { outlets: { popup: 'movement-line/'+ movementLine.id + '/delete'} }]"
                                replaceUrl="true"
                                queryParamsHandling="merge"
                                class="btn btn-danger btn-sm">
                            <fa-icon [icon]="'times'"></fa-icon>
                            <span class="d-none d-md-inline" jhiTranslate="entity.action.delete">Delete</span>
                        </button>
                    </div>
                </td>
            </tr>
            </tbody>
        </table>
    </div>
</div>

// ecolar-mobile/src/main/webapp/app/entities/movement-line/movement-line.vue
<template>
    <div>
        <h2 id="page-heading">
            <span v-text="$t('ecolarApp.movementLine.home.title')" id="movement-line-heading">Movement Lines</span>
            <router-link to="/entity/movement-line/new" tag="button" id="jh-create-entity" class="btn btn-primary float-right jh-create-entity create-movement-line">
                <font-awesome-icon icon="plus"></font-awesome-icon>
                <span  v-text="$t('ecolarApp.movementLine.home.createLabel')">
                    Create new MovementLine
                </span>
            </router-link>
        </h2>
        <!--<jhi-alert></jhi-alert>-->
        <br/>
        <div class="table-responsive" v-if="movementLines">
            <table class="table table-striped">
                <thead>
                <tr>
                    <th><span v-text="$t('global.field.id')">ID</span></th>
                        <th><span v-text="$t('ecolarApp.movementLine.amount')">Amount</span></th>
                        <th><span v-text="$t('ecolarApp.movementLine.eventType')">Event Type</span></th>
                            <th><span v-text="$t('ecolarApp.movementLine.account')">Account</span></th>
                    <th></th>
                </tr>
                </thead>
                <tbody>
                <tr v-for="movementLine in movementLines">
                    <td><router-link :to="{name: 'MovementLineView', params: {movementLineId: movementLine.id}}">{{movementLine.id}}</router-link></td>
                            <td>{{movementLine.amount}}</td>
                            <td v-text="$t('ecolarApp.LineType.' + movementLine.eventType)">{{movementLine.eventType}}</td>
                        <td>
                                        <div v-if="movementLine.account">
                                            <router-link :to="'../entity/e-account/' + movementLine.account.id + '/view'" >{{movementLine.account.accountName}}</router-link>
                                        </div>
                        </td>
                    <td class="text-right">
                        <div class="btn-group flex-btn-group-container">
                            <router-link :to="{name: 'MovementLineView', params: {movementLineId: movementLine.id}}" tag="button" class="btn btn-info btn-sm">
                                <font-awesome-icon icon="eye"></font-awesome-icon>
                                <span class="d-none d-md-inline" v-text="$t('entity.action.view')">View</span>
                            </router-link>
                            <router-link :to="{name: 'MovementLineEdit', params: {movementLineId: movementLine.id}}"  tag="button" class="btn btn-primary btn-sm">
                                <font-awesome-icon icon="pencil-alt"></font-awesome-icon>
                                <span class="d-none d-md-inline" v-text="$t('entity.action.edit')">Edit</span>
                            </router-link>
                            <b-btn v-on:click="prepareRemove(movementLine)"
                                   class="btn btn-danger btn-sm"
                                   v-b-modal.removeEntity>
                                <font-awesome-icon icon="times"></font-awesome-icon>
                                <span class="d-none d-md-inline" v-text="$t('entity.action.delete')">Delete</span>
                            </b-btn>
                        </div>
                    </td>
                </tr>
                </tbody>
            </table>
        </div>
        <b-modal ref="removeEntity" id="removeEntity" >
            <span slot="modal-title"><span id="ecolarApp.movementLine.delete.question" v-text="$t('entity.delete.title')">Confirm delete operation</span></span>
            <div class="modal-body">
                <p id="eco-delete-movementLine-heading" v-bind:title="$t('ecolarApp.movementLine.delete.question')">Are you sure you want to delete this Movement Line?</p>
            </div>
            <div slot="modal-footer">
                <button type="button" class="btn btn-secondary" v-text="$t('entity.action.cancel')" v-on:click="closeDialog()">Cancel</button>
                <button type="button" class="btn btn-primary" id="eco-confirm-delete-movementLine" v-text="$t('entity.action.delete')" v-on:click="removeMovementLine()">Delete</button>
            </div>
        </b-modal>
    </div>
</template>

<script lang="ts" src="./movement-line.component.ts">
</script>
