// ecolarAdmin/src/main/webapp/app/entities/movement-line/movement-line-update.component.ts
import { Component, OnInit } from '@angular/core';
import { ActivatedRoute } from '@angular/router';
import { HttpResponse, HttpErrorResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { JhiAlertService } from 'ng-jhipster';

import { IMovementLine } from 'app/shared/model/movement-line.model';
import { MovementLineService } from './movement-line.service';
import { IEAccount } from 'app/shared/model/e-account.model';
import { EAccountService } from 'app/entities/e-account';

@Component({
    selector: 'eco-movement-line-update',
    templateUrl: './movement-line-update.component.html'
})
export class MovementLineUpdateComponent implements OnInit {
    movementLine: IMovementLine;
    isSaving: boolean;

    eaccounts: IEAccount[];

    constructor(
        private jhiAlertService: JhiAlertService,
        private movementLineService: MovementLineService,
        private eAccountService: EAccountService,
        private activatedRoute: ActivatedRoute
    ) {}

    ngOnInit() {
        this.isSaving = false;
        this.activatedRoute.data.subscribe(({ movementLine }) => {
            this.movementLine = movementLine;
        });
        this.eAccountService.query().subscribe(
            (res: HttpResponse<IEAccount[]>) => {
                this.eaccounts = res.body;
            },
            (res: HttpErrorResponse) => this.onError(res.message)
        );
    }

    previousState() {
        window.history.back();
    }

    save() {
        this.isSaving = true;
        if (this.movementLine.id !== undefined) {
            this.subscribeToSaveResponse(this.movementLineService.update(this.movementLine));
        } else {
            this.subscribeToSaveResponse(this.movementLineService.create(this.movementLine));
        }
    }

    private subscribeToSaveResponse(result: Observable<HttpResponse<IMovementLine>>) {
        result.subscribe((res: HttpResponse<IMovementLine>) => this.onSaveSuccess(), (res: HttpErrorResponse) => this.onSaveError());
    }

    private onSaveSuccess() {
        this.isSaving = false;
        this.previousState();
    }

    private onSaveError() {
        this.isSaving = false;
    }

    private onError(errorMessage: string) {
        this.jhiAlertService.error(errorMessage, null, null);
    }

    trackEAccountById(index: number, item: IEAccount) {
        return item.id;
    }
}

<div class="row justify-content-center">
    <div class="col-8">
        <form name="editForm" role="form" novalidate (ngSubmit)="save()" #editForm="ngForm">
            <h2 id="eco-movement-line-heading" jhiTranslate="ecolarAdminApp.movementLine.home.createOrEditLabel">Create or edit a Movement Line</h2>
            <div>
                <eco-alert-error></eco-alert-error>
                <div class="form-group" [hidden]="!movementLine.id">
                    <label for="id" jhiTranslate="global.field.id">ID</label>
                    <input type="text" class="form-control" id="id" name="id"
                        [(ngModel)]="movementLine.id" readonly />
                </div>
                <div class="form-group">
                    <label class="form-control-label" jhiTranslate="ecolarAdminApp.movementLine.amount" for="field_amount">Amount</label>
                    <input type="number" class="form-control" name="amount" id="field_amount"
                        [(ngModel)]="movementLine.amount" />
                </div>
                <div class="form-group">
                    <label class="form-control-label" jhiTranslate="ecolarAdminApp.movementLine.eventType" for="field_eventType">Event Type</label>
                    <select class="form-control" name="eventType" [(ngModel)]="movementLine.eventType" id="field_eventType" >
                        <option value="CREDIT">{{'ecolarAdminApp.LineType.CREDIT' | translate}}</option>
                        <option value="DEBIT">{{'ecolarAdminApp.LineType.DEBIT' | translate}}</option>
                    </select>
                </div>

                <div class="form-group">
                    <label class="form-control-label" jhiTranslate="ecolarAdminApp.movementLine.account" for="field_account">Account</label>
                    <select class="form-control" id="field_account" name="account" [(ngModel)]="movementLine.account" >
                        <option [ngValue]="null"></option>
                        <option [ngValue]="eAccountOption.id === movementLine.account?.id ? movementLine.account : eAccountOption" *ngFor="let eAccountOption of eaccounts; trackBy: trackEAccountById">{{eAccountOption.accountName}}</option>
                    </select>
                </div>
            </div>
            <div>
                <button type="button" id="cancel-save" class="btn btn-secondary"  (click)="previousState()">
                    <fa-icon [icon]="'ban'"></fa-icon>&nbsp;<span jhiTranslate="entity.action.cancel">Cancel</span>
                </button>
                <button type="submit" id="save-entity" [disabled]="editForm.form.invalid || isSaving" class="btn btn-primary">
                    <fa-icon [icon]="'save'"></fa-icon>&nbsp;<span jhiTranslate="entity.action.save">Save</span>
                </button>
            </div>
        </form>
    </div>
</div>

// ecolar-mobile/src/main/webapp/app/entities/movement-line/movement-line-update.vue
<template>
    <div class="row justify-content-center">
        <div class="col-8">
            <form name="editForm" role="form" novalidate v-on:submit.prevent="save()" >
                <h2 id="ecolarApp.movementLine.home.createOrEditLabel" v-text="$t('ecolarApp.movementLine.home.createOrEditLabel')">Create or edit a MovementLine</h2>
                <div v-if="movementLine">
                    <!--<jhi-alert-error></jhi-alert-error>-->
                    <div class="form-group" v-if="movementLine.id">
                        <label for="id" v-text="$t('global.field.id')">ID</label>
                        <input type="text" class="form-control" id="id" name="id"
                               v-model="movementLine.id" readonly />
                    </div>

                    <div class="form-group">
                        <label class="form-control-label" v-text="$t('ecolarApp.movementLine.amount')" for="movement-line-amount">Amount</label>
                        <input type="number" class="form-control" name="amount" id="movement-line-amount"
                            :class="{'valid': !$v.movementLine.amount.$invalid, 'invalid': $v.movementLine.amount.$invalid }" v-model="$v.movementLine.amount.$model" />
                    </div>
                    <div class="form-group">
                        <label class="form-control-label" v-text="$t('ecolarApp.movementLine.eventType')" for="movement-line-eventType">Event Type</label>
                        <select class="form-control" name="eventType" :class="{'valid': !$v.movementLine.eventType.$invalid, 'invalid': $v.movementLine.eventType.$invalid }" v-model="$v.movementLine.eventType.$model" id="movement-line-eventType" >
                            <option value="CREDIT" v-bind:label="$t('ecolarApp.LineType.CREDIT')">CREDIT</option>
                            <option value="DEBIT" v-bind:label="$t('ecolarApp.LineType.DEBIT')">DEBIT</option>
                        </select>
                    </div>

                        <div class="form-group">
                            <label class="form-control-label" v-bind:value="$t('ecolarApp.movementLine.account')" for="movement-line-account">Account</label>
                                <select class="form-control" id="movement-line-account" name="account" v-model="movementLine.account" >
                                    <option value="null"></option>
                                    <option v-bind:value="movementLine.account && eAccountOption.id === movementLine.account.id ? movementLine.account : eAccountOption" v-for="eAccountOption in eAccounts">{{eAccountOption.accountName}}</option>
                                </select>
                        </div>

                </div>
                <div>
                    <button type="button" id="cancel-save" class="btn btn-secondary" v-on:click="previousState()">
                        <font-awesome-icon icon="ban"></font-awesome-icon>&nbsp;<span v-text="$t('entity.action.cancel')">Cancel</span>
                    </button>
                    <button type="submit" id="save-entity" :disabled="$v.movementLine.$invalid || isSaving" class="btn btn-primary">
                        <font-awesome-icon icon="save"></font-awesome-icon>&nbsp;<span v-text="$t('entity.action.save')">Save</span>
                    </button>
                </div>
            </form>
        </div>
    </div>
</template>
<script lang="ts" src="./movement-line-update.component.ts">
</script>
