// ecolarMobile/src/main/webapp/app/entities/account-categories/account-categories.tsx
import React from 'react';
import { connect } from 'react-redux';
import { Link, RouteComponentProps } from 'react-router-dom';
import { Button, Col, Row, Table } from 'reactstrap';
// tslint:disable-next-line:no-unused-variable
import { Translate, ICrudGetAllAction } from 'react-jhipster';
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome';

import { IRootState } from 'app/shared/reducers';
import { getEntities } from './account-categories.reducer';
import { IAccountCategories } from 'app/shared/model/account-categories.model';
// tslint:disable-next-line:no-unused-variable
import { APP_DATE_FORMAT, APP_LOCAL_DATE_FORMAT } from 'app/config/constants';

export interface IAccountCategoriesProps extends StateProps, DispatchProps, RouteComponentProps<{ url: string }> {}

export class AccountCategories extends React.Component<IAccountCategoriesProps> {
  componentDidMount() {
    this.props.getEntities();
  }

  render() {
    const { accountCategoriesList, match } = this.props;
    return (
      <div>
        <h2 id="account-categories-heading">
          <Translate contentKey="ecolarMobileApp.accountCategories.home.title">Account Categories</Translate>
          <Link to={`${match.url}/new`} className="btn btn-primary float-right jh-create-entity" id="jh-create-entity">
            <FontAwesomeIcon icon="plus" />&nbsp;
            <Translate contentKey="ecolarMobileApp.accountCategories.home.createLabel">Create new Account Categories</Translate>
          </Link>
        </h2>
        <div className="table-responsive">
          <Table responsive>
            <thead>
              <tr>
                <th>
                  <Translate contentKey="global.field.id">ID</Translate>
                </th>
                <th />
              </tr>
            </thead>
            <tbody>
              {accountCategoriesList.map((accountCategories, i) => (
                <tr key={`entity-${i}`}>
                  <td>
                    <Button tag={Link} to={`${match.url}/${accountCategories.id}`} color="link" size="sm">
                      {accountCategories.id}
                    </Button>
                  </td>
                  <td className="text-right">
                    <div className="btn-group flex-btn-group-container">
                      <Button tag={Link} to={`${match.url}/${accountCategories.id}`} color="info" size="sm">
                        <FontAwesomeIcon icon="eye" />{' '}
                        <span className="d-none d-md-inline">
                          <Translate contentKey="entity.action.view">View</Translate>
                        </span>
                      </Button>
                      <Button tag={Link} to={`${match.url}/${accountCategories.id}/edit`} color="primary" size="sm">
                        <FontAwesomeIcon icon="pencil-alt" />{' '}
                        <span className="d-none d-md-inline">
                          <Translate contentKey="entity.action.edit">Edit</Translate>
                        </span>
                      </Button>
                      <Button tag={Link} to={`${match.url}/${accountCategories.id}/delete`} color="danger" size="sm">
                        <FontAwesomeIcon icon="trash" />{' '}
                        <span className="d-none d-md-inline">
                          <Translate contentKey="entity.action.delete">Delete</Translate>
                        </span>
                      </Button>
                    </div>
                  </td>
                </tr>
              ))}
            </tbody>
          </Table>
        </div>
      </div>
    );
  }
}

const mapStateToProps = ({ accountCategories }: IRootState) => ({
  accountCategoriesList: accountCategories.entities
});

const mapDispatchToProps = {
  getEntities
};

type StateProps = ReturnType<typeof mapStateToProps>;
type DispatchProps = typeof mapDispatchToProps;

export default connect(
  mapStateToProps,
  mapDispatchToProps
)(AccountCategories);

// ecolar-mobile/src/main/webapp/app/entities/account-categories/account-categories.vue
<template>
    <div>
        <h2 id="page-heading">
            <span v-text="$t('ecolarApp.accountCategories.home.title')" id="account-categories-heading">Account Categories</span>
            <router-link to="/entity/account-categories/new" tag="button" id="jh-create-entity" class="btn btn-primary float-right jh-create-entity create-account-categories">
                <font-awesome-icon icon="plus"></font-awesome-icon>
                <span  v-text="$t('ecolarApp.accountCategories.home.createLabel')">
                    Create new AccountCategories
                </span>
            </router-link>
        </h2>
        <!--<jhi-alert></jhi-alert>-->
        <br/>
        <div class="table-responsive" v-if="accountCategories">
            <table class="table table-striped">
                <thead>
                <tr>
                    <th><span v-text="$t('global.field.id')">ID</span></th>
                    <th></th>
                </tr>
                </thead>
                <tbody>
                <tr v-for="accountCategories in accountCategories">
                    <td><router-link :to="{name: 'AccountCategoriesView', params: {accountCategoriesId: accountCategories.id}}">{{accountCategories.id}}</router-link></td>
                    <td class="text-right">
                        <div class="btn-group flex-btn-group-container">
                            <router-link :to="{name: 'AccountCategoriesView', params: {accountCategoriesId: accountCategories.id}}" tag="button" class="btn btn-info btn-sm">
                                <font-awesome-icon icon="eye"></font-awesome-icon>
                                <span class="d-none d-md-inline" v-text="$t('entity.action.view')">View</span>
                            </router-link>
                            <router-link :to="{name: 'AccountCategoriesEdit', params: {accountCategoriesId: accountCategories.id}}"  tag="button" class="btn btn-primary btn-sm">
                                <font-awesome-icon icon="pencil-alt"></font-awesome-icon>
                                <span class="d-none d-md-inline" v-text="$t('entity.action.edit')">Edit</span>
                            </router-link>
                            <b-btn v-on:click="prepareRemove(accountCategories)"
                                   class="btn btn-danger btn-sm"
                                   v-b-modal.removeEntity>
                                <font-awesome-icon icon="times"></font-awesome-icon>
                                <span class="d-none d-md-inline" v-text="$t('entity.action.delete')">Delete</span>
                            </b-btn>
                        </div>
                    </td>
                </tr>
                </tbody>
            </table>
        </div>
        <b-modal ref="removeEntity" id="removeEntity" >
            <span slot="modal-title"><span id="ecolarApp.accountCategories.delete.question" v-text="$t('entity.delete.title')">Confirm delete operation</span></span>
            <div class="modal-body">
                <p id="eco-delete-accountCategories-heading" v-bind:title="$t('ecolarApp.accountCategories.delete.question')">Are you sure you want to delete this Account Categories?</p>
            </div>
            <div slot="modal-footer">
                <button type="button" class="btn btn-secondary" v-text="$t('entity.action.cancel')" v-on:click="closeDialog()">Cancel</button>
                <button type="button" class="btn btn-primary" id="eco-confirm-delete-accountCategories" v-text="$t('entity.action.delete')" v-on:click="removeAccountCategories()">Delete</button>
            </div>
        </b-modal>
    </div>
</template>

<script lang="ts" src="./account-categories.component.ts">
</script>
