// ecolar-admin/src/main/webapp/app/entities/account-categories/account-categories-update.component.ts
import { Component, OnInit } from '@angular/core';
import { ActivatedRoute } from '@angular/router';
import { HttpResponse, HttpErrorResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { JhiAlertService } from 'ng-jhipster';

import { IAccountCategories } from 'app/shared/model/account-categories.model';
import { AccountCategoriesService } from './account-categories.service';
import { IHouseHold } from 'app/shared/model/house-hold.model';
import { HouseHoldService } from 'app/entities/house-hold';

@Component({
    selector: 'eco-account-categories-update',
    templateUrl: './account-categories-update.component.html'
})
export class AccountCategoriesUpdateComponent implements OnInit {
    accountCategories: IAccountCategories;
    isSaving: boolean;

    households: IHouseHold[];

    constructor(
        private jhiAlertService: JhiAlertService,
        private accountCategoriesService: AccountCategoriesService,
        private houseHoldService: HouseHoldService,
        private activatedRoute: ActivatedRoute
    ) {}

    ngOnInit() {
        this.isSaving = false;
        this.activatedRoute.data.subscribe(({ accountCategories }) => {
            this.accountCategories = accountCategories;
        });
        this.houseHoldService.query().subscribe(
            (res: HttpResponse<IHouseHold[]>) => {
                this.households = res.body;
            },
            (res: HttpErrorResponse) => this.onError(res.message)
        );
    }

    previousState() {
        window.history.back();
    }

    save() {
        this.isSaving = true;
        if (this.accountCategories.id !== undefined) {
            this.subscribeToSaveResponse(this.accountCategoriesService.update(this.accountCategories));
        } else {
            this.subscribeToSaveResponse(this.accountCategoriesService.create(this.accountCategories));
        }
    }

    private subscribeToSaveResponse(result: Observable<HttpResponse<IAccountCategories>>) {
        result.subscribe((res: HttpResponse<IAccountCategories>) => this.onSaveSuccess(), (res: HttpErrorResponse) => this.onSaveError());
    }

    private onSaveSuccess() {
        this.isSaving = false;
        this.previousState();
    }

    private onSaveError() {
        this.isSaving = false;
    }

    private onError(errorMessage: string) {
        this.jhiAlertService.error(errorMessage, null, null);
    }

    trackHouseHoldById(index: number, item: IHouseHold) {
        return item.id;
    }
}

<div class="row justify-content-center">
    <div class="col-8">
        <form name="editForm" role="form" novalidate (ngSubmit)="save()" #editForm="ngForm">
            <h2 id="eco-account-categories-heading" jhiTranslate="ecolarApp.accountCategories.home.createOrEditLabel">Create or edit a Account Categories</h2>
            <div>
                <eco-alert-error></eco-alert-error>
                <div class="form-group" [hidden]="!accountCategories.id">
                    <label for="id" jhiTranslate="global.field.id">ID</label>
                    <input type="text" class="form-control" id="id" name="id"
                        [(ngModel)]="accountCategories.id" readonly />
                </div>

            </div>
            <div>
                <button type="button" id="cancel-save" class="btn btn-secondary"  (click)="previousState()">
                    <fa-icon [icon]="'ban'"></fa-icon>&nbsp;<span jhiTranslate="entity.action.cancel">Cancel</span>
                </button>
                <button type="submit" id="save-entity" [disabled]="editForm.form.invalid || isSaving" class="btn btn-primary">
                    <fa-icon [icon]="'save'"></fa-icon>&nbsp;<span jhiTranslate="entity.action.save">Save</span>
                </button>
            </div>
        </form>
    </div>
</div>

// ecolar-mobile/src/main/webapp/app/entities/account-categories/account-categories-update.vue
<template>
    <div class="row justify-content-center">
        <div class="col-8">
            <form name="editForm" role="form" novalidate v-on:submit.prevent="save()" >
                <h2 id="ecolarApp.accountCategories.home.createOrEditLabel" v-text="$t('ecolarApp.accountCategories.home.createOrEditLabel')">Create or edit a AccountCategories</h2>
                <div>
                    <!--<jhi-alert-error></jhi-alert-error>-->
                    <div class="form-group" v-if="accountCategories.id">
                        <label for="id" v-text="$t('global.field.id')">ID</label>
                        <input type="text" class="form-control" id="id" name="id"
                               v-model="accountCategories.id" readonly />
                    </div>



                </div>
                <div>
                    <button type="button" id="cancel-save" class="btn btn-secondary" v-on:click="previousState()">
                        <font-awesome-icon icon="ban"></font-awesome-icon>&nbsp;<span v-text="$t('entity.action.cancel')">Cancel</span>
                    </button>
                    <button type="submit" id="save-entity" :disabled="$v.accountCategories.$invalid || isSaving" class="btn btn-primary">
                        <font-awesome-icon icon="save"></font-awesome-icon>&nbsp;<span v-text="$t('entity.action.save')">Save</span>
                    </button>
                </div>
            </form>
        </div>
    </div>
</template>
<script lang="ts" src="./account-categories-update.component.ts">
</script>
