// ecolar-admin/src/main/webapp/app/house-holds/e-account/e-account.component.ts
import { Component, OnInit, OnDestroy } from '@angular/core';
import { HttpErrorResponse, HttpResponse } from '@angular/common/http';
import { Subscription } from 'rxjs';
import { JhiEventManager, JhiAlertService } from 'ng-jhipster';

import { IEAccount } from 'app/shared/model/e-account.model';
import { Principal } from 'app/core';
import { EAccountService } from './e-account.service';

@Component({
    selector: 'eco-e-account',
    templateUrl: './e-account.component.html'
})
export class EAccountComponent implements OnInit, OnDestroy {
    eAccounts: IEAccount[];
    currentAccount: any;
    eventSubscriber: Subscription;

    constructor(
        private eAccountService: EAccountService,
        private jhiAlertService: JhiAlertService,
        private eventManager: JhiEventManager,
        private principal: Principal
    ) {}

    loadAll() {
        this.eAccountService.query().subscribe(
            (res: HttpResponse<IEAccount[]>) => {
                this.eAccounts = res.body;
            },
            (res: HttpErrorResponse) => this.onError(res.message)
        );
    }

    ngOnInit() {
        this.loadAll();
        this.principal.identity().then(account => {
            this.currentAccount = account;
        });
        this.registerChangeInEAccounts();
    }

    ngOnDestroy() {
        this.eventManager.destroy(this.eventSubscriber);
    }

    trackId(index: number, item: IEAccount) {
        return item.id;
    }

    registerChangeInEAccounts() {
        this.eventSubscriber = this.eventManager.subscribe('eAccountListModification', response => this.loadAll());
    }

    private onError(errorMessage: string) {
        this.jhiAlertService.error(errorMessage, null, null);
    }
}

<div>
    <h2 id="page-heading">
        <span jhiTranslate="ecolarApp.eAccount.home.title">E Accounts</span>
        <button id="jh-create-entity" class="btn btn-primary float-right jh-create-entity create-e-account" [routerLink]="['/e-account/new']">
            <fa-icon [icon]="'plus'"></fa-icon>
            <span  jhiTranslate="ecolarApp.eAccount.home.createLabel">
            Create new E Account
            </span>
        </button>
    </h2>
    <eco-alert></eco-alert>
    <br/>
    <div class="table-responsive" *ngIf="eAccounts">
        <table class="table table-striped">
            <thead>
            <tr>
            <th><span jhiTranslate="global.field.id">ID</span></th>
            <th><span jhiTranslate="ecolarApp.eAccount.accountCode">Account Code</span></th>
            <th><span jhiTranslate="ecolarApp.eAccount.accountName">Account Name</span></th>
            <th><span jhiTranslate="ecolarApp.eAccount.type">Type</span></th>
            <th><span jhiTranslate="ecolarApp.eAccount.category">Category</span></th>
            <th></th>
            </tr>
            </thead>
            <tbody>
            <tr *ngFor="let eAccount of eAccounts ;trackBy: trackId">
                <td><a [routerLink]="['/e-account', eAccount.id, 'view' ]">{{eAccount.id}}</a></td>
                <td>{{eAccount.accountCode}}</td>
                <td>{{eAccount.accountName}}</td>
                <td jhiTranslate="{{'ecolarApp.AccountType.' + eAccount.type}}">{{eAccount.type}}</td>
                <td>
                    <div *ngIf="eAccount.category">
                        <a [routerLink]="['../category', eAccount.category?.id, 'view' ]" >{{eAccount.category?.name}}</a>
                    </div>
                </td>
                <td class="text-right">
                    <div class="btn-group flex-btn-group-container">
                        <button type="submit"
                                [routerLink]="['/e-account', eAccount.id, 'view' ]"
                                class="btn btn-info btn-sm">
                            <fa-icon [icon]="'eye'"></fa-icon>
                            <span class="d-none d-md-inline" jhiTranslate="entity.action.view">View</span>
                        </button>
                        <button type="submit"
                                [routerLink]="['/e-account', eAccount.id, 'edit']"
                                class="btn btn-primary btn-sm">
                            <fa-icon [icon]="'pencil-alt'"></fa-icon>
                            <span class="d-none d-md-inline" jhiTranslate="entity.action.edit">Edit</span>
                        </button>
                        <button type="submit"
                                [routerLink]="['/', { outlets: { popup: 'e-account/'+ eAccount.id + '/delete'} }]"
                                replaceUrl="true"
                                queryParamsHandling="merge"
                                class="btn btn-danger btn-sm">
                            <fa-icon [icon]="'times'"></fa-icon>
                            <span class="d-none d-md-inline" jhiTranslate="entity.action.delete">Delete</span>
                        </button>
                    </div>
                </td>
            </tr>
            </tbody>
        </table>
    </div>
</div>

// ecolar-mobile/src/main/webapp/app/entities/e-account/e-account.vue
<template>
    <div>
        <h2 id="page-heading">
            <span v-text="$t('ecolarApp.eAccount.home.title')" id="e-account-heading">E Accounts</span>
            <router-link to="/entity/e-account/new" tag="button" id="jh-create-entity" class="btn btn-primary float-right jh-create-entity create-e-account">
                <font-awesome-icon icon="plus"></font-awesome-icon>
                <span  v-text="$t('ecolarApp.eAccount.home.createLabel')">
                    Create new EAccount
                </span>
            </router-link>
        </h2>
        <!--<jhi-alert></jhi-alert>-->
        <br/>
        <div class="table-responsive" v-if="eAccounts">
            <table class="table table-striped">
                <thead>
                <tr>
                    <th><span v-text="$t('global.field.id')">ID</span></th>
                        <th><span v-text="$t('ecolarApp.eAccount.accountCode')">Account Code</span></th>
                        <th><span v-text="$t('ecolarApp.eAccount.accountName')">Account Name</span></th>
                        <th><span v-text="$t('ecolarApp.eAccount.type')">Type</span></th>
                            <th><span v-text="$t('ecolarApp.eAccount.category')">Category</span></th>
                    <th></th>
                </tr>
                </thead>
                <tbody>
                <tr v-for="eAccount in eAccounts">
                    <td><router-link :to="{name: 'EAccountView', params: {eAccountId: eAccount.id}}">{{eAccount.id}}</router-link></td>
                            <td>{{eAccount.accountCode}}</td>
                            <td>{{eAccount.accountName}}</td>
                            <td v-text="$t('ecolarApp.AccountType.' + eAccount.type)">{{eAccount.type}}</td>
                        <td>
                                        <div v-if="eAccount.category">
                                            <router-link :to="'../entity/category/' + eAccount.category.id + '/view'" >{{eAccount.category.name}}</router-link>
                                        </div>
                        </td>
                    <td class="text-right">
                        <div class="btn-group flex-btn-group-container">
                            <router-link :to="{name: 'EAccountView', params: {eAccountId: eAccount.id}}" tag="button" class="btn btn-info btn-sm">
                                <font-awesome-icon icon="eye"></font-awesome-icon>
                                <span class="d-none d-md-inline" v-text="$t('entity.action.view')">View</span>
                            </router-link>
                            <router-link :to="{name: 'EAccountEdit', params: {eAccountId: eAccount.id}}"  tag="button" class="btn btn-primary btn-sm">
                                <font-awesome-icon icon="pencil-alt"></font-awesome-icon>
                                <span class="d-none d-md-inline" v-text="$t('entity.action.edit')">Edit</span>
                            </router-link>
                            <b-btn v-on:click="prepareRemove(eAccount)"
                                   class="btn btn-danger btn-sm"
                                   v-b-modal.removeEntity>
                                <font-awesome-icon icon="times"></font-awesome-icon>
                                <span class="d-none d-md-inline" v-text="$t('entity.action.delete')">Delete</span>
                            </b-btn>
                        </div>
                    </td>
                </tr>
                </tbody>
            </table>
        </div>
        <b-modal ref="removeEntity" id="removeEntity" >
            <span slot="modal-title"><span id="ecolarApp.eAccount.delete.question" v-text="$t('entity.delete.title')">Confirm delete operation</span></span>
            <div class="modal-body">
                <p id="eco-delete-eAccount-heading" v-bind:title="$t('ecolarApp.eAccount.delete.question')">Are you sure you want to delete this E Account?</p>
            </div>
            <div slot="modal-footer">
                <button type="button" class="btn btn-secondary" v-text="$t('entity.action.cancel')" v-on:click="closeDialog()">Cancel</button>
                <button type="button" class="btn btn-primary" id="eco-confirm-delete-eAccount" v-text="$t('entity.action.delete')" v-on:click="removeEAccount()">Delete</button>
            </div>
        </b-modal>
    </div>
</template>

<script lang="ts" src="./e-account.component.ts">
</script>
