// ecolarMobile/src/main/webapp/app/entities/e-account/e-account-update.tsx
import React from 'react';
import { connect } from 'react-redux';
import { Link, RouteComponentProps } from 'react-router-dom';
import { Button, Row, Col, Label } from 'reactstrap';
import { AvForm, AvGroup, AvInput, AvField } from 'availity-reactstrap-validation';
// tslint:disable-next-line:no-unused-variable
import { Translate, translate, ICrudGetAction, ICrudGetAllAction, ICrudPutAction } from 'react-jhipster';
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome';
import { IRootState } from 'app/shared/reducers';

import { ICategory } from 'app/shared/model/category.model';
import { getEntities as getCategories } from 'app/entities/category/category.reducer';
import { getEntity, updateEntity, createEntity, reset } from './e-account.reducer';
import { IEAccount } from 'app/shared/model/e-account.model';
// tslint:disable-next-line:no-unused-variable
import { convertDateTimeFromServer } from 'app/shared/util/date-utils';
import { mapIdList } from 'app/shared/util/entity-utils';

export interface IEAccountUpdateProps extends StateProps, DispatchProps, RouteComponentProps<{ id: string }> {}

export interface IEAccountUpdateState {
  isNew: boolean;
  categoryId: string;
}

export class EAccountUpdate extends React.Component<IEAccountUpdateProps, IEAccountUpdateState> {
  constructor(props) {
    super(props);
    this.state = {
      categoryId: '0',
      isNew: !this.props.match.params || !this.props.match.params.id
    };
  }

  componentDidMount() {
    if (this.state.isNew) {
      this.props.reset();
    } else {
      this.props.getEntity(this.props.match.params.id);
    }

    this.props.getCategories();
  }

  saveEntity = (event, errors, values) => {
    if (errors.length === 0) {
      const { eAccountEntity } = this.props;
      const entity = {
        ...eAccountEntity,
        ...values
      };

      if (this.state.isNew) {
        this.props.createEntity(entity);
      } else {
        this.props.updateEntity(entity);
      }
      this.handleClose();
    }
  };

  handleClose = () => {
    this.props.history.push('/entity/e-account');
  };

  render() {
    const { eAccountEntity, categories, loading, updating } = this.props;
    const { isNew } = this.state;

    return (
      <div>
        <Row className="justify-content-center">
          <Col md="8">
            <h2 id="ecolarMobileApp.eAccount.home.createOrEditLabel">
              <Translate contentKey="ecolarMobileApp.eAccount.home.createOrEditLabel">Create or edit a EAccount</Translate>
            </h2>
          </Col>
        </Row>
        <Row className="justify-content-center">
          <Col md="8">
            {loading ? (
              <p>Loading...</p>
            ) : (
              <AvForm model={isNew ? {} : eAccountEntity} onSubmit={this.saveEntity}>
                {!isNew ? (
                  <AvGroup>
                    <Label for="id">
                      <Translate contentKey="global.field.id">ID</Translate>
                    </Label>
                    <AvInput id="e-account-id" type="text" className="form-control" name="id" required readOnly />
                  </AvGroup>
                ) : null}
                <AvGroup>
                  <Label id="accountCodeLabel" for="accountCode">
                    <Translate contentKey="ecolarMobileApp.eAccount.accountCode">Account Code</Translate>
                  </Label>
                  <AvField id="e-account-accountCode" type="text" name="accountCode" />
                </AvGroup>
                <AvGroup>
                  <Label id="accountNameLabel" for="accountName">
                    <Translate contentKey="ecolarMobileApp.eAccount.accountName">Account Name</Translate>
                  </Label>
                  <AvField id="e-account-accountName" type="text" name="accountName" />
                </AvGroup>
                <AvGroup>
                  <Label id="typeLabel">
                    <Translate contentKey="ecolarMobileApp.eAccount.type">Type</Translate>
                  </Label>
                  <AvInput
                    id="e-account-type"
                    type="select"
                    className="form-control"
                    name="type"
                    value={(!isNew && eAccountEntity.type) || 'ASSETS'}
                  >
                    <option value="ASSETS">
                      <Translate contentKey="ecolarMobileApp.AccountType.ASSETS" />
                    </option>
                    <option value="LIABILITIES">
                      <Translate contentKey="ecolarMobileApp.AccountType.LIABILITIES" />
                    </option>
                    <option value="REVENUE">
                      <Translate contentKey="ecolarMobileApp.AccountType.REVENUE" />
                    </option>
                    <option value="EXPENSE">
                      <Translate contentKey="ecolarMobileApp.AccountType.EXPENSE" />
                    </option>
                  </AvInput>
                </AvGroup>
                <AvGroup>
                  <Label for="category.name">
                    <Translate contentKey="ecolarMobileApp.eAccount.category">Category</Translate>
                  </Label>
                  <AvInput id="e-account-category" type="select" className="form-control" name="category.id">
                    <option value="" key="0" />
                    {categories
                      ? categories.map(otherEntity => (
                          <option value={otherEntity.id} key={otherEntity.id}>
                            {otherEntity.name}
                          </option>
                        ))
                      : null}
                  </AvInput>
                </AvGroup>
                <Button tag={Link} id="cancel-save" to="/entity/e-account" replace color="info">
                  <FontAwesomeIcon icon="arrow-left" />&nbsp;
                  <span className="d-none d-md-inline">
                    <Translate contentKey="entity.action.back">Back</Translate>
                  </span>
                </Button>
                &nbsp;
                <Button color="primary" id="save-entity" type="submit" disabled={updating}>
                  <FontAwesomeIcon icon="save" />&nbsp;
                  <Translate contentKey="entity.action.save">Save</Translate>
                </Button>
              </AvForm>
            )}
          </Col>
        </Row>
      </div>
    );
  }
}

const mapStateToProps = (storeState: IRootState) => ({
  categories: storeState.category.entities,
  eAccountEntity: storeState.eAccount.entity,
  loading: storeState.eAccount.loading,
  updating: storeState.eAccount.updating
});

const mapDispatchToProps = {
  getCategories,
  getEntity,
  updateEntity,
  createEntity,
  reset
};

type StateProps = ReturnType<typeof mapStateToProps>;
type DispatchProps = typeof mapDispatchToProps;

export default connect(
  mapStateToProps,
  mapDispatchToProps
)(EAccountUpdate);

// ecolar-mobile/src/main/webapp/app/entities/e-account/e-account-update.vue
<template>
    <div class="row justify-content-center">
        <div class="col-8">
            <form name="editForm" role="form" novalidate v-on:submit.prevent="save()" >
                <h2 id="ecolarApp.eAccount.home.createOrEditLabel" v-text="$t('ecolarApp.eAccount.home.createOrEditLabel')">Create or edit a EAccount</h2>
                <div>
                    <!--<jhi-alert-error></jhi-alert-error>-->
                    <div class="form-group" v-if="eAccount.id">
                        <label for="id" v-text="$t('global.field.id')">ID</label>
                        <input type="text" class="form-control" id="id" name="id"
                               v-model="eAccount.id" readonly />
                    </div>

                    <div class="form-group">
                        <label class="form-control-label" v-text="$t('ecolarApp.eAccount.accountCode')" for="e-account-accountCode">Account Code</label>
                        <input type="text" class="form-control" name="accountCode" id="e-account-accountCode"
                            :class="{'valid': !$v.eAccount.accountCode.$invalid, 'invalid': $v.eAccount.accountCode.$invalid }" v-model="$v.eAccount.accountCode.$model" />
                    </div>
                    <div class="form-group">
                        <label class="form-control-label" v-text="$t('ecolarApp.eAccount.accountName')" for="e-account-accountName">Account Name</label>
                        <input type="text" class="form-control" name="accountName" id="e-account-accountName"
                            :class="{'valid': !$v.eAccount.accountName.$invalid, 'invalid': $v.eAccount.accountName.$invalid }" v-model="$v.eAccount.accountName.$model" />
                    </div>
                    <div class="form-group">
                        <label class="form-control-label" v-text="$t('ecolarApp.eAccount.type')" for="e-account-type">Type</label>
                        <select class="form-control" name="type" :class="{'valid': !$v.eAccount.type.$invalid, 'invalid': $v.eAccount.type.$invalid }" v-model="$v.eAccount.type.$model" id="e-account-type" >
                            <option value="ASSETS" v-bind:label="$t('ecolarApp.AccountType.ASSETS')">ASSETS</option>
                            <option value="LIABILITIES" v-bind:label="$t('ecolarApp.AccountType.LIABILITIES')">LIABILITIES</option>
                            <option value="REVENUE" v-bind:label="$t('ecolarApp.AccountType.REVENUE')">REVENUE</option>
                            <option value="EXPENSE" v-bind:label="$t('ecolarApp.AccountType.EXPENSE')">EXPENSE</option>
                        </select>
                    </div>

                        <div class="form-group">
                            <label class="form-control-label" v-bind:value="$t('ecolarApp.eAccount.category')" for="e-account-category">Category</label>
                                <select class="form-control" id="e-account-category" name="category" v-model="eAccount.category" >
                                    <option value="null"></option>
                                    <option v-bind:value="eAccount.category && categoryOption.id === eAccount.category.id ? eAccount.category : categoryOption" v-for="categoryOption in categories">{{categoryOption.name}}</option>
                                </select>
                        </div>

                </div>
                <div>
                    <button type="button" id="cancel-save" class="btn btn-secondary" v-on:click="previousState()">
                        <font-awesome-icon icon="ban"></font-awesome-icon>&nbsp;<span v-text="$t('entity.action.cancel')">Cancel</span>
                    </button>
                    <button type="submit" id="save-entity" :disabled="$v.eAccount.$invalid || isSaving" class="btn btn-primary">
                        <font-awesome-icon icon="save"></font-awesome-icon>&nbsp;<span v-text="$t('entity.action.save')">Save</span>
                    </button>
                </div>
            </form>
        </div>
    </div>
</template>
<script lang="ts" src="./e-account-update.component.ts">
</script>
