// ecolar-admin/src/main/webapp/app/house-holds/e-account/e-account-update.component.ts
import { Component, OnInit } from '@angular/core';
import { ActivatedRoute } from '@angular/router';
import { HttpResponse, HttpErrorResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { JhiAlertService } from 'ng-jhipster';

import { IEAccount } from 'app/shared/model/e-account.model';
import { EAccountService } from './e-account.service';
import { ICategory } from 'app/shared/model/category.model';
import { HouseHoldService } from '../house-hold.service';

@Component({
    selector: 'eco-e-account-update',
    templateUrl: './e-account-update.component.html'
})
export class EAccountUpdateComponent implements OnInit {
    eAccount: IEAccount;
    isSaving: boolean;

    categories: ICategory[];

    constructor(
        private jhiAlertService: JhiAlertService,
        private eAccountService: EAccountService,
        private categoryService: HouseHoldService,
        private activatedRoute: ActivatedRoute
    ) {}

    ngOnInit() {
        this.isSaving = false;
        this.activatedRoute.data.subscribe(({ eAccount }) => {
            this.eAccount = eAccount;
        });
        this.categoryService.query().subscribe(
            (res: HttpResponse<ICategory[]>) => {
                this.categories = res.body;
            },
            (res: HttpErrorResponse) => this.onError(res.message)
        );
    }

    previousState() {
        window.history.back();
    }

    save() {
        this.isSaving = true;
        if (this.eAccount.id !== undefined) {
            this.subscribeToSaveResponse(this.eAccountService.update(this.eAccount));
        } else {
            this.subscribeToSaveResponse(this.eAccountService.create(this.eAccount));
        }
    }

    private subscribeToSaveResponse(result: Observable<HttpResponse<IEAccount>>) {
        result.subscribe((res: HttpResponse<IEAccount>) => this.onSaveSuccess(), (res: HttpErrorResponse) => this.onSaveError());
    }

    private onSaveSuccess() {
        this.isSaving = false;
        this.previousState();
    }

    private onSaveError() {
        this.isSaving = false;
    }

    private onError(errorMessage: string) {
        this.jhiAlertService.error(errorMessage, null, null);
    }

    trackCategoryById(index: number, item: ICategory) {
        return item.id;
    }
}

<div class="row justify-content-center">
    <div class="col-8">
        <form name="editForm" role="form" novalidate (ngSubmit)="save()" #editForm="ngForm">
            <h2 id="eco-e-account-heading" jhiTranslate="ecolarApp.eAccount.home.createOrEditLabel">Create or edit a E Account</h2>
            <div>
                <eco-alert-error></eco-alert-error>
                <div class="form-group" [hidden]="!eAccount.id">
                    <label for="id" jhiTranslate="global.field.id">ID</label>
                    <input type="text" class="form-control" id="id" name="id"
                        [(ngModel)]="eAccount.id" readonly />
                </div>
                <div class="form-group">
                    <label class="form-control-label" jhiTranslate="ecolarApp.eAccount.accountCode" for="field_accountCode">Account Code</label>
                    <input type="text" class="form-control" name="accountCode" id="field_accountCode"
                        [(ngModel)]="eAccount.accountCode" />
                </div>
                <div class="form-group">
                    <label class="form-control-label" jhiTranslate="ecolarApp.eAccount.accountName" for="field_accountName">Account Name</label>
                    <input type="text" class="form-control" name="accountName" id="field_accountName"
                        [(ngModel)]="eAccount.accountName" />
                </div>
                <div class="form-group">
                    <label class="form-control-label" jhiTranslate="ecolarApp.eAccount.type" for="field_type">Type</label>
                    <select class="form-control" name="type" [(ngModel)]="eAccount.type" id="field_type" >
                        <option value="ASSETS">{{'ecolarApp.AccountType.ASSETS' | translate}}</option>
                        <option value="LIABILITIES">{{'ecolarApp.AccountType.LIABILITIES' | translate}}</option>
                        <option value="REVENUE">{{'ecolarApp.AccountType.REVENUE' | translate}}</option>
                        <option value="EXPENSE">{{'ecolarApp.AccountType.EXPENSE' | translate}}</option>
                    </select>
                </div>

                <div class="form-group">
                    <label class="form-control-label" jhiTranslate="ecolarApp.eAccount.category" for="field_category">Category</label>
                    <select class="form-control" id="field_category" name="categoryId" [(ngModel)]="eAccount.categoryId" >
                        <option [ngValue]="null"></option>
                        <option [ngValue]="categoryOption.id" *ngFor="let categoryOption of categories; trackBy: trackCategoryById">{{categoryOption.path}}</option>
                    </select>
                </div>
            </div>
            <div>
                <button type="button" id="cancel-save" class="btn btn-secondary"  (click)="previousState()">
                    <fa-icon [icon]="'ban'"></fa-icon>&nbsp;<span jhiTranslate="entity.action.cancel">Cancel</span>
                </button>
                <button type="submit" id="save-entity" [disabled]="editForm.form.invalid || isSaving" class="btn btn-primary">
                    <fa-icon [icon]="'save'"></fa-icon>&nbsp;<span jhiTranslate="entity.action.save">Save</span>
                </button>
            </div>
        </form>
    </div>
</div>

// ecolar-mobile/src/main/webapp/app/entities/e-account/e-account-update.vue
<template>
    <div class="row justify-content-center">
        <div class="col-8">
            <form name="editForm" role="form" novalidate v-on:submit.prevent="save()" >
                <h2 id="ecolarApp.eAccount.home.createOrEditLabel" v-text="$t('ecolarApp.eAccount.home.createOrEditLabel')">Create or edit a EAccount</h2>
                <div>
                    <!--<jhi-alert-error></jhi-alert-error>-->
                    <div class="form-group" v-if="eAccount.id">
                        <label for="id" v-text="$t('global.field.id')">ID</label>
                        <input type="text" class="form-control" id="id" name="id"
                               v-model="eAccount.id" readonly />
                    </div>

                    <div class="form-group">
                        <label class="form-control-label" v-text="$t('ecolarApp.eAccount.accountCode')" for="e-account-accountCode">Account Code</label>
                        <input type="text" class="form-control" name="accountCode" id="e-account-accountCode"
                            :class="{'valid': !$v.eAccount.accountCode.$invalid, 'invalid': $v.eAccount.accountCode.$invalid }" v-model="$v.eAccount.accountCode.$model" />
                    </div>
                    <div class="form-group">
                        <label class="form-control-label" v-text="$t('ecolarApp.eAccount.accountName')" for="e-account-accountName">Account Name</label>
                        <input type="text" class="form-control" name="accountName" id="e-account-accountName"
                            :class="{'valid': !$v.eAccount.accountName.$invalid, 'invalid': $v.eAccount.accountName.$invalid }" v-model="$v.eAccount.accountName.$model" />
                    </div>
                    <div class="form-group">
                        <label class="form-control-label" v-text="$t('ecolarApp.eAccount.type')" for="e-account-type">Type</label>
                        <select class="form-control" name="type" :class="{'valid': !$v.eAccount.type.$invalid, 'invalid': $v.eAccount.type.$invalid }" v-model="$v.eAccount.type.$model" id="e-account-type" >
                            <option value="ASSETS" v-bind:label="$t('ecolarApp.AccountType.ASSETS')">ASSETS</option>
                            <option value="LIABILITIES" v-bind:label="$t('ecolarApp.AccountType.LIABILITIES')">LIABILITIES</option>
                            <option value="REVENUE" v-bind:label="$t('ecolarApp.AccountType.REVENUE')">REVENUE</option>
                            <option value="EXPENSE" v-bind:label="$t('ecolarApp.AccountType.EXPENSE')">EXPENSE</option>
                        </select>
                    </div>

                        <div class="form-group">
                            <label class="form-control-label" v-bind:value="$t('ecolarApp.eAccount.category')" for="e-account-category">Category</label>
                                <select class="form-control" id="e-account-category" name="category" v-model="eAccount.category" >
                                    <option value="null"></option>
                                    <option v-bind:value="eAccount.category && categoryOption.id === eAccount.category.id ? eAccount.category : categoryOption" v-for="categoryOption in categories">{{categoryOption.name}}</option>
                                </select>
                        </div>

                </div>
                <div>
                    <button type="button" id="cancel-save" class="btn btn-secondary" v-on:click="previousState()">
                        <font-awesome-icon icon="ban"></font-awesome-icon>&nbsp;<span v-text="$t('entity.action.cancel')">Cancel</span>
                    </button>
                    <button type="submit" id="save-entity" :disabled="$v.eAccount.$invalid || isSaving" class="btn btn-primary">
                        <font-awesome-icon icon="save"></font-awesome-icon>&nbsp;<span v-text="$t('entity.action.save')">Save</span>
                    </button>
                </div>
            </form>
        </div>
    </div>
</template>
<script lang="ts" src="./e-account-update.component.ts">
</script>
