// ecolar-mobile/src/main/webapp/app/entities/category/category.vue
<template>
    <div>
        <h2 id="page-heading">
            <span v-text="$t('ecolarApp.category.home.title')" id="category-heading">Categories</span>
            <router-link to="/entity/category/new" tag="button" id="jh-create-entity" class="btn btn-primary float-right jh-create-entity create-category">
                <font-awesome-icon icon="plus"></font-awesome-icon>
                <span  v-text="$t('ecolarApp.category.home.createLabel')">
                    Create new Category
                </span>
            </router-link>
        </h2>
        <!--<jhi-alert></jhi-alert>-->
        <br/>
        <div class="table-responsive" v-if="categories">
            <table class="table table-striped">
                <thead>
                <tr>
                    <th><span v-text="$t('global.field.id')">ID</span></th>
                        <th><span v-text="$t('ecolarApp.category.name')">Name</span></th>
                        <th><span v-text="$t('ecolarApp.category.description')">Description</span></th>
                        <th><span v-text="$t('ecolarApp.category.path')">Path</span></th>
                        <th><span v-text="$t('ecolarApp.category.parentId')">Parent Id</span></th>
                        <th><span v-text="$t('ecolarApp.category.accountType')">Account Type</span></th>
                            <th><span v-text="$t('ecolarApp.category.parent')">Parent</span></th>
                            <th><span v-text="$t('ecolarApp.category.document')">Document</span></th>
                    <th></th>
                </tr>
                </thead>
                <tbody>
                <tr v-for="category in categories">
                    <td><router-link :to="{name: 'CategoryView', params: {categoryId: category.id}}">{{category.id}}</router-link></td>
                            <td>{{category.name}}</td>
                            <td>{{category.description}}</td>
                            <td>{{category.path}}</td>
                            <td>{{category.parentId}}</td>
                            <td v-text="$t('ecolarApp.AccountType.' + category.accountType)">{{category.accountType}}</td>
                        <td>
                                        <div v-if="category.parent">
                                            <router-link :to="'../category/' + category.parent.id + '/View'" >{{category.parent.name}}</router-link>
                                        </div>
                        </td>
                        <td>
                                        <div v-if="category.document">
                                            <router-link :to="'../account-categories/' + category.document.id + '/View'" >{{category.document.id}}</router-link>
                                        </div>
                        </td>
                    <td class="text-right">
                        <div class="btn-group flex-btn-group-container">
                            <router-link :to="{name: 'CategoryView', params: {categoryId: category.id}}" tag="button" class="btn btn-info btn-sm">
                                <font-awesome-icon icon="eye"></font-awesome-icon>
                                <span class="d-none d-md-inline" v-text="$t('entity.action.view')">View</span>
                            </router-link>
                            <router-link :to="{name: 'CategoryEdit', params: {categoryId: category.id}}"  tag="button" class="btn btn-primary btn-sm">
                                <font-awesome-icon icon="pencil-alt"></font-awesome-icon>
                                <span class="d-none d-md-inline" v-text="$t('entity.action.edit')">Edit</span>
                            </router-link>
                            <b-btn v-on:click="prepareRemove(category)"
                                   class="btn btn-danger btn-sm"
                                   v-b-modal.removeEntity>
                                <font-awesome-icon icon="times"></font-awesome-icon>
                                <span class="d-none d-md-inline" v-text="$t('entity.action.delete')">Delete</span>
                            </b-btn>
                        </div>
                    </td>
                </tr>
                </tbody>
            </table>
        </div>
        <b-modal ref="removeEntity" id="removeEntity" >
            <span slot="modal-title"><span id="ecolarApp.category.delete.question" v-text="$t('entity.delete.title')">Confirm delete operation</span></span>
            <div class="modal-body">
                <p id="eco-delete-category-heading" v-bind:title="$t('ecolarApp.category.delete.question')">Are you sure you want to delete this Category?</p>
            </div>
            <div slot="modal-footer">
                <button type="button" class="btn btn-secondary" v-text="$t('entity.action.cancel')" v-on:click="closeDialog()">Cancel</button>
                <button type="button" class="btn btn-primary" id="eco-confirm-delete-category" v-text="$t('entity.action.delete')" v-on:click="removeCategory()">Delete</button>
            </div>
        </b-modal>
    </div>
</template>

<script lang="ts" src="./category.component.ts">
</script>

// ecolarAdmin/src/main/webapp/app/house-hold-administration/category/category.component.ts
import { Component, OnInit, OnDestroy } from '@angular/core';
import { HttpErrorResponse, HttpResponse } from '@angular/common/http';
import { Subscription } from 'rxjs';
import { JhiEventManager, JhiAlertService } from 'ng-jhipster';

import { ICategory } from 'app/shared/model/category.model';
import { Principal } from 'app/core';
import { CategoryService } from './category.service';

@Component({
    selector: 'eco-category',
    templateUrl: './category.component.html'
})
export class CategoryComponent implements OnInit, OnDestroy {
    categories: ICategory[];
    currentAccount: any;
    eventSubscriber: Subscription;

    constructor(
        private categoryService: CategoryService,
        private jhiAlertService: JhiAlertService,
        private eventManager: JhiEventManager,
        private principal: Principal
    ) {}

    loadAll() {
        this.categoryService.query().subscribe(
            (res: HttpResponse<ICategory[]>) => {
                this.categories = res.body;
            },
            (res: HttpErrorResponse) => this.onError(res.message)
        );
    }

    ngOnInit() {
        this.loadAll();
        this.principal.identity().then(account => {
            this.currentAccount = account;
        });
        this.registerChangeInCategories();
    }

    ngOnDestroy() {
        this.eventManager.destroy(this.eventSubscriber);
    }

    trackId(index: number, item: ICategory) {
        return item.id;
    }

    registerChangeInCategories() {
        this.eventSubscriber = this.eventManager.subscribe('categoryListModification', response => this.loadAll());
    }

    private onError(errorMessage: string) {
        this.jhiAlertService.error(errorMessage, null, null);
    }
}

<div>
    <h2 id="page-heading">
        <span jhiTranslate="ecolarAdminApp.category.home.title">Categories</span>
        <button id="jh-create-entity" class="btn btn-primary float-right jh-create-entity create-category" [routerLink]="['/category/new']">
            <fa-icon [icon]="'plus'"></fa-icon>
            <span  jhiTranslate="ecolarAdminApp.category.home.createLabel">
            Create new Category
            </span>
        </button>
    </h2>
    <eco-alert></eco-alert>
    <br/>
    <div class="table-responsive" *ngIf="categories">
        <table class="table table-striped">
            <thead>
            <tr>
            <th><span jhiTranslate="global.field.id">ID</span></th>
            <th><span jhiTranslate="ecolarAdminApp.category.name">Name</span></th>
            <th><span jhiTranslate="ecolarAdminApp.category.description">Description</span></th>
            <th><span jhiTranslate="ecolarAdminApp.category.path">Path</span></th>
            <th><span jhiTranslate="ecolarAdminApp.category.parentId">Parent Id</span></th>
            <th><span jhiTranslate="ecolarAdminApp.category.accountType">Account Type</span></th>
            <th><span jhiTranslate="ecolarAdminApp.category.parent">Parent</span></th>
            <th><span jhiTranslate="ecolarAdminApp.category.document">Document</span></th>
            <th></th>
            </tr>
            </thead>
            <tbody>
            <tr *ngFor="let category of categories ;trackBy: trackId">
                <td><a [routerLink]="['/category', category.id, 'view' ]">{{category.id}}</a></td>
                <td>{{category.name}}</td>
                <td>{{category.description}}</td>
                <td>{{category.path}}</td>
                <td>{{category.parentId}}</td>
                <td jhiTranslate="{{'ecolarAdminApp.AccountType.' + category.accountType}}">{{category.accountType}}</td>
                <td>
                    <div *ngIf="category.parent">
                        <a [routerLink]="['../category', category.parent?.id, 'view' ]" >{{category.parent?.name}}</a>
                    </div>
                </td>
                <td>
                    <div *ngIf="category.document">
                        <a [routerLink]="['../accounts-document', category.document?.id, 'view' ]" >{{category.document?.id}}</a>
                    </div>
                </td>
                <td class="text-right">
                    <div class="btn-group flex-btn-group-container">
                        <button type="submit"
                                [routerLink]="['/category', category.id, 'view' ]"
                                class="btn btn-info btn-sm">
                            <fa-icon [icon]="'eye'"></fa-icon>
                            <span class="d-none d-md-inline" jhiTranslate="entity.action.view">View</span>
                        </button>
                        <button type="submit"
                                [routerLink]="['/category', category.id, 'edit']"
                                class="btn btn-primary btn-sm">
                            <fa-icon [icon]="'pencil-alt'"></fa-icon>
                            <span class="d-none d-md-inline" jhiTranslate="entity.action.edit">Edit</span>
                        </button>
                        <button type="submit"
                                [routerLink]="['/', { outlets: { popup: 'category/'+ category.id + '/delete'} }]"
                                replaceUrl="true"
                                queryParamsHandling="merge"
                                class="btn btn-danger btn-sm">
                            <fa-icon [icon]="'times'"></fa-icon>
                            <span class="d-none d-md-inline" jhiTranslate="entity.action.delete">Delete</span>
                        </button>
                    </div>
                </td>
            </tr>
            </tbody>
        </table>
    </div>
</div>
